apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saffron-hive-data
  labels:
    app.kubernetes.io/name: saffron-hive
    app.kubernetes.io/component: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
