package device

import "fmt"

// GroupID is a unique identifier for a group (UUID, generated by the system).
type GroupID string

// Group is a named collection of devices or other groups.
type Group struct {
	ID   GroupID
	Name string
}

// GroupMemberType classifies what kind of entity a group member is.
type GroupMemberType string

const (
	// GroupMemberDevice indicates the member is a device.
	GroupMemberDevice GroupMemberType = "device"
	// GroupMemberGroup indicates the member is another group.
	GroupMemberGroup GroupMemberType = "group"
	// GroupMemberRoom indicates the member is a room.
	GroupMemberRoom GroupMemberType = "room"
)

// GroupMember represents a membership relationship between a group and a device or another group.
type GroupMember struct {
	GroupID    GroupID
	MemberType GroupMemberType
	MemberID   string
}

// ErrGroupNotFound is returned when a group does not exist.
var ErrGroupNotFound = fmt.Errorf("group not found")

// ErrCircularDependency is returned when adding a group member would create a cycle.
var ErrCircularDependency = fmt.Errorf("circular dependency detected")
