package device

import "fmt"

// GroupID is a unique identifier for a group (UUID, generated by the system).
type GroupID string

// Group is a named collection of devices or other groups.
type Group struct {
	ID   GroupID
	Name string
}

// GroupTag classifies a group by the role it represents on the dashboard.
// A group can carry zero, one, or both tags simultaneously. Tags are decorative
// metadata for now; only the dashboard renderer interprets them (LIGHT collapses
// a group's member bulbs into a single virtual light card).
type GroupTag string

const (
	// GroupTagLight marks the group as representing a single virtual light
	// (e.g., a lamp built from multiple bulbs).
	GroupTagLight GroupTag = "light"
	// GroupTagSensor marks the group as representing sensor data.
	GroupTagSensor GroupTag = "sensor"
)

// IsValidGroupTag reports whether t is a recognised GroupTag value.
func IsValidGroupTag(t GroupTag) bool {
	switch t {
	case GroupTagLight, GroupTagSensor:
		return true
	}
	return false
}

// GroupMemberType classifies what kind of entity a group member is.
type GroupMemberType string

const (
	// GroupMemberDevice indicates the member is a device.
	GroupMemberDevice GroupMemberType = "device"
	// GroupMemberGroup indicates the member is another group.
	GroupMemberGroup GroupMemberType = "group"
	// GroupMemberRoom indicates the member is a room.
	GroupMemberRoom GroupMemberType = "room"
)

// GroupMember represents a membership relationship between a group and a device or another group.
type GroupMember struct {
	GroupID    GroupID
	MemberType GroupMemberType
	MemberID   string
}

// ErrGroupNotFound is returned when a group does not exist.
var ErrGroupNotFound = fmt.Errorf("group not found")

// ErrCircularDependency is returned when adding a group member would create a cycle.
var ErrCircularDependency = fmt.Errorf("circular dependency detected")
