package device

import "time"

// DeviceID is a unique identifier for a device (UUID, generated by the system).
type DeviceID string

// Source identifies the integration a device was discovered through, and
// doubles as the integration's provider id in the GraphQL API.
type Source string

const (
	// SourceZigbee2MQTT covers Zigbee devices bridged onto MQTT by zigbee2mqtt.
	SourceZigbee2MQTT Source = "zigbee2mqtt"
	// SourceTuya covers devices reached through the Tuya cloud API.
	SourceTuya Source = "tuya"
)

// DeviceType classifies a device by its primary function.
type DeviceType string

const (
	// Light represents a controllable light device.
	Light DeviceType = "light"
	// Sensor represents a device that reports environmental readings.
	Sensor DeviceType = "sensor"
	// Button represents an input device that reports discrete action events
	// (e.g. single / double / hold) without an on/off state of its own.
	Button DeviceType = "button"
	// Plug represents a switchable outlet, usually with on/off control and
	// often with power metering (power, voltage, current, energy).
	Plug DeviceType = "plug"
	// Climate represents a heating/cooling device with thermostat-like controls.
	Climate DeviceType = "climate"
	// Speaker represents an audio output device.
	Speaker DeviceType = "speaker"
	// Unknown represents a device whose type could not be determined.
	Unknown DeviceType = "unknown"
)

// DeviceTag marks user-owned device roles that supplement the adapter-detected type.
type DeviceTag string

const (
	DeviceTagLight DeviceTag = "LIGHT"
)

// IsValidDeviceTag reports whether t is a supported device tag.
func IsValidDeviceTag(t DeviceTag) bool {
	switch t {
	case DeviceTagLight:
		return true
	default:
		return false
	}
}

// Capability constants for known device capabilities.
const (
	CapOnOff             = "on_off"
	CapBrightness        = "brightness"
	CapColorTemp         = "color_temp"
	CapColor             = "color"
	CapTemperature       = "temperature"
	CapHumidity          = "humidity"
	CapPressure          = "pressure"
	CapIlluminance       = "illuminance"
	CapBattery           = "battery"
	CapAction            = "action"
	CapEffect            = "effect"
	CapPower             = "power"
	CapVoltage           = "voltage"
	CapCurrent           = "current"
	CapEnergy            = "energy"
	CapTargetTemperature = "target_temperature"
	CapHvacMode          = "hvac_mode"
	CapFanMode           = "fan_mode"
	CapSwing             = "swing"
)

// Capability describes a single device capability with optional rich metadata
// extracted from the protocol adapter (e.g. zigbee2mqtt exposes).
type Capability struct {
	Name     string   `json:"name"`               // canonical name (e.g. "on_off", "brightness", "action")
	Type     string   `json:"type"`               // feature type: "binary", "numeric", "enum", "text", "composite"
	Values   []string `json:"values,omitempty"`   // for enum types (e.g. ["single","double","hold"])
	ValueMin *float64 `json:"valueMin,omitempty"` // for numeric types
	ValueMax *float64 `json:"valueMax,omitempty"` // for numeric types
	Unit     string   `json:"unit,omitempty"`     // for numeric types (e.g. "°C", "%", "lux")
	Access   int      `json:"access"`             // bitmask: 1=published, 2=get, 4=set
}

// Device is the protocol-agnostic representation of a home automation device.
type Device struct {
	ID           DeviceID     `json:"id"`
	Name         string       `json:"name"`
	Icon         *string      `json:"icon,omitempty"`
	Source       Source       `json:"source"`
	Type         DeviceType   `json:"type"`
	Tags         []DeviceTag  `json:"tags"`
	Capabilities []Capability `json:"capabilities"`
	Available    bool         `json:"available"`
	Removed      bool         `json:"removed"`
	// Disabled excludes the device from every path that commands or watches it
	// (scenes, automations, effects, staleness alarms) while keeping its row and
	// its detail page. For seasonal hardware that is unplugged but not gone.
	Disabled bool      `json:"disabled"`
	LastSeen time.Time `json:"lastSeen"`
}

// EnabledDevices returns the subset of devs that are neither removed nor
// disabled — the set that command fan-out, selector evaluation and health
// monitoring operate on. Display and history paths use the unfiltered list.
func EnabledDevices(devs []Device) []Device {
	out := make([]Device, 0, len(devs))
	for _, d := range devs {
		if d.Removed || d.Disabled {
			continue
		}
		out = append(out, d)
	}
	return out
}
