package device

import "time"

// DeviceID is a unique identifier for a device (UUID, generated by the system).
type DeviceID string

// Source identifies the protocol a device was discovered through.
type Source string

// DeviceType classifies a device by its primary function.
type DeviceType string

const (
	// Light represents a controllable light device.
	Light DeviceType = "light"
	// Sensor represents a device that reports environmental readings.
	Sensor DeviceType = "sensor"
	// Button represents an input device that reports discrete action events
	// (e.g. single / double / hold) without an on/off state of its own.
	Button DeviceType = "button"
	// Plug represents a switchable outlet, usually with on/off control and
	// often with power metering (power, voltage, current, energy).
	Plug DeviceType = "plug"
	// Speaker represents an audio output device.
	Speaker DeviceType = "speaker"
	// Unknown represents a device whose type could not be determined.
	Unknown DeviceType = "unknown"
)

// Capability constants for known device capabilities.
const (
	CapOnOff       = "on_off"
	CapBrightness  = "brightness"
	CapColorTemp   = "color_temp"
	CapColor       = "color"
	CapTemperature = "temperature"
	CapHumidity    = "humidity"
	CapPressure    = "pressure"
	CapIlluminance = "illuminance"
	CapBattery     = "battery"
	CapAction      = "action"
	CapEffect      = "effect"
	CapPower       = "power"
	CapVoltage     = "voltage"
	CapCurrent     = "current"
	CapEnergy      = "energy"
)

// Capability describes a single device capability with optional rich metadata
// extracted from the protocol adapter (e.g. zigbee2mqtt exposes).
type Capability struct {
	Name     string   `json:"name"`               // canonical name (e.g. "on_off", "brightness", "action")
	Type     string   `json:"type"`               // feature type: "binary", "numeric", "enum", "text", "composite"
	Values   []string `json:"values,omitempty"`   // for enum types (e.g. ["single","double","hold"])
	ValueMin *float64 `json:"valueMin,omitempty"` // for numeric types
	ValueMax *float64 `json:"valueMax,omitempty"` // for numeric types
	Unit     string   `json:"unit,omitempty"`     // for numeric types (e.g. "°C", "%", "lux")
	Access   int      `json:"access"`             // bitmask: 1=published, 2=get, 4=set
}

// Device is the protocol-agnostic representation of a home automation device.
type Device struct {
	ID           DeviceID     `json:"id"`
	Name         string       `json:"name"`
	Source       Source       `json:"source"`
	Type         DeviceType   `json:"type"`
	Capabilities []Capability `json:"capabilities"`
	Available    bool         `json:"available"`
	Removed      bool         `json:"removed"`
	LastSeen     time.Time    `json:"lastSeen"`
}
