apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saffron-hive-data
  namespace: home
  labels:
    app.kubernetes.io/name: saffron-hive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
