// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type DeviceState interface {
	IsDeviceState()
}

type SceneTarget interface {
	IsSceneTarget()
}

type AddGroupMemberInput struct {
	GroupID    string `json:"groupId"`
	MemberType string `json:"memberType"`
	MemberID   string `json:"memberId"`
}

type AddRoomDeviceInput struct {
	RoomID   string `json:"roomId"`
	DeviceID string `json:"deviceId"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type AutomationEdge struct {
	ID         string `json:"id"`
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationEdgeInput struct {
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationGraph struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	Icon            *string           `json:"icon,omitempty"`
	Enabled         bool              `json:"enabled"`
	CooldownSeconds int               `json:"cooldownSeconds"`
	Nodes           []*AutomationNode `json:"nodes"`
	Edges           []*AutomationEdge `json:"edges"`
	CreatedBy       *User             `json:"createdBy,omitempty"`
}

type AutomationNode struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

type AutomationNodeActivationEvent struct {
	AutomationID string `json:"automationId"`
	NodeID       string `json:"nodeId"`
	Active       bool   `json:"active"`
}

type AutomationNodeInput struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

type Capability struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Values   []string `json:"values,omitempty"`
	ValueMin *float64 `json:"valueMin,omitempty"`
	ValueMax *float64 `json:"valueMax,omitempty"`
	Unit     *string  `json:"unit,omitempty"`
	Access   int      `json:"access"`
}

type Color struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ColorInput struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ConnectionTestResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateAutomationInput struct {
	Name            string                 `json:"name"`
	Enabled         bool                   `json:"enabled"`
	CooldownSeconds int                    `json:"cooldownSeconds"`
	Nodes           []*AutomationNodeInput `json:"nodes"`
	Edges           []*AutomationEdgeInput `json:"edges"`
}

type CreateGroupInput struct {
	Name string `json:"name"`
}

type CreateInitialUserInput struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type CreateRoomInput struct {
	Name string `json:"name"`
}

type CreateSceneInput struct {
	Name    string              `json:"name"`
	Actions []*SceneActionInput `json:"actions"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Device struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Source       string        `json:"source"`
	Type         string        `json:"type"`
	Capabilities []*Capability `json:"capabilities"`
	Available    bool          `json:"available"`
	LastSeen     *time.Time    `json:"lastSeen,omitempty"`
	State        DeviceState   `json:"state,omitempty"`
}

func (Device) IsSceneTarget() {}

type DeviceAvailabilityEvent struct {
	DeviceID  string `json:"deviceId"`
	Available bool   `json:"available"`
}

type DeviceStateEvent struct {
	DeviceID string      `json:"deviceId"`
	State    DeviceState `json:"state"`
}

type Group struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Icon            *string        `json:"icon,omitempty"`
	Members         []*GroupMember `json:"members"`
	ResolvedDevices []*Device      `json:"resolvedDevices"`
	CreatedBy       *User          `json:"createdBy,omitempty"`
}

func (Group) IsSceneTarget() {}

type GroupMember struct {
	ID         string  `json:"id"`
	MemberType string  `json:"memberType"`
	MemberID   string  `json:"memberId"`
	Device     *Device `json:"device,omitempty"`
	Group      *Group  `json:"group,omitempty"`
	Room       *Room   `json:"room,omitempty"`
}

type LightState struct {
	On         *bool    `json:"on,omitempty"`
	Brightness *int     `json:"brightness,omitempty"`
	ColorTemp  *int     `json:"colorTemp,omitempty"`
	Color      *Color   `json:"color,omitempty"`
	Transition *float64 `json:"transition,omitempty"`
}

func (LightState) IsDeviceState() {}

type LightStateInput struct {
	On         graphql.Omittable[*bool]       `json:"on,omitempty"`
	Brightness graphql.Omittable[*int]        `json:"brightness,omitempty"`
	ColorTemp  graphql.Omittable[*int]        `json:"colorTemp,omitempty"`
	Color      graphql.Omittable[*ColorInput] `json:"color,omitempty"`
	Transition graphql.Omittable[*float64]    `json:"transition,omitempty"`
}

type LogEntry struct {
	Timestamp time.Time `json:"timestamp"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Attrs     string    `json:"attrs"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MqttConfig struct {
	Broker   string `json:"broker"`
	Username string `json:"username"`
	Password string `json:"password"`
	UseWss   bool   `json:"useWss"`
}

type MqttConfigInput struct {
	Broker   string `json:"broker"`
	Username string `json:"username"`
	Password string `json:"password"`
	UseWss   bool   `json:"useWss"`
}

type Mutation struct {
}

type Query struct {
}

type Room struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Icon      *string   `json:"icon,omitempty"`
	Devices   []*Device `json:"devices"`
	CreatedBy *User     `json:"createdBy,omitempty"`
}

func (Room) IsSceneTarget() {}

type Scene struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Icon      *string        `json:"icon,omitempty"`
	Actions   []*SceneAction `json:"actions"`
	CreatedBy *User          `json:"createdBy,omitempty"`
}

type SceneAction struct {
	ID         string      `json:"id"`
	TargetType string      `json:"targetType"`
	TargetID   string      `json:"targetId"`
	Target     SceneTarget `json:"target"`
	Payload    string      `json:"payload"`
}

type SceneActionInput struct {
	TargetType string `json:"targetType"`
	TargetID   string `json:"targetId"`
	Payload    string `json:"payload"`
}

type SensorReading struct {
	ID          string    `json:"id"`
	DeviceID    string    `json:"deviceId"`
	Temperature *float64  `json:"temperature,omitempty"`
	Humidity    *float64  `json:"humidity,omitempty"`
	Battery     *int      `json:"battery,omitempty"`
	Pressure    *float64  `json:"pressure,omitempty"`
	Illuminance *float64  `json:"illuminance,omitempty"`
	RecordedAt  time.Time `json:"recordedAt"`
}

type SensorState struct {
	Temperature *float64 `json:"temperature,omitempty"`
	Humidity    *float64 `json:"humidity,omitempty"`
	Battery     *int     `json:"battery,omitempty"`
	Pressure    *float64 `json:"pressure,omitempty"`
	Illuminance *float64 `json:"illuminance,omitempty"`
}

func (SensorState) IsDeviceState() {}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SetupStatus struct {
	HasInitialUser bool `json:"hasInitialUser"`
	MqttConfigured bool `json:"mqttConfigured"`
}

type Subscription struct {
}

type SwitchState struct {
	Action *string `json:"action,omitempty"`
}

func (SwitchState) IsDeviceState() {}

type UpdateAutomationInput struct {
	Name            graphql.Omittable[*string]                `json:"name,omitempty"`
	Icon            graphql.Omittable[*string]                `json:"icon,omitempty"`
	Enabled         graphql.Omittable[*bool]                  `json:"enabled,omitempty"`
	CooldownSeconds graphql.Omittable[*int]                   `json:"cooldownSeconds,omitempty"`
	Nodes           graphql.Omittable[[]*AutomationNodeInput] `json:"nodes,omitempty"`
	Edges           graphql.Omittable[[]*AutomationEdgeInput] `json:"edges,omitempty"`
}

type UpdateDeviceInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
}

type UpdateGroupInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
	Icon graphql.Omittable[*string] `json:"icon,omitempty"`
}

type UpdateRoomInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
	Icon graphql.Omittable[*string] `json:"icon,omitempty"`
}

type UpdateSceneInput struct {
	Name    graphql.Omittable[*string]             `json:"name,omitempty"`
	Icon    graphql.Omittable[*string]             `json:"icon,omitempty"`
	Actions graphql.Omittable[[]*SceneActionInput] `json:"actions,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
}
