// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DeviceState interface {
	IsDeviceState()
}

type SceneTarget interface {
	IsSceneTarget()
}

type AddGroupMemberInput struct {
	GroupID    string `json:"groupId"`
	MemberType string `json:"memberType"`
	MemberID   string `json:"memberId"`
}

type AutomationEdge struct {
	ID         string `json:"id"`
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationEdgeInput struct {
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationGraph struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	Enabled         bool              `json:"enabled"`
	CooldownSeconds int               `json:"cooldownSeconds"`
	Nodes           []*AutomationNode `json:"nodes"`
	Edges           []*AutomationEdge `json:"edges"`
}

type AutomationNode struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

type AutomationNodeActivationEvent struct {
	AutomationID string `json:"automationId"`
	NodeID       string `json:"nodeId"`
	Active       bool   `json:"active"`
}

type AutomationNodeInput struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

type Color struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ColorInput struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type CreateAutomationInput struct {
	Name            string                 `json:"name"`
	Enabled         bool                   `json:"enabled"`
	CooldownSeconds int                    `json:"cooldownSeconds"`
	Nodes           []*AutomationNodeInput `json:"nodes"`
	Edges           []*AutomationEdgeInput `json:"edges"`
}

type CreateGroupInput struct {
	Name string `json:"name"`
}

type CreateSceneInput struct {
	Name    string              `json:"name"`
	Actions []*SceneActionInput `json:"actions"`
}

type Device struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Source    string      `json:"source"`
	Type      string      `json:"type"`
	Available bool        `json:"available"`
	LastSeen  *time.Time  `json:"lastSeen,omitempty"`
	State     DeviceState `json:"state,omitempty"`
}

func (Device) IsSceneTarget() {}

type DeviceAvailabilityEvent struct {
	DeviceID  string `json:"deviceId"`
	Available bool   `json:"available"`
}

type DeviceStateEvent struct {
	DeviceID string      `json:"deviceId"`
	State    DeviceState `json:"state"`
}

type Group struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Members         []*GroupMember `json:"members"`
	ResolvedDevices []*Device      `json:"resolvedDevices"`
}

func (Group) IsSceneTarget() {}

type GroupMember struct {
	ID         string  `json:"id"`
	MemberType string  `json:"memberType"`
	MemberID   string  `json:"memberId"`
	Device     *Device `json:"device,omitempty"`
	Group      *Group  `json:"group,omitempty"`
}

type LightState struct {
	On         *bool    `json:"on,omitempty"`
	Brightness *int     `json:"brightness,omitempty"`
	ColorTemp  *int     `json:"colorTemp,omitempty"`
	Color      *Color   `json:"color,omitempty"`
	Transition *float64 `json:"transition,omitempty"`
}

func (LightState) IsDeviceState() {}

type LightStateInput struct {
	On         *bool       `json:"on,omitempty"`
	Brightness *int        `json:"brightness,omitempty"`
	ColorTemp  *int        `json:"colorTemp,omitempty"`
	Color      *ColorInput `json:"color,omitempty"`
	Transition *float64    `json:"transition,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Scene struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Actions []*SceneAction `json:"actions"`
}

type SceneAction struct {
	ID         string      `json:"id"`
	TargetType string      `json:"targetType"`
	TargetID   string      `json:"targetId"`
	Target     SceneTarget `json:"target"`
	Payload    string      `json:"payload"`
}

type SceneActionInput struct {
	TargetType string `json:"targetType"`
	TargetID   string `json:"targetId"`
	Payload    string `json:"payload"`
}

type SensorReading struct {
	ID          string    `json:"id"`
	DeviceID    string    `json:"deviceId"`
	Temperature *float64  `json:"temperature,omitempty"`
	Humidity    *float64  `json:"humidity,omitempty"`
	Battery     *int      `json:"battery,omitempty"`
	Pressure    *float64  `json:"pressure,omitempty"`
	Illuminance *float64  `json:"illuminance,omitempty"`
	RecordedAt  time.Time `json:"recordedAt"`
}

type SensorState struct {
	Temperature *float64 `json:"temperature,omitempty"`
	Humidity    *float64 `json:"humidity,omitempty"`
	Battery     *int     `json:"battery,omitempty"`
	Pressure    *float64 `json:"pressure,omitempty"`
	Illuminance *float64 `json:"illuminance,omitempty"`
}

func (SensorState) IsDeviceState() {}

type Subscription struct {
}

type SwitchState struct {
	Action *string `json:"action,omitempty"`
}

func (SwitchState) IsDeviceState() {}

type UpdateAutomationInput struct {
	Name            *string                `json:"name,omitempty"`
	Enabled         *bool                  `json:"enabled,omitempty"`
	CooldownSeconds *int                   `json:"cooldownSeconds,omitempty"`
	Nodes           []*AutomationNodeInput `json:"nodes,omitempty"`
	Edges           []*AutomationEdgeInput `json:"edges,omitempty"`
}

type UpdateDeviceInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateGroupInput struct {
	Name *string `json:"name,omitempty"`
}

type UpdateSceneInput struct {
	Name    *string             `json:"name,omitempty"`
	Actions []*SceneActionInput `json:"actions,omitempty"`
}
