// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type SceneTarget interface {
	IsSceneTarget()
}

// One row marking that an effect is currently running on a target. volatile
// mirrors the persistence flag — non-loop timeline runs and native runs are
// volatile (wiped at process startup); loop timeline runs survive a restart.
type ActiveEffect struct {
	ID         string    `json:"id"`
	Effect     *Effect   `json:"effect"`
	TargetType string    `json:"targetType"`
	TargetID   string    `json:"targetId"`
	StartedAt  time.Time `json:"startedAt"`
	Volatile   bool      `json:"volatile"`
}

type ActivityEvent struct {
	ID        string          `json:"id"`
	Type      string          `json:"type"`
	Timestamp time.Time       `json:"timestamp"`
	Message   string          `json:"message"`
	Payload   string          `json:"payload"`
	Source    *ActivitySource `json:"source"`
}

type ActivityFilter struct {
	Types    graphql.Omittable[[]string]   `json:"types,omitempty"`
	DeviceID graphql.Omittable[*string]    `json:"deviceId,omitempty"`
	RoomID   graphql.Omittable[*string]    `json:"roomId,omitempty"`
	Since    graphql.Omittable[*time.Time] `json:"since,omitempty"`
	Advanced graphql.Omittable[*bool]      `json:"advanced,omitempty"`
	Limit    graphql.Omittable[*int]       `json:"limit,omitempty"`
	Before   graphql.Omittable[*string]    `json:"before,omitempty"`
}

type ActivitySource struct {
	Kind     string  `json:"kind"`
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Type     *string `json:"type,omitempty"`
	RoomID   *string `json:"roomId,omitempty"`
	RoomName *string `json:"roomName,omitempty"`
}

type AddGroupMemberInput struct {
	GroupID    string `json:"groupId"`
	MemberType string `json:"memberType"`
	MemberID   string `json:"memberId"`
}

type AddRoomMemberInput struct {
	RoomID     string `json:"roomId"`
	MemberType string `json:"memberType"`
	MemberID   string `json:"memberId"`
}

// An alarm is an actionable severity-tagged signal. Rows are persisted 1:1 per
// raise; this type is the grouped projection — multiple raises sharing the same
// id collapse into one Alarm whose message/severity/kind come from the latest
// raise and whose count reflects the group size.
type Alarm struct {
	ID            string        `json:"id"`
	LatestRowID   string        `json:"latestRowId"`
	Severity      AlarmSeverity `json:"severity"`
	Kind          AlarmKind     `json:"kind"`
	Message       string        `json:"message"`
	Source        string        `json:"source"`
	Count         int           `json:"count"`
	FirstRaisedAt time.Time     `json:"firstRaisedAt"`
	LastRaisedAt  time.Time     `json:"lastRaisedAt"`
}

type AlarmEvent struct {
	Kind           AlarmEventKind `json:"kind"`
	Alarm          *Alarm         `json:"alarm,omitempty"`
	ClearedAlarmID *string        `json:"clearedAlarmId,omitempty"`
}

type AlarmFilter struct {
	Severities graphql.Omittable[[]AlarmSeverity] `json:"severities,omitempty"`
	Kinds      graphql.Omittable[[]AlarmKind]     `json:"kinds,omitempty"`
	Sources    graphql.Omittable[[]string]        `json:"sources,omitempty"`
	Since      graphql.Omittable[*time.Time]      `json:"since,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type AutomationEdge struct {
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationEdgeInput struct {
	FromNodeID string `json:"fromNodeId"`
	ToNodeID   string `json:"toNodeId"`
}

type AutomationGraph struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Icon        *string           `json:"icon,omitempty"`
	Enabled     bool              `json:"enabled"`
	LastFiredAt *time.Time        `json:"lastFiredAt,omitempty"`
	Nodes       []*AutomationNode `json:"nodes"`
	Edges       []*AutomationEdge `json:"edges"`
	CreatedBy   *User             `json:"createdBy,omitempty"`
}

type AutomationNode struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Config    string  `json:"config"`
	PositionX float64 `json:"positionX"`
	PositionY float64 `json:"positionY"`
}

type AutomationNodeActivationEvent struct {
	AutomationID string `json:"automationId"`
	NodeID       string `json:"nodeId"`
	Active       bool   `json:"active"`
}

type AutomationNodeInput struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Config    string  `json:"config"`
	PositionX float64 `json:"positionX"`
	PositionY float64 `json:"positionY"`
}

type Capability struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Values   []string `json:"values,omitempty"`
	ValueMin *float64 `json:"valueMin,omitempty"`
	ValueMax *float64 `json:"valueMax,omitempty"`
	Unit     *string  `json:"unit,omitempty"`
	Access   int      `json:"access"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type Color struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ColorInput struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type ConnectionTestResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateAutomationInput struct {
	Name    string                 `json:"name"`
	Enabled bool                   `json:"enabled"`
	Nodes   []*AutomationNodeInput `json:"nodes"`
	Edges   []*AutomationEdgeInput `json:"edges"`
}

type CreateEffectInput struct {
	Name       string                     `json:"name"`
	Icon       graphql.Omittable[*string] `json:"icon,omitempty"`
	Kind       EffectKind                 `json:"kind"`
	NativeName graphql.Omittable[*string] `json:"nativeName,omitempty"`
	Loop       bool                       `json:"loop"`
	Steps      []*EffectStepInput         `json:"steps"`
}

type CreateGroupInput struct {
	Name string `json:"name"`
}

type CreateInitialUserInput struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type CreateRoomInput struct {
	Name string `json:"name"`
}

type CreateSceneInput struct {
	Name           string                                        `json:"name"`
	Actions        []*SceneActionInput                           `json:"actions"`
	DevicePayloads graphql.Omittable[[]*SceneDevicePayloadInput] `json:"devicePayloads,omitempty"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Device struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Source       string        `json:"source"`
	Type         string        `json:"type"`
	Capabilities []*Capability `json:"capabilities"`
	Available    bool          `json:"available"`
	LastSeen     *time.Time    `json:"lastSeen,omitempty"`
	State        *DeviceState  `json:"state,omitempty"`
}

func (Device) IsSceneTarget() {}

type DeviceActionEvent struct {
	DeviceID string    `json:"deviceId"`
	Action   string    `json:"action"`
	FiredAt  time.Time `json:"firedAt"`
}

type DeviceAvailabilityEvent struct {
	DeviceID  string `json:"deviceId"`
	Available bool   `json:"available"`
}

// Current state of a device across every capability it reports. Every field is
// nullable — null means the device has not reported (or does not report) that
// value. Clients typically branch on Device.type to decide which fields to
// display, but any field may be present on any device.
type DeviceState struct {
	On          *bool    `json:"on,omitempty"`
	Brightness  *int     `json:"brightness,omitempty"`
	ColorTemp   *int     `json:"colorTemp,omitempty"`
	Color       *Color   `json:"color,omitempty"`
	Transition  *float64 `json:"transition,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	Humidity    *float64 `json:"humidity,omitempty"`
	Pressure    *float64 `json:"pressure,omitempty"`
	Illuminance *float64 `json:"illuminance,omitempty"`
	Battery     *int     `json:"battery,omitempty"`
	Power       *float64 `json:"power,omitempty"`
	Voltage     *float64 `json:"voltage,omitempty"`
	Current     *float64 `json:"current,omitempty"`
	Energy      *float64 `json:"energy,omitempty"`
}

type DeviceStateEvent struct {
	DeviceID string       `json:"deviceId"`
	State    *DeviceState `json:"state"`
}

type DeviceStateInput struct {
	On         graphql.Omittable[*bool]       `json:"on,omitempty"`
	Brightness graphql.Omittable[*int]        `json:"brightness,omitempty"`
	ColorTemp  graphql.Omittable[*int]        `json:"colorTemp,omitempty"`
	Color      graphql.Omittable[*ColorInput] `json:"color,omitempty"`
	Transition graphql.Omittable[*float64]    `json:"transition,omitempty"`
}

type Effect struct {
	ID         string        `json:"id"`
	Name       string        `json:"name"`
	Icon       *string       `json:"icon,omitempty"`
	Kind       EffectKind    `json:"kind"`
	NativeName *string       `json:"nativeName,omitempty"`
	Loop       bool          `json:"loop"`
	Steps      []*EffectStep `json:"steps"`
	// Capabilities every target device must support for this effect to apply
	// cleanly. Derived from the effect's step kinds for timeline effects;
	// empty for native effects (the per-device native option list owns that
	// filtering).
	RequiredCapabilities []string  `json:"requiredCapabilities"`
	CreatedBy            *User     `json:"createdBy,omitempty"`
	CreatedAt            time.Time `json:"createdAt"`
	UpdatedAt            time.Time `json:"updatedAt"`
}

// A single step inside a timeline effect. config is a JSON document whose
// shape is determined by kind — the disk shape directly, not wrapped, e.g.
// {"r":244,"g":42,"b":23,"transition_ms":200} for SET_COLOR_RGB.
type EffectStep struct {
	ID     string         `json:"id"`
	Index  int            `json:"index"`
	Kind   EffectStepKind `json:"kind"`
	Config string         `json:"config"`
}

// Step boundary marker emitted by the runner. active=true on enter,
// active=false on exit. runId identifies the in-flight run instance.
type EffectStepEvent struct {
	RunID     string `json:"runId"`
	EffectID  string `json:"effectId"`
	StepIndex int    `json:"stepIndex"`
	Active    bool   `json:"active"`
}

type EffectStepInput struct {
	Kind   EffectStepKind `json:"kind"`
	Config string         `json:"config"`
}

type Group struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Icon            *string        `json:"icon,omitempty"`
	Members         []*GroupMember `json:"members"`
	ResolvedDevices []*Device      `json:"resolvedDevices"`
	CreatedBy       *User          `json:"createdBy,omitempty"`
}

func (Group) IsSceneTarget() {}

type GroupMember struct {
	ID         string  `json:"id"`
	MemberType string  `json:"memberType"`
	MemberID   string  `json:"memberId"`
	Device     *Device `json:"device,omitempty"`
	Group      *Group  `json:"group,omitempty"`
	Room       *Room   `json:"room,omitempty"`
}

type LogEntry struct {
	Timestamp time.Time `json:"timestamp"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Attrs     string    `json:"attrs"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MqttConfig struct {
	Broker   string `json:"broker"`
	Username string `json:"username"`
	Password string `json:"password"`
	UseWss   bool   `json:"useWss"`
}

type MqttConfigInput struct {
	Broker   string `json:"broker"`
	Username string `json:"username"`
	Password string `json:"password"`
	UseWss   bool   `json:"useWss"`
}

type Mutation struct {
}

// A native effect option as offered by the editor. supportedDeviceCount is
// the number of currently-known devices whose effect capability advertises
// this value.
type NativeEffectOption struct {
	Name                 string `json:"name"`
	DisplayName          string `json:"displayName"`
	SupportedDeviceCount int    `json:"supportedDeviceCount"`
}

type Query struct {
}

type RaiseAlarmInput struct {
	AlarmID  string                     `json:"alarmId"`
	Severity AlarmSeverity              `json:"severity"`
	Kind     AlarmKind                  `json:"kind"`
	Message  string                     `json:"message"`
	Source   graphql.Omittable[*string] `json:"source,omitempty"`
}

type Room struct {
	ID              string        `json:"id"`
	Name            string        `json:"name"`
	Icon            *string       `json:"icon,omitempty"`
	Members         []*RoomMember `json:"members"`
	ResolvedDevices []*Device     `json:"resolvedDevices"`
	CreatedBy       *User         `json:"createdBy,omitempty"`
}

func (Room) IsSceneTarget() {}

type RoomMember struct {
	ID         string  `json:"id"`
	MemberType string  `json:"memberType"`
	MemberID   string  `json:"memberId"`
	Device     *Device `json:"device,omitempty"`
	Group      *Group  `json:"group,omitempty"`
}

type RoomMemberInput struct {
	MemberType string `json:"memberType"`
	MemberID   string `json:"memberId"`
}

type Scene struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Icon    *string        `json:"icon,omitempty"`
	Actions []*SceneAction `json:"actions"`
	// Per-device payload overrides the user has saved explicitly. Devices that
	// inherit their room/group default do NOT appear here. Use this for the
	// scene editor's override rows; use effectivePayloads for display tint.
	DevicePayloads []*SceneDevicePayload `json:"devicePayloads"`
	// One payload per unique device reached by the scene's action targets
	// (rooms, groups, or direct devices), in the same order apply-scene would
	// command them. Devices without an explicit override appear with a
	// capability-filtered default (warm-white on), so consumers can tint cards,
	// preview apply behaviour, etc. without re-implementing the resolution.
	EffectivePayloads []*SceneDevicePayload `json:"effectivePayloads"`
	CreatedBy         *User                 `json:"createdBy,omitempty"`
	// Non-null while this scene is currently the state of its devices: every
	// device the scene reached at apply time is still in the scene-relevant
	// state the scene asked for. Any change to a scene-relevant field (on,
	// brightness, colorTemp, color) on any of those devices clears this back
	// to null. Use the presence of a value as "is this scene active right now".
	ActivatedAt *time.Time `json:"activatedAt,omitempty"`
}

type SceneAction struct {
	TargetType string      `json:"targetType"`
	TargetID   string      `json:"targetId"`
	Target     SceneTarget `json:"target"`
}

type SceneActionInput struct {
	TargetType string `json:"targetType"`
	TargetID   string `json:"targetId"`
}

// Emitted whenever a scene's activation state flips. activatedAt is non-null
// when the scene just became active, null when it was deactivated by a
// device-state change.
type SceneActiveEvent struct {
	SceneID     string     `json:"sceneId"`
	ActivatedAt *time.Time `json:"activatedAt,omitempty"`
}

type SceneDevicePayload struct {
	DeviceID string `json:"deviceId"`
	Payload  string `json:"payload"`
}

type SceneDevicePayloadInput struct {
	DeviceID string `json:"deviceId"`
	Payload  string `json:"payload"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SetupStatus struct {
	HasInitialUser bool `json:"hasInitialUser"`
	MqttConfigured bool `json:"mqttConfigured"`
}

type StateHistoryFilter struct {
	DeviceIds     []string                      `json:"deviceIds"`
	Fields        graphql.Omittable[[]string]   `json:"fields,omitempty"`
	From          graphql.Omittable[*time.Time] `json:"from,omitempty"`
	To            graphql.Omittable[*time.Time] `json:"to,omitempty"`
	BucketSeconds graphql.Omittable[*int]       `json:"bucketSeconds,omitempty"`
}

type StateSeries struct {
	DeviceID string              `json:"deviceId"`
	Field    string              `json:"field"`
	Points   []*StateSeriesPoint `json:"points"`
}

type StateSeriesPoint struct {
	At    time.Time `json:"at"`
	Value float64   `json:"value"`
}

type Subscription struct {
}

type UpdateAutomationInput struct {
	Name    graphql.Omittable[*string]                `json:"name,omitempty"`
	Icon    graphql.Omittable[*string]                `json:"icon,omitempty"`
	Enabled graphql.Omittable[*bool]                  `json:"enabled,omitempty"`
	Nodes   graphql.Omittable[[]*AutomationNodeInput] `json:"nodes,omitempty"`
	Edges   graphql.Omittable[[]*AutomationEdgeInput] `json:"edges,omitempty"`
}

type UpdateCurrentUserInput struct {
	Name  graphql.Omittable[*string] `json:"name,omitempty"`
	Theme graphql.Omittable[*Theme]  `json:"theme,omitempty"`
}

type UpdateDeviceInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
}

type UpdateEffectInput struct {
	ID         string                                `json:"id"`
	Name       graphql.Omittable[*string]            `json:"name,omitempty"`
	Icon       graphql.Omittable[*string]            `json:"icon,omitempty"`
	Loop       graphql.Omittable[*bool]              `json:"loop,omitempty"`
	NativeName graphql.Omittable[*string]            `json:"nativeName,omitempty"`
	Steps      graphql.Omittable[[]*EffectStepInput] `json:"steps,omitempty"`
}

type UpdateGroupInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
	Icon graphql.Omittable[*string] `json:"icon,omitempty"`
}

type UpdateRoomInput struct {
	Name graphql.Omittable[*string] `json:"name,omitempty"`
	Icon graphql.Omittable[*string] `json:"icon,omitempty"`
}

type UpdateSceneInput struct {
	Name           graphql.Omittable[*string]                    `json:"name,omitempty"`
	Icon           graphql.Omittable[*string]                    `json:"icon,omitempty"`
	Actions        graphql.Omittable[[]*SceneActionInput]        `json:"actions,omitempty"`
	DevicePayloads graphql.Omittable[[]*SceneDevicePayloadInput] `json:"devicePayloads,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
	// Avatar filename on the server, relative to the avatars endpoint. Null when
	// no avatar has been uploaded; clients fall back to rendered initials. Resolve
	// to a URL by prefixing with `/avatars/`.
	AvatarPath *string `json:"avatarPath,omitempty"`
	// UI theme preference stored per user. Present on full user loads (`me`,
	// `users`). Null on attribution references (e.g. `scene.createdBy`), which
	// only populate `id`, `username`, and `name`.
	Theme *Theme `json:"theme,omitempty"`
	// Timestamp the user was created; used on the profile page as "member since".
	// Present on full user loads, null on attribution references.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

type AlarmEventKind string

const (
	AlarmEventKindRaised  AlarmEventKind = "RAISED"
	AlarmEventKindCleared AlarmEventKind = "CLEARED"
)

var AllAlarmEventKind = []AlarmEventKind{
	AlarmEventKindRaised,
	AlarmEventKindCleared,
}

func (e AlarmEventKind) IsValid() bool {
	switch e {
	case AlarmEventKindRaised, AlarmEventKindCleared:
		return true
	}
	return false
}

func (e AlarmEventKind) String() string {
	return string(e)
}

func (e *AlarmEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlarmEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlarmEventKind", str)
	}
	return nil
}

func (e AlarmEventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlarmEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlarmEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlarmKind string

const (
	AlarmKindAuto    AlarmKind = "AUTO"
	AlarmKindOneShot AlarmKind = "ONE_SHOT"
)

var AllAlarmKind = []AlarmKind{
	AlarmKindAuto,
	AlarmKindOneShot,
}

func (e AlarmKind) IsValid() bool {
	switch e {
	case AlarmKindAuto, AlarmKindOneShot:
		return true
	}
	return false
}

func (e AlarmKind) String() string {
	return string(e)
}

func (e *AlarmKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlarmKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlarmKind", str)
	}
	return nil
}

func (e AlarmKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlarmKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlarmKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlarmSeverity string

const (
	AlarmSeverityHigh   AlarmSeverity = "HIGH"
	AlarmSeverityMedium AlarmSeverity = "MEDIUM"
	AlarmSeverityLow    AlarmSeverity = "LOW"
)

var AllAlarmSeverity = []AlarmSeverity{
	AlarmSeverityHigh,
	AlarmSeverityMedium,
	AlarmSeverityLow,
}

func (e AlarmSeverity) IsValid() bool {
	switch e {
	case AlarmSeverityHigh, AlarmSeverityMedium, AlarmSeverityLow:
		return true
	}
	return false
}

func (e AlarmSeverity) String() string {
	return string(e)
}

func (e *AlarmSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlarmSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlarmSeverity", str)
	}
	return nil
}

func (e AlarmSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlarmSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlarmSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EffectKind string

const (
	EffectKindTimeline EffectKind = "TIMELINE"
	EffectKindNative   EffectKind = "NATIVE"
)

var AllEffectKind = []EffectKind{
	EffectKindTimeline,
	EffectKindNative,
}

func (e EffectKind) IsValid() bool {
	switch e {
	case EffectKindTimeline, EffectKindNative:
		return true
	}
	return false
}

func (e EffectKind) String() string {
	return string(e)
}

func (e *EffectKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EffectKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EffectKind", str)
	}
	return nil
}

func (e EffectKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EffectKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EffectKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EffectStepKind string

const (
	EffectStepKindWait          EffectStepKind = "WAIT"
	EffectStepKindSetOnOff      EffectStepKind = "SET_ON_OFF"
	EffectStepKindSetBrightness EffectStepKind = "SET_BRIGHTNESS"
	EffectStepKindSetColorRgb   EffectStepKind = "SET_COLOR_RGB"
	EffectStepKindSetColorTemp  EffectStepKind = "SET_COLOR_TEMP"
)

var AllEffectStepKind = []EffectStepKind{
	EffectStepKindWait,
	EffectStepKindSetOnOff,
	EffectStepKindSetBrightness,
	EffectStepKindSetColorRgb,
	EffectStepKindSetColorTemp,
}

func (e EffectStepKind) IsValid() bool {
	switch e {
	case EffectStepKindWait, EffectStepKindSetOnOff, EffectStepKindSetBrightness, EffectStepKindSetColorRgb, EffectStepKindSetColorTemp:
		return true
	}
	return false
}

func (e EffectStepKind) String() string {
	return string(e)
}

func (e *EffectStepKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EffectStepKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EffectStepKind", str)
	}
	return nil
}

func (e EffectStepKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EffectStepKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EffectStepKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Theme string

const (
	ThemeLight Theme = "LIGHT"
	ThemeDark  Theme = "DARK"
)

var AllTheme = []Theme{
	ThemeLight,
	ThemeDark,
}

func (e Theme) IsValid() bool {
	switch e {
	case ThemeLight, ThemeDark:
		return true
	}
	return false
}

func (e Theme) String() string {
	return string(e)
}

func (e *Theme) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Theme(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Theme", str)
	}
	return nil
}

func (e Theme) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Theme) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Theme) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
