ALTER TABLE scenes      ADD COLUMN created_by TEXT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE automations ADD COLUMN created_by TEXT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE groups      ADD COLUMN created_by TEXT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE rooms       ADD COLUMN created_by TEXT REFERENCES users(id) ON DELETE SET NULL;
