DROP TRIGGER IF EXISTS localized_subject_floorplan_room_delete;
DROP TRIGGER IF EXISTS localized_subject_floorplan_delete;
DROP TRIGGER IF EXISTS localized_subject_effect_track_delete;
DROP TRIGGER IF EXISTS localized_subject_effect_delete;
DROP TRIGGER IF EXISTS localized_subject_webhook_delete;
DROP TRIGGER IF EXISTS localized_subject_automation_delete;
DROP TRIGGER IF EXISTS localized_subject_scene_delete;
DROP TRIGGER IF EXISTS localized_subject_room_delete;
DROP TRIGGER IF EXISTS localized_subject_group_delete;
DROP TRIGGER IF EXISTS localized_subject_device_delete;
DROP TRIGGER IF EXISTS localized_subject_floorplan_room_insert;
DROP TRIGGER IF EXISTS localized_subject_floorplan_insert;
DROP TRIGGER IF EXISTS localized_subject_effect_track_insert;
DROP TRIGGER IF EXISTS localized_subject_effect_insert;
DROP TRIGGER IF EXISTS localized_subject_webhook_insert;
DROP TRIGGER IF EXISTS localized_subject_automation_insert;
DROP TRIGGER IF EXISTS localized_subject_scene_insert;
DROP TRIGGER IF EXISTS localized_subject_room_insert;
DROP TRIGGER IF EXISTS localized_subject_group_insert;
DROP TRIGGER IF EXISTS localized_subject_device_insert;
DROP TRIGGER IF EXISTS localized_names_reject_source_language;
DROP TABLE localized_names;
DROP TABLE localized_name_subjects;
DELETE FROM settings WHERE key = 'i18n.default_content_language';
