// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: active_scene_runs.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const deleteActiveSceneMembers = `-- name: DeleteActiveSceneMembers :exec
DELETE FROM active_scene_members WHERE scene_id = ?
`

func (q *Queries) DeleteActiveSceneMembers(ctx context.Context, sceneID string) error {
	_, err := q.db.ExecContext(ctx, deleteActiveSceneMembers, sceneID)
	return err
}

const deleteActiveSceneRun = `-- name: DeleteActiveSceneRun :execrows
DELETE FROM active_scene_runs WHERE scene_id = ?
`

func (q *Queries) DeleteActiveSceneRun(ctx context.Context, sceneID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteActiveSceneRun, sceneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveSceneRun = `-- name: GetActiveSceneRun :one
SELECT scene_id, run_id, started_at, definition_updated_at
FROM active_scene_runs WHERE scene_id = ?
`

func (q *Queries) GetActiveSceneRun(ctx context.Context, sceneID string) (ActiveSceneRun, error) {
	row := q.db.QueryRowContext(ctx, getActiveSceneRun, sceneID)
	var i ActiveSceneRun
	err := row.Scan(
		&i.SceneID,
		&i.RunID,
		&i.StartedAt,
		&i.DefinitionUpdatedAt,
	)
	return i, err
}

const insertActiveSceneMember = `-- name: InsertActiveSceneMember :exec
INSERT INTO active_scene_members (
    scene_id, device_id, behavior_kind,
    owns_on, owns_brightness, owns_color_temp, owns_color,
    owns_temperature, owns_hvac_mode, owns_fan_mode, owns_swing,
    expected_on, expected_brightness, expected_color_temp,
    expected_color_r, expected_color_g, expected_color_b,
    expected_color_x, expected_color_y,
    expected_temperature, expected_hvac_mode, expected_fan_mode, expected_swing,
    effect_run_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertActiveSceneMemberParams struct {
	SceneID             string
	DeviceID            device.DeviceID
	BehaviorKind        string
	OwnsOn              int64
	OwnsBrightness      int64
	OwnsColorTemp       int64
	OwnsColor           int64
	OwnsTemperature     int64
	OwnsHvacMode        int64
	OwnsFanMode         int64
	OwnsSwing           int64
	ExpectedOn          *int64
	ExpectedBrightness  *int64
	ExpectedColorTemp   *int64
	ExpectedColorR      *int64
	ExpectedColorG      *int64
	ExpectedColorB      *int64
	ExpectedColorX      *float64
	ExpectedColorY      *float64
	ExpectedTemperature *float64
	ExpectedHvacMode    *string
	ExpectedFanMode     *string
	ExpectedSwing       *string
	EffectRunID         *string
}

func (q *Queries) InsertActiveSceneMember(ctx context.Context, arg InsertActiveSceneMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertActiveSceneMember,
		arg.SceneID,
		arg.DeviceID,
		arg.BehaviorKind,
		arg.OwnsOn,
		arg.OwnsBrightness,
		arg.OwnsColorTemp,
		arg.OwnsColor,
		arg.OwnsTemperature,
		arg.OwnsHvacMode,
		arg.OwnsFanMode,
		arg.OwnsSwing,
		arg.ExpectedOn,
		arg.ExpectedBrightness,
		arg.ExpectedColorTemp,
		arg.ExpectedColorR,
		arg.ExpectedColorG,
		arg.ExpectedColorB,
		arg.ExpectedColorX,
		arg.ExpectedColorY,
		arg.ExpectedTemperature,
		arg.ExpectedHvacMode,
		arg.ExpectedFanMode,
		arg.ExpectedSwing,
		arg.EffectRunID,
	)
	return err
}

const listActiveSceneMembers = `-- name: ListActiveSceneMembers :many
SELECT scene_id, device_id, behavior_kind, owns_on, owns_brightness, owns_color_temp, owns_color, owns_temperature, owns_hvac_mode, owns_fan_mode, owns_swing, expected_on, expected_brightness, expected_color_temp, expected_color_r, expected_color_g, expected_color_b, expected_color_x, expected_color_y, expected_temperature, expected_hvac_mode, expected_fan_mode, expected_swing, effect_run_id FROM active_scene_members ORDER BY scene_id, device_id
`

func (q *Queries) ListActiveSceneMembers(ctx context.Context) ([]ActiveSceneMember, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSceneMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveSceneMember
	for rows.Next() {
		var i ActiveSceneMember
		if err := rows.Scan(
			&i.SceneID,
			&i.DeviceID,
			&i.BehaviorKind,
			&i.OwnsOn,
			&i.OwnsBrightness,
			&i.OwnsColorTemp,
			&i.OwnsColor,
			&i.OwnsTemperature,
			&i.OwnsHvacMode,
			&i.OwnsFanMode,
			&i.OwnsSwing,
			&i.ExpectedOn,
			&i.ExpectedBrightness,
			&i.ExpectedColorTemp,
			&i.ExpectedColorR,
			&i.ExpectedColorG,
			&i.ExpectedColorB,
			&i.ExpectedColorX,
			&i.ExpectedColorY,
			&i.ExpectedTemperature,
			&i.ExpectedHvacMode,
			&i.ExpectedFanMode,
			&i.ExpectedSwing,
			&i.EffectRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSceneRuns = `-- name: ListActiveSceneRuns :many
SELECT scene_id, run_id, started_at, definition_updated_at
FROM active_scene_runs
ORDER BY started_at, scene_id
`

func (q *Queries) ListActiveSceneRuns(ctx context.Context) ([]ActiveSceneRun, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSceneRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveSceneRun
	for rows.Next() {
		var i ActiveSceneRun
		if err := rows.Scan(
			&i.SceneID,
			&i.RunID,
			&i.StartedAt,
			&i.DefinitionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveSceneMemberEffectRun = `-- name: UpdateActiveSceneMemberEffectRun :exec
UPDATE active_scene_members SET effect_run_id = ? WHERE scene_id = ? AND device_id = ?
`

type UpdateActiveSceneMemberEffectRunParams struct {
	EffectRunID *string
	SceneID     string
	DeviceID    device.DeviceID
}

func (q *Queries) UpdateActiveSceneMemberEffectRun(ctx context.Context, arg UpdateActiveSceneMemberEffectRunParams) error {
	_, err := q.db.ExecContext(ctx, updateActiveSceneMemberEffectRun, arg.EffectRunID, arg.SceneID, arg.DeviceID)
	return err
}

const updateActiveSceneMemberExpected = `-- name: UpdateActiveSceneMemberExpected :exec
UPDATE active_scene_members
SET expected_on = ?,
    expected_brightness = ?,
    expected_color_temp = ?,
    expected_color_r = ?,
    expected_color_g = ?,
    expected_color_b = ?,
    expected_color_x = ?,
    expected_color_y = ?,
    expected_temperature = ?,
    expected_hvac_mode = ?,
    expected_fan_mode = ?,
    expected_swing = ?
WHERE scene_id = ? AND device_id = ?
`

type UpdateActiveSceneMemberExpectedParams struct {
	ExpectedOn          *int64
	ExpectedBrightness  *int64
	ExpectedColorTemp   *int64
	ExpectedColorR      *int64
	ExpectedColorG      *int64
	ExpectedColorB      *int64
	ExpectedColorX      *float64
	ExpectedColorY      *float64
	ExpectedTemperature *float64
	ExpectedHvacMode    *string
	ExpectedFanMode     *string
	ExpectedSwing       *string
	SceneID             string
	DeviceID            device.DeviceID
}

func (q *Queries) UpdateActiveSceneMemberExpected(ctx context.Context, arg UpdateActiveSceneMemberExpectedParams) error {
	_, err := q.db.ExecContext(ctx, updateActiveSceneMemberExpected,
		arg.ExpectedOn,
		arg.ExpectedBrightness,
		arg.ExpectedColorTemp,
		arg.ExpectedColorR,
		arg.ExpectedColorG,
		arg.ExpectedColorB,
		arg.ExpectedColorX,
		arg.ExpectedColorY,
		arg.ExpectedTemperature,
		arg.ExpectedHvacMode,
		arg.ExpectedFanMode,
		arg.ExpectedSwing,
		arg.SceneID,
		arg.DeviceID,
	)
	return err
}

const upsertActiveSceneRun = `-- name: UpsertActiveSceneRun :exec
INSERT INTO active_scene_runs (scene_id, run_id, started_at, definition_updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(scene_id) DO UPDATE SET
    run_id = excluded.run_id,
    started_at = excluded.started_at,
    definition_updated_at = excluded.definition_updated_at
`

type UpsertActiveSceneRunParams struct {
	SceneID             string
	RunID               string
	StartedAt           time.Time
	DefinitionUpdatedAt time.Time
}

func (q *Queries) UpsertActiveSceneRun(ctx context.Context, arg UpsertActiveSceneRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertActiveSceneRun,
		arg.SceneID,
		arg.RunID,
		arg.StartedAt,
		arg.DefinitionUpdatedAt,
	)
	return err
}
