// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: activity.sql

package sqlite

import (
	"context"
	"time"
)

const insertActivityEvent = `-- name: InsertActivityEvent :one

INSERT INTO activity_events (
    type, timestamp, message, payload_json,
    device_id, device_name, device_type, room_id, room_name,
    scene_id, scene_name,
    automation_id, automation_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertActivityEventParams struct {
	Type           string
	Timestamp      time.Time
	Message        string
	PayloadJson    string
	DeviceID       *string
	DeviceName     *string
	DeviceType     *string
	RoomID         *string
	RoomName       *string
	SceneID        *string
	SceneName      *string
	AutomationID   *string
	AutomationName *string
}

// Activity event persistence. QueryActivityEvents is the only query in the
// codebase with fully-dynamic filters, so it uses every gate trick we have:
//
//   - json_array_length + json_each: a single JSON-array param covers both
//     "match all" (empty array) and "match listed values" without a combinatorial
//     explosion of generated queries.
//   - CAST(narg AS TEXT) IS NULL OR col = CAST(narg AS TEXT): optional filter
//     on a nullable column. The CAST is there to pin the Go type to *string;
//     without it sqlc emits interface{}.
//   - COALESCE(narg, col): optional filter on a NOT NULL column (timestamp,
//     id). Self-neutral when narg is NULL, since col >= col is always true.
//   - IIF(lim > 0, lim, -1): single-query optional LIMIT; SQLite treats -1 as
//     unbounded.
func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertActivityEvent,
		arg.Type,
		arg.Timestamp,
		arg.Message,
		arg.PayloadJson,
		arg.DeviceID,
		arg.DeviceName,
		arg.DeviceType,
		arg.RoomID,
		arg.RoomName,
		arg.SceneID,
		arg.SceneName,
		arg.AutomationID,
		arg.AutomationName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const pruneActivityEventsOlderThan = `-- name: PruneActivityEventsOlderThan :execrows
DELETE FROM activity_events WHERE timestamp < ?
`

func (q *Queries) PruneActivityEventsOlderThan(ctx context.Context, timestamp time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneActivityEventsOlderThan, timestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queryActivityEvents = `-- name: QueryActivityEvents :many
SELECT id, type, timestamp, message, payload_json,
       device_id, device_name, device_type, room_id, room_name,
       scene_id, scene_name,
       automation_id, automation_name
FROM activity_events
WHERE
    (json_array_length(CAST(?1 AS TEXT)) = 0
     OR type IN (SELECT value FROM json_each(CAST(?1 AS TEXT))))
  AND type NOT IN (SELECT value FROM json_each(CAST(?2 AS TEXT)))
  AND (CAST(?3 AS TEXT) IS NULL OR device_id = CAST(?3 AS TEXT))
  AND (CAST(?4   AS TEXT) IS NULL OR room_id   = CAST(?4   AS TEXT))
  AND timestamp >= COALESCE(?5,  timestamp)
  AND id        <  COALESCE(?6, id + 1)
ORDER BY timestamp DESC, id DESC
LIMIT IIF(CAST(?7 AS INTEGER) > 0, CAST(?7 AS INTEGER), -1)
`

type QueryActivityEventsParams struct {
	TypesJson         string
	ExcludedTypesJson string
	DeviceID          *string
	RoomID            *string
	Since             *time.Time
	Before            *int64
	Lim               int64
}

func (q *Queries) QueryActivityEvents(ctx context.Context, arg QueryActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryActivityEvents,
		arg.TypesJson,
		arg.ExcludedTypesJson,
		arg.DeviceID,
		arg.RoomID,
		arg.Since,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Timestamp,
			&i.Message,
			&i.PayloadJson,
			&i.DeviceID,
			&i.DeviceName,
			&i.DeviceType,
			&i.RoomID,
			&i.RoomName,
			&i.SceneID,
			&i.SceneName,
			&i.AutomationID,
			&i.AutomationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
