// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: alarms.sql

package sqlite

import (
	"context"
	"time"
)

const countAlarmsByAlarmID = `-- name: CountAlarmsByAlarmID :one
SELECT COUNT(*) FROM alarms WHERE alarm_id = ?
`

func (q *Queries) CountAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlarmsByAlarmID, alarmID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAlarmsByAlarmID = `-- name: DeleteAlarmsByAlarmID :execrows
DELETE FROM alarms WHERE alarm_id = ?
`

func (q *Queries) DeleteAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlarmsByAlarmID, alarmID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAlarm = `-- name: InsertAlarm :one

INSERT INTO alarms (alarm_id, severity, kind, message, source, raised_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, alarm_id, severity, kind, message, source, raised_at
`

type InsertAlarmParams struct {
	AlarmID  string
	Severity string
	Kind     string
	Message  string
	Source   string
	RaisedAt time.Time
}

// Alarms persistence. One row per raise; grouping by alarm_id happens in Go.
// Deletion is by alarm_id, removing every row belonging to a logical alarm
// in one shot. The user-facing identity is alarm_id, not the row id.
func (q *Queries) InsertAlarm(ctx context.Context, arg InsertAlarmParams) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, insertAlarm,
		arg.AlarmID,
		arg.Severity,
		arg.Kind,
		arg.Message,
		arg.Source,
		arg.RaisedAt,
	)
	var i Alarm
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.Severity,
		&i.Kind,
		&i.Message,
		&i.Source,
		&i.RaisedAt,
	)
	return i, err
}

const listAlarms = `-- name: ListAlarms :many
SELECT id, alarm_id, severity, kind, message, source, raised_at
FROM alarms
ORDER BY raised_at DESC, id DESC
`

func (q *Queries) ListAlarms(ctx context.Context) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.Severity,
			&i.Kind,
			&i.Message,
			&i.Source,
			&i.RaisedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
