// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: automations.sql

package sqlite

import (
	"context"
	"time"
)

const batchDeleteAutomations = `-- name: BatchDeleteAutomations :execrows
DELETE FROM automations
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) BatchDeleteAutomations(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteAutomations, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearAutomationIcon = `-- name: ClearAutomationIcon :exec
UPDATE automations SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearAutomationIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearAutomationIcon, id)
	return err
}

const createAutomation = `-- name: CreateAutomation :exec

INSERT INTO automations (id, name, enabled, cooldown_seconds, created_by)
VALUES (?, ?, ?, ?, ?)
`

type CreateAutomationParams struct {
	ID              string
	Name            string
	Enabled         bool
	CooldownSeconds float64
	CreatedBy       *string
}

// Automations own three related tables: automations, automation_nodes,
// automation_edges. GetAutomationGraph is composed in Go from three sqlc
// queries since sqlc's SQLite parser doesn't support data-modifying CTEs.
func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) error {
	_, err := q.db.ExecContext(ctx, createAutomation,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.CooldownSeconds,
		arg.CreatedBy,
	)
	return err
}

const createAutomationEdge = `-- name: CreateAutomationEdge :exec
INSERT INTO automation_edges (id, automation_id, from_node_id, to_node_id)
VALUES (?, ?, ?, ?)
`

type CreateAutomationEdgeParams struct {
	ID           string
	AutomationID string
	FromNodeID   string
	ToNodeID     string
}

func (q *Queries) CreateAutomationEdge(ctx context.Context, arg CreateAutomationEdgeParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationEdge,
		arg.ID,
		arg.AutomationID,
		arg.FromNodeID,
		arg.ToNodeID,
	)
	return err
}

const createAutomationNode = `-- name: CreateAutomationNode :exec
INSERT INTO automation_nodes (id, automation_id, type, config, position_x, position_y)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAutomationNodeParams struct {
	ID           string
	AutomationID string
	Type         string
	Config       string
	PositionX    float64
	PositionY    float64
}

func (q *Queries) CreateAutomationNode(ctx context.Context, arg CreateAutomationNodeParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationNode,
		arg.ID,
		arg.AutomationID,
		arg.Type,
		arg.Config,
		arg.PositionX,
		arg.PositionY,
	)
	return err
}

const deleteAutomation = `-- name: DeleteAutomation :exec
DELETE FROM automations WHERE id = ?
`

func (q *Queries) DeleteAutomation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAutomation, id)
	return err
}

const deleteAutomationEdge = `-- name: DeleteAutomationEdge :exec
DELETE FROM automation_edges WHERE id = ?
`

func (q *Queries) DeleteAutomationEdge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationEdge, id)
	return err
}

const deleteAutomationNode = `-- name: DeleteAutomationNode :exec
DELETE FROM automation_nodes WHERE id = ?
`

func (q *Queries) DeleteAutomationNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationNode, id)
	return err
}

const getAutomation = `-- name: GetAutomation :one
SELECT a.id, a.name, a.icon, a.enabled, a.cooldown_seconds, a.last_fired_at, a.created_at, a.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM automations a
LEFT JOIN users u ON u.id = a.created_by
WHERE a.id = ?
`

type GetAutomationRow struct {
	ID              string
	Name            string
	Icon            *string
	Enabled         bool
	CooldownSeconds float64
	LastFiredAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetAutomation(ctx context.Context, id string) (GetAutomationRow, error) {
	row := q.db.QueryRowContext(ctx, getAutomation, id)
	var i GetAutomationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Enabled,
		&i.CooldownSeconds,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listAutomationEdges = `-- name: ListAutomationEdges :many
SELECT id, automation_id, from_node_id, to_node_id
FROM automation_edges
WHERE automation_id = ?
`

func (q *Queries) ListAutomationEdges(ctx context.Context, automationID string) ([]AutomationEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationEdges, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationEdge
	for rows.Next() {
		var i AutomationEdge
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.FromNodeID,
			&i.ToNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationNodes = `-- name: ListAutomationNodes :many
SELECT id, automation_id, type, config, position_x, position_y
FROM automation_nodes
WHERE automation_id = ?
`

func (q *Queries) ListAutomationNodes(ctx context.Context, automationID string) ([]AutomationNode, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationNodes, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationNode
	for rows.Next() {
		var i AutomationNode
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.Type,
			&i.Config,
			&i.PositionX,
			&i.PositionY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomations = `-- name: ListAutomations :many
SELECT a.id, a.name, a.icon, a.enabled, a.cooldown_seconds, a.last_fired_at, a.created_at, a.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM automations a
LEFT JOIN users u ON u.id = a.created_by
`

type ListAutomationsRow struct {
	ID              string
	Name            string
	Icon            *string
	Enabled         bool
	CooldownSeconds float64
	LastFiredAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListAutomations(ctx context.Context) ([]ListAutomationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutomationsRow
	for rows.Next() {
		var i ListAutomationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Enabled,
			&i.CooldownSeconds,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAutomations = `-- name: ListEnabledAutomations :many
SELECT a.id, a.name, a.icon, a.enabled, a.cooldown_seconds, a.last_fired_at, a.created_at, a.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM automations a
LEFT JOIN users u ON u.id = a.created_by
WHERE a.enabled = true
`

type ListEnabledAutomationsRow struct {
	ID              string
	Name            string
	Icon            *string
	Enabled         bool
	CooldownSeconds float64
	LastFiredAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListEnabledAutomations(ctx context.Context) ([]ListEnabledAutomationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledAutomationsRow
	for rows.Next() {
		var i ListEnabledAutomationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Enabled,
			&i.CooldownSeconds,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomationEnabled = `-- name: UpdateAutomationEnabled :exec
UPDATE automations SET enabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateAutomationEnabledParams struct {
	Enabled bool
	ID      string
}

func (q *Queries) UpdateAutomationEnabled(ctx context.Context, arg UpdateAutomationEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateAutomationEnabled, arg.Enabled, arg.ID)
	return err
}

const updateAutomationFields = `-- name: UpdateAutomationFields :exec
UPDATE automations SET
    name             = COALESCE(?1,     name),
    icon             = COALESCE(?2,     icon),
    enabled          = COALESCE(?3,  enabled),
    cooldown_seconds = COALESCE(?4, cooldown_seconds),
    updated_at       = CURRENT_TIMESTAMP
WHERE id = ?5
`

type UpdateAutomationFieldsParams struct {
	Name     *string
	Icon     *string
	Enabled  *bool
	Cooldown *float64
	ID       string
}

// Partial update via COALESCE(narg, col) gate. Nil narg values leave their
// column untouched. The nullable icon column can't be cleared through this
// query; use ClearAutomationIcon for that. All args are named so sqlc's
// SQLite emitter keeps a consistent indexing scheme (mixing named and bare
// positional `?` produced off-by-one parameter indices in 1.31.0).
func (q *Queries) UpdateAutomationFields(ctx context.Context, arg UpdateAutomationFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateAutomationFields,
		arg.Name,
		arg.Icon,
		arg.Enabled,
		arg.Cooldown,
		arg.ID,
	)
	return err
}

const updateAutomationLastFired = `-- name: UpdateAutomationLastFired :exec
UPDATE automations SET last_fired_at = ? WHERE id = ?
`

type UpdateAutomationLastFiredParams struct {
	LastFiredAt *time.Time
	ID          string
}

// Stamps when the automation most recently fired. updated_at is intentionally
// NOT touched so the "last edited" semantics stay distinct from "last fired".
func (q *Queries) UpdateAutomationLastFired(ctx context.Context, arg UpdateAutomationLastFiredParams) error {
	_, err := q.db.ExecContext(ctx, updateAutomationLastFired, arg.LastFiredAt, arg.ID)
	return err
}
