// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: automation_node_state.sql

package sqlite

import (
	"context"
)

const deleteAutomationNodeStateByAutomation = `-- name: DeleteAutomationNodeStateByAutomation :exec
DELETE FROM automation_node_state WHERE automation_id = ?
`

func (q *Queries) DeleteAutomationNodeStateByAutomation(ctx context.Context, automationID string) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationNodeStateByAutomation, automationID)
	return err
}

const getAutomationNodeState = `-- name: GetAutomationNodeState :one

SELECT value FROM automation_node_state
WHERE automation_id = ? AND node_id = ? AND key = ?
`

type GetAutomationNodeStateParams struct {
	AutomationID string
	NodeID       string
	Key          string
}

// Per-node runtime state for stateful automation nodes (e.g. cycle_scenes
// index). Generic key/value JSON store keyed by (automation_id, node_id, key).
// Cascades on automation and node deletion, so graph replacement wipes state
// automatically.
func (q *Queries) GetAutomationNodeState(ctx context.Context, arg GetAutomationNodeStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAutomationNodeState, arg.AutomationID, arg.NodeID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listAutomationNodeStateByAutomation = `-- name: ListAutomationNodeStateByAutomation :many
SELECT node_id, key, value FROM automation_node_state
WHERE automation_id = ?
`

type ListAutomationNodeStateByAutomationRow struct {
	NodeID string
	Key    string
	Value  string
}

func (q *Queries) ListAutomationNodeStateByAutomation(ctx context.Context, automationID string) ([]ListAutomationNodeStateByAutomationRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationNodeStateByAutomation, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutomationNodeStateByAutomationRow
	for rows.Next() {
		var i ListAutomationNodeStateByAutomationRow
		if err := rows.Scan(&i.NodeID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAutomationNodeState = `-- name: SetAutomationNodeState :exec
INSERT INTO automation_node_state (automation_id, node_id, key, value, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(automation_id, node_id, key) DO UPDATE SET
    value      = excluded.value,
    updated_at = CURRENT_TIMESTAMP
`

type SetAutomationNodeStateParams struct {
	AutomationID string
	NodeID       string
	Key          string
	Value        string
}

func (q *Queries) SetAutomationNodeState(ctx context.Context, arg SetAutomationNodeStateParams) error {
	_, err := q.db.ExecContext(ctx, setAutomationNodeState,
		arg.AutomationID,
		arg.NodeID,
		arg.Key,
		arg.Value,
	)
	return err
}
