// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: device_tags.sql

package sqlite

import (
	"context"
)

const deleteDeviceTags = `-- name: DeleteDeviceTags :exec
DELETE FROM device_tags WHERE device_id = ?
`

func (q *Queries) DeleteDeviceTags(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceTags, deviceID)
	return err
}

const insertDeviceTag = `-- name: InsertDeviceTag :exec
INSERT OR IGNORE INTO device_tags (device_id, tag) VALUES (?, ?)
`

type InsertDeviceTagParams struct {
	DeviceID string
	Tag      string
}

func (q *Queries) InsertDeviceTag(ctx context.Context, arg InsertDeviceTagParams) error {
	_, err := q.db.ExecContext(ctx, insertDeviceTag, arg.DeviceID, arg.Tag)
	return err
}

const listAllDeviceTags = `-- name: ListAllDeviceTags :many
SELECT device_id, tag FROM device_tags
`

func (q *Queries) ListAllDeviceTags(ctx context.Context) ([]DeviceTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeviceTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceTag
	for rows.Next() {
		var i DeviceTag
		if err := rows.Scan(&i.DeviceID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTags = `-- name: ListDeviceTags :many
SELECT tag FROM device_tags WHERE device_id = ?
`

func (q *Queries) ListDeviceTags(ctx context.Context, deviceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTags, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
