// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: device_state_history.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const insertStateSample = `-- name: InsertStateSample :one
INSERT INTO device_state_samples (device_id, field, value, recorded_at)
VALUES (
    ?1,
    ?2,
    ?3,
    CAST(?4 AS TEXT)
)
RETURNING id
`

type InsertStateSampleParams struct {
	DeviceID   device.DeviceID
	Field      string
	Value      float64
	RecordedAt string
}

func (q *Queries) InsertStateSample(ctx context.Context, arg InsertStateSampleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStateSample,
		arg.DeviceID,
		arg.Field,
		arg.Value,
		arg.RecordedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const pruneDeviceStateSamplesOlderThan = `-- name: PruneDeviceStateSamplesOlderThan :execrows
DELETE FROM device_state_samples WHERE recorded_at < CAST(?1 AS TEXT)
`

func (q *Queries) PruneDeviceStateSamplesOlderThan(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDeviceStateSamplesOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queryStateHistoryBucketed = `-- name: QueryStateHistoryBucketed :many
SELECT
    device_id,
    field,
    CAST(strftime('%s', substr(recorded_at, 1, 19)) AS INTEGER) / CAST(?1 AS INTEGER) AS bucket_key,
    CAST(AVG(value) AS REAL) AS bucket_value,
    CAST(strftime('%s', substr(MIN(recorded_at), 1, 19)) AS INTEGER) AS bucket_start_unix
FROM device_state_samples
WHERE device_id IN (SELECT value FROM json_each(CAST(?2 AS TEXT)))
  AND (json_array_length(CAST(?3 AS TEXT)) = 0
       OR field IN (SELECT value FROM json_each(CAST(?3 AS TEXT))))
  AND recorded_at >= CAST(?4 AS TEXT)
  AND recorded_at <= CAST(?5 AS TEXT)
GROUP BY device_id, field, bucket_key
ORDER BY device_id ASC, field ASC, bucket_start_unix ASC
`

type QueryStateHistoryBucketedParams struct {
	BucketSeconds int64
	DeviceIdsJson string
	FieldsJson    string
	FromTime      string
	ToTime        string
}

type QueryStateHistoryBucketedRow struct {
	DeviceID        device.DeviceID
	Field           string
	BucketKey       int64
	BucketValue     float64
	BucketStartUnix int64
}

// Groups samples into fixed-size time buckets. bucket_seconds must be > 0.
// Per bucket returns AVG(value) and the Unix epoch of the earliest recorded_at
// (bucket_start_unix). Returning an INTEGER epoch sidesteps the sqlite driver's
// re-serialisation of TIMESTAMP aggregates. The substr(..., 1, 19) keeps
// strftime happy across the stored RFC3339Nano form.
func (q *Queries) QueryStateHistoryBucketed(ctx context.Context, arg QueryStateHistoryBucketedParams) ([]QueryStateHistoryBucketedRow, error) {
	rows, err := q.db.QueryContext(ctx, queryStateHistoryBucketed,
		arg.BucketSeconds,
		arg.DeviceIdsJson,
		arg.FieldsJson,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryStateHistoryBucketedRow
	for rows.Next() {
		var i QueryStateHistoryBucketedRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Field,
			&i.BucketKey,
			&i.BucketValue,
			&i.BucketStartUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryStateHistoryRaw = `-- name: QueryStateHistoryRaw :many
SELECT device_id, field, value, recorded_at
FROM device_state_samples
WHERE device_id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
  AND (json_array_length(CAST(?2 AS TEXT)) = 0
       OR field IN (SELECT value FROM json_each(CAST(?2 AS TEXT))))
  AND recorded_at >= CAST(?3 AS TEXT)
  AND recorded_at <= CAST(?4 AS TEXT)
ORDER BY device_id ASC, field ASC, recorded_at ASC
LIMIT IIF(CAST(?5 AS INTEGER) > 0, CAST(?5 AS INTEGER), -1)
`

type QueryStateHistoryRawParams struct {
	DeviceIdsJson string
	FieldsJson    string
	FromTime      string
	ToTime        string
	Lim           int64
}

type QueryStateHistoryRawRow struct {
	DeviceID   device.DeviceID
	Field      string
	Value      float64
	RecordedAt time.Time
}

// device_ids_json and fields_json are JSON-array strings. An empty array in
// fields_json matches every field. device_ids_json must be non-empty (callers
// always pick sources explicitly). Time bounds are RFC3339Nano UTC strings so
// lexicographic comparison matches chronological order.
func (q *Queries) QueryStateHistoryRaw(ctx context.Context, arg QueryStateHistoryRawParams) ([]QueryStateHistoryRawRow, error) {
	rows, err := q.db.QueryContext(ctx, queryStateHistoryRaw,
		arg.DeviceIdsJson,
		arg.FieldsJson,
		arg.FromTime,
		arg.ToTime,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryStateHistoryRawRow
	for rows.Next() {
		var i QueryStateHistoryRawRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Field,
			&i.Value,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
