// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: devices.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const clearDeviceIcon = `-- name: ClearDeviceIcon :exec
UPDATE devices SET icon = NULL WHERE id = ?
`

func (q *Queries) ClearDeviceIcon(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, clearDeviceIcon, id)
	return err
}

const createDevice = `-- name: CreateDevice :exec

INSERT INTO devices (id, name, source, type, capabilities, available, removed)
VALUES (?, ?, ?, ?, ?, false, false)
`

type CreateDeviceParams struct {
	ID           device.DeviceID
	Name         string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
}

// Capabilities is stored as a JSON TEXT blob; the Go wrapper marshals it
// before hitting these queries and unmarshals on read (with a legacy format
// fallback preserved in mapper.go).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Type,
		arg.Capabilities,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, icon, source, type, capabilities, available, removed, last_seen
FROM devices
WHERE id = ?
`

type GetDeviceRow struct {
	ID           device.DeviceID
	Name         string
	Icon         *string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
	Available    bool
	Removed      bool
	LastSeen     *time.Time
}

func (q *Queries) GetDevice(ctx context.Context, id device.DeviceID) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Source,
		&i.Type,
		&i.Capabilities,
		&i.Available,
		&i.Removed,
		&i.LastSeen,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, icon, source, type, capabilities, available, removed, last_seen
FROM devices
`

type ListDevicesRow struct {
	ID           device.DeviceID
	Name         string
	Icon         *string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
	Available    bool
	Removed      bool
	LastSeen     *time.Time
}

func (q *Queries) ListDevices(ctx context.Context) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Source,
			&i.Type,
			&i.Capabilities,
			&i.Available,
			&i.Removed,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySource = `-- name: ListDevicesBySource :many
SELECT id, name, icon, source, type, capabilities, available, removed, last_seen
FROM devices
WHERE source = ?
`

type ListDevicesBySourceRow struct {
	ID           device.DeviceID
	Name         string
	Icon         *string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
	Available    bool
	Removed      bool
	LastSeen     *time.Time
}

func (q *Queries) ListDevicesBySource(ctx context.Context, source device.Source) ([]ListDevicesBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesBySourceRow
	for rows.Next() {
		var i ListDevicesBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Source,
			&i.Type,
			&i.Capabilities,
			&i.Available,
			&i.Removed,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices
SET name = ?, available = ?, removed = ?, last_seen = ?
WHERE id = ?
`

type UpdateDeviceParams struct {
	Name      string
	Available bool
	Removed   bool
	LastSeen  *time.Time
	ID        device.DeviceID
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Name,
		arg.Available,
		arg.Removed,
		arg.LastSeen,
		arg.ID,
	)
	return err
}

const updateDeviceIcon = `-- name: UpdateDeviceIcon :exec

UPDATE devices SET icon = ? WHERE id = ?
`

type UpdateDeviceIconParams struct {
	Icon *string
	ID   device.DeviceID
}

// The nullable icon column needs a dedicated ClearDeviceIcon because COALESCE
// can't distinguish "leave alone" from "set to NULL". UpdateDevice deliberately
// skips the icon column so MQTT-driven sync (UpsertDevice) and re-sync don't
// overwrite a user-set icon.
func (q *Queries) UpdateDeviceIcon(ctx context.Context, arg UpdateDeviceIconParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceIcon, arg.Icon, arg.ID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, name, source, type, capabilities, available, removed)
VALUES (?, ?, ?, ?, ?, false, false)
ON CONFLICT(id) DO UPDATE SET
    name         = excluded.name,
    source       = excluded.source,
    type         = excluded.type,
    capabilities = excluded.capabilities,
    removed      = false
`

type UpsertDeviceParams struct {
	ID           device.DeviceID
	Name         string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
}

// Clears the removed flag on conflict so re-discovered devices become active.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Type,
		arg.Capabilities,
	)
	return err
}
