// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: devices.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const clearDeviceDisplayBrightness = `-- name: ClearDeviceDisplayBrightness :exec
UPDATE devices SET display_brightness = NULL WHERE id = ?
`

func (q *Queries) ClearDeviceDisplayBrightness(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, clearDeviceDisplayBrightness, id)
	return err
}

const clearDeviceDisplayColor = `-- name: ClearDeviceDisplayColor :exec
UPDATE devices SET display_color = NULL WHERE id = ?
`

func (q *Queries) ClearDeviceDisplayColor(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, clearDeviceDisplayColor, id)
	return err
}

const clearDeviceIcon = `-- name: ClearDeviceIcon :exec
UPDATE devices SET icon = NULL WHERE id = ?
`

func (q *Queries) ClearDeviceIcon(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, clearDeviceIcon, id)
	return err
}

const createDevice = `-- name: CreateDevice :exec

INSERT INTO devices (id, friendly_name, source, type, capabilities, available, removed)
VALUES (?, ?, ?, ?, ?, false, false)
`

type CreateDeviceParams struct {
	ID           device.DeviceID
	FriendlyName string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
}

// Capabilities is stored as a JSON TEXT blob; the Go wrapper marshals it
// before hitting these queries and unmarshals on read.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.FriendlyName,
		arg.Source,
		arg.Type,
		arg.Capabilities,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, friendly_name, icon, display_color, display_brightness, source, type, capabilities, available, removed, disabled, seen, last_seen
FROM devices
WHERE id = ?
`

type GetDeviceRow struct {
	ID                device.DeviceID
	Name              *string
	FriendlyName      string
	Icon              *string
	DisplayColor      *string
	DisplayBrightness *int64
	Source            device.Source
	Type              device.DeviceType
	Capabilities      string
	Available         bool
	Removed           bool
	Disabled          bool
	Seen              bool
	LastSeen          *time.Time
}

func (q *Queries) GetDevice(ctx context.Context, id device.DeviceID) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FriendlyName,
		&i.Icon,
		&i.DisplayColor,
		&i.DisplayBrightness,
		&i.Source,
		&i.Type,
		&i.Capabilities,
		&i.Available,
		&i.Removed,
		&i.Disabled,
		&i.Seen,
		&i.LastSeen,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, friendly_name, icon, display_color, display_brightness, source, type, capabilities, available, removed, disabled, seen, last_seen
FROM devices
`

type ListDevicesRow struct {
	ID                device.DeviceID
	Name              *string
	FriendlyName      string
	Icon              *string
	DisplayColor      *string
	DisplayBrightness *int64
	Source            device.Source
	Type              device.DeviceType
	Capabilities      string
	Available         bool
	Removed           bool
	Disabled          bool
	Seen              bool
	LastSeen          *time.Time
}

func (q *Queries) ListDevices(ctx context.Context) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FriendlyName,
			&i.Icon,
			&i.DisplayColor,
			&i.DisplayBrightness,
			&i.Source,
			&i.Type,
			&i.Capabilities,
			&i.Available,
			&i.Removed,
			&i.Disabled,
			&i.Seen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesBySource = `-- name: ListDevicesBySource :many
SELECT id, name, friendly_name, icon, display_color, display_brightness, source, type, capabilities, available, removed, disabled, seen, last_seen
FROM devices
WHERE source = ?
`

type ListDevicesBySourceRow struct {
	ID                device.DeviceID
	Name              *string
	FriendlyName      string
	Icon              *string
	DisplayColor      *string
	DisplayBrightness *int64
	Source            device.Source
	Type              device.DeviceType
	Capabilities      string
	Available         bool
	Removed           bool
	Disabled          bool
	Seen              bool
	LastSeen          *time.Time
}

func (q *Queries) ListDevicesBySource(ctx context.Context, source device.Source) ([]ListDevicesBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesBySourceRow
	for rows.Next() {
		var i ListDevicesBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FriendlyName,
			&i.Icon,
			&i.DisplayColor,
			&i.DisplayBrightness,
			&i.Source,
			&i.Type,
			&i.Capabilities,
			&i.Available,
			&i.Removed,
			&i.Disabled,
			&i.Seen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledDeviceIDs = `-- name: ListDisabledDeviceIDs :many
SELECT id FROM devices WHERE disabled = true
`

func (q *Queries) ListDisabledDeviceIDs(ctx context.Context) ([]device.DeviceID, error) {
	rows, err := q.db.QueryContext(ctx, listDisabledDeviceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []device.DeviceID
	for rows.Next() {
		var id device.DeviceID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDevicesSeen = `-- name: MarkDevicesSeen :execrows
UPDATE devices SET seen = true
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) MarkDevicesSeen(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDevicesSeen, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDeviceDisabled = `-- name: SetDeviceDisabled :exec
UPDATE devices SET disabled = ? WHERE id = ?
`

type SetDeviceDisabledParams struct {
	Disabled bool
	ID       device.DeviceID
}

func (q *Queries) SetDeviceDisabled(ctx context.Context, arg SetDeviceDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setDeviceDisabled, arg.Disabled, arg.ID)
	return err
}

const setDeviceName = `-- name: SetDeviceName :exec


UPDATE devices SET name = ? WHERE id = ?
`

type SetDeviceNameParams struct {
	Name *string
	ID   device.DeviceID
}

// The nullable icon and display_color columns need dedicated clear queries
// because COALESCE can't distinguish "leave alone" from "set to NULL".
// UpdateDevice deliberately skips both so MQTT-driven sync (UpsertDevice) and
// re-sync don't overwrite what the user set.
// The disabled flag, the name override and the seen flag are user-owned, so each
// gets its own setter for the same reason the icon column does: UpdateDevice
// overwrites every column it names, and the device-removal path calls it with an
// otherwise zero-value struct. UpsertDevice leaves all four alone as well, or an
// adapter re-sync would undo them.
func (q *Queries) SetDeviceName(ctx context.Context, arg SetDeviceNameParams) error {
	_, err := q.db.ExecContext(ctx, setDeviceName, arg.Name, arg.ID)
	return err
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices
SET available = ?, removed = ?, last_seen = ?
WHERE id = ?
`

type UpdateDeviceParams struct {
	Available bool
	Removed   bool
	LastSeen  *time.Time
	ID        device.DeviceID
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Available,
		arg.Removed,
		arg.LastSeen,
		arg.ID,
	)
	return err
}

const updateDeviceDisplayBrightness = `-- name: UpdateDeviceDisplayBrightness :exec
UPDATE devices SET display_brightness = ? WHERE id = ?
`

type UpdateDeviceDisplayBrightnessParams struct {
	DisplayBrightness *int64
	ID                device.DeviceID
}

func (q *Queries) UpdateDeviceDisplayBrightness(ctx context.Context, arg UpdateDeviceDisplayBrightnessParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceDisplayBrightness, arg.DisplayBrightness, arg.ID)
	return err
}

const updateDeviceDisplayColor = `-- name: UpdateDeviceDisplayColor :exec
UPDATE devices SET display_color = ? WHERE id = ?
`

type UpdateDeviceDisplayColorParams struct {
	DisplayColor *string
	ID           device.DeviceID
}

func (q *Queries) UpdateDeviceDisplayColor(ctx context.Context, arg UpdateDeviceDisplayColorParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceDisplayColor, arg.DisplayColor, arg.ID)
	return err
}

const updateDeviceIcon = `-- name: UpdateDeviceIcon :exec
UPDATE devices SET icon = ? WHERE id = ?
`

type UpdateDeviceIconParams struct {
	Icon *string
	ID   device.DeviceID
}

func (q *Queries) UpdateDeviceIcon(ctx context.Context, arg UpdateDeviceIconParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceIcon, arg.Icon, arg.ID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, friendly_name, source, type, capabilities, available, removed)
VALUES (?, ?, ?, ?, ?, false, false)
ON CONFLICT(id) DO UPDATE SET
    friendly_name = excluded.friendly_name,
    source        = excluded.source,
    type          = excluded.type,
    capabilities  = excluded.capabilities,
    removed       = false
`

type UpsertDeviceParams struct {
	ID           device.DeviceID
	FriendlyName string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
}

// Refreshes every adapter-owned column, including the friendly name, and clears
// the removed flag when a device reappears. The name column is the user's
// override and is never touched here.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.FriendlyName,
		arg.Source,
		arg.Type,
		arg.Capabilities,
	)
	return err
}
