// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: effects.sql

package sqlite

import (
	"context"
	"time"
)

const clearEffectIcon = `-- name: ClearEffectIcon :exec
UPDATE effects SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearEffectIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearEffectIcon, id)
	return err
}

const clearEffectNativeName = `-- name: ClearEffectNativeName :exec
UPDATE effects SET native_name = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearEffectNativeName(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearEffectNativeName, id)
	return err
}

const createEffect = `-- name: CreateEffect :exec
INSERT INTO effects (id, name, icon, kind, native_name, loop, duration_ms, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEffectParams struct {
	ID         string
	Name       string
	Icon       *string
	Kind       string
	NativeName *string
	Loop       int64
	DurationMs int64
	CreatedBy  *string
}

func (q *Queries) CreateEffect(ctx context.Context, arg CreateEffectParams) error {
	_, err := q.db.ExecContext(ctx, createEffect,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Kind,
		arg.NativeName,
		arg.Loop,
		arg.DurationMs,
		arg.CreatedBy,
	)
	return err
}

const createEffectClip = `-- name: CreateEffectClip :exec
INSERT INTO effect_clips (id, track_id, start_ms, transition_min_ms, transition_max_ms, kind, config)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEffectClipParams struct {
	ID              string
	TrackID         string
	StartMs         int64
	TransitionMinMs int64
	TransitionMaxMs int64
	Kind            string
	Config          string
}

func (q *Queries) CreateEffectClip(ctx context.Context, arg CreateEffectClipParams) error {
	_, err := q.db.ExecContext(ctx, createEffectClip,
		arg.ID,
		arg.TrackID,
		arg.StartMs,
		arg.TransitionMinMs,
		arg.TransitionMaxMs,
		arg.Kind,
		arg.Config,
	)
	return err
}

const createEffectTrack = `-- name: CreateEffectTrack :exec
INSERT INTO effect_tracks (id, effect_id, track_index, name)
VALUES (?, ?, ?, ?)
`

type CreateEffectTrackParams struct {
	ID         string
	EffectID   string
	TrackIndex int64
	Name       string
}

func (q *Queries) CreateEffectTrack(ctx context.Context, arg CreateEffectTrackParams) error {
	_, err := q.db.ExecContext(ctx, createEffectTrack,
		arg.ID,
		arg.EffectID,
		arg.TrackIndex,
		arg.Name,
	)
	return err
}

const deleteActiveEffectByTarget = `-- name: DeleteActiveEffectByTarget :exec
DELETE FROM active_effects WHERE target_type = ? AND target_id = ?
`

type DeleteActiveEffectByTargetParams struct {
	TargetType string
	TargetID   string
}

func (q *Queries) DeleteActiveEffectByTarget(ctx context.Context, arg DeleteActiveEffectByTargetParams) error {
	_, err := q.db.ExecContext(ctx, deleteActiveEffectByTarget, arg.TargetType, arg.TargetID)
	return err
}

const deleteEffect = `-- name: DeleteEffect :exec
DELETE FROM effects WHERE id = ?
`

func (q *Queries) DeleteEffect(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEffect, id)
	return err
}

const deleteEffectTracksByEffect = `-- name: DeleteEffectTracksByEffect :exec
DELETE FROM effect_tracks WHERE effect_id = ?
`

func (q *Queries) DeleteEffectTracksByEffect(ctx context.Context, effectID string) error {
	_, err := q.db.ExecContext(ctx, deleteEffectTracksByEffect, effectID)
	return err
}

const deleteVolatileActiveEffects = `-- name: DeleteVolatileActiveEffects :execrows
DELETE FROM active_effects WHERE volatile = 1
`

func (q *Queries) DeleteVolatileActiveEffects(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVolatileActiveEffects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEffect = `-- name: GetEffect :one
SELECT e.id, e.name, e.icon, e.kind, e.native_name, e.loop, e.duration_ms,
       e.created_at, e.updated_at,
       u.id       AS creator_id,
       u.username AS creator_username,
       u.name     AS creator_name
FROM effects e
LEFT JOIN users u ON u.id = e.created_by
WHERE e.id = ?
`

type GetEffectRow struct {
	ID              string
	Name            string
	Icon            *string
	Kind            string
	NativeName      *string
	Loop            int64
	DurationMs      int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetEffect(ctx context.Context, id string) (GetEffectRow, error) {
	row := q.db.QueryRowContext(ctx, getEffect, id)
	var i GetEffectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Kind,
		&i.NativeName,
		&i.Loop,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listActiveEffects = `-- name: ListActiveEffects :many
SELECT id, effect_id, target_type, target_id, started_at, volatile
FROM active_effects
`

func (q *Queries) ListActiveEffects(ctx context.Context) ([]ActiveEffect, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveEffect
	for rows.Next() {
		var i ActiveEffect
		if err := rows.Scan(
			&i.ID,
			&i.EffectID,
			&i.TargetType,
			&i.TargetID,
			&i.StartedAt,
			&i.Volatile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectClips = `-- name: ListEffectClips :many
SELECT id, track_id, start_ms, transition_min_ms, transition_max_ms, kind, config
FROM effect_clips
WHERE track_id = ?
ORDER BY start_ms, id
`

func (q *Queries) ListEffectClips(ctx context.Context, trackID string) ([]EffectClip, error) {
	rows, err := q.db.QueryContext(ctx, listEffectClips, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EffectClip
	for rows.Next() {
		var i EffectClip
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.StartMs,
			&i.TransitionMinMs,
			&i.TransitionMaxMs,
			&i.Kind,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectTracks = `-- name: ListEffectTracks :many
SELECT id, effect_id, track_index, name
FROM effect_tracks
WHERE effect_id = ?
ORDER BY track_index
`

func (q *Queries) ListEffectTracks(ctx context.Context, effectID string) ([]EffectTrack, error) {
	rows, err := q.db.QueryContext(ctx, listEffectTracks, effectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EffectTrack
	for rows.Next() {
		var i EffectTrack
		if err := rows.Scan(
			&i.ID,
			&i.EffectID,
			&i.TrackIndex,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffects = `-- name: ListEffects :many
SELECT e.id, e.name, e.icon, e.kind, e.native_name, e.loop, e.duration_ms,
       e.created_at, e.updated_at,
       u.id       AS creator_id,
       u.username AS creator_username,
       u.name     AS creator_name
FROM effects e
LEFT JOIN users u ON u.id = e.created_by
`

type ListEffectsRow struct {
	ID              string
	Name            string
	Icon            *string
	Kind            string
	NativeName      *string
	Loop            int64
	DurationMs      int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListEffects(ctx context.Context) ([]ListEffectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectsRow
	for rows.Next() {
		var i ListEffectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Kind,
			&i.NativeName,
			&i.Loop,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEffect = `-- name: UpdateEffect :exec
UPDATE effects SET
    name        = COALESCE(?1,        name),
    icon        = COALESCE(?2,        icon),
    kind        = COALESCE(?3,        kind),
    native_name = COALESCE(?4, native_name),
    loop        = COALESCE(?5,        loop),
    duration_ms = COALESCE(?6, duration_ms),
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?7
`

type UpdateEffectParams struct {
	Name       *string
	Icon       *string
	Kind       *string
	NativeName *string
	Loop       *int64
	DurationMs *int64
	ID         string
}

func (q *Queries) UpdateEffect(ctx context.Context, arg UpdateEffectParams) error {
	_, err := q.db.ExecContext(ctx, updateEffect,
		arg.Name,
		arg.Icon,
		arg.Kind,
		arg.NativeName,
		arg.Loop,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const updateEffectDuration = `-- name: UpdateEffectDuration :exec
UPDATE effects SET duration_ms = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateEffectDurationParams struct {
	DurationMs int64
	ID         string
}

func (q *Queries) UpdateEffectDuration(ctx context.Context, arg UpdateEffectDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateEffectDuration, arg.DurationMs, arg.ID)
	return err
}

const upsertActiveEffect = `-- name: UpsertActiveEffect :exec
INSERT INTO active_effects (id, effect_id, target_type, target_id, started_at, volatile)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(target_type, target_id) DO UPDATE SET
    effect_id  = excluded.effect_id,
    started_at = excluded.started_at,
    volatile   = excluded.volatile
`

type UpsertActiveEffectParams struct {
	ID         string
	EffectID   string
	TargetType string
	TargetID   string
	StartedAt  time.Time
	Volatile   int64
}

func (q *Queries) UpsertActiveEffect(ctx context.Context, arg UpsertActiveEffectParams) error {
	_, err := q.db.ExecContext(ctx, upsertActiveEffect,
		arg.ID,
		arg.EffectID,
		arg.TargetType,
		arg.TargetID,
		arg.StartedAt,
		arg.Volatile,
	)
	return err
}
