// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: effects.sql

package sqlite

import (
	"context"
	"time"
)

const clearEffectIcon = `-- name: ClearEffectIcon :exec
UPDATE effects SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearEffectIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearEffectIcon, id)
	return err
}

const clearEffectNativeName = `-- name: ClearEffectNativeName :exec
UPDATE effects SET native_name = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearEffectNativeName(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearEffectNativeName, id)
	return err
}

const createEffect = `-- name: CreateEffect :exec
INSERT INTO effects (id, name, icon, kind, native_name, loop, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEffectParams struct {
	ID         string
	Name       string
	Icon       *string
	Kind       string
	NativeName *string
	Loop       int64
	CreatedBy  *string
}

func (q *Queries) CreateEffect(ctx context.Context, arg CreateEffectParams) error {
	_, err := q.db.ExecContext(ctx, createEffect,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Kind,
		arg.NativeName,
		arg.Loop,
		arg.CreatedBy,
	)
	return err
}

const createEffectStep = `-- name: CreateEffectStep :exec
INSERT INTO effect_steps (id, effect_id, step_index, kind, config)
VALUES (?, ?, ?, ?, ?)
`

type CreateEffectStepParams struct {
	ID        string
	EffectID  string
	StepIndex int64
	Kind      string
	Config    string
}

func (q *Queries) CreateEffectStep(ctx context.Context, arg CreateEffectStepParams) error {
	_, err := q.db.ExecContext(ctx, createEffectStep,
		arg.ID,
		arg.EffectID,
		arg.StepIndex,
		arg.Kind,
		arg.Config,
	)
	return err
}

const deleteActiveEffect = `-- name: DeleteActiveEffect :exec
DELETE FROM active_effects WHERE id = ?
`

func (q *Queries) DeleteActiveEffect(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteActiveEffect, id)
	return err
}

const deleteEffect = `-- name: DeleteEffect :exec
DELETE FROM effects WHERE id = ?
`

func (q *Queries) DeleteEffect(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEffect, id)
	return err
}

const deleteEffectStepsByEffect = `-- name: DeleteEffectStepsByEffect :exec
DELETE FROM effect_steps WHERE effect_id = ?
`

func (q *Queries) DeleteEffectStepsByEffect(ctx context.Context, effectID string) error {
	_, err := q.db.ExecContext(ctx, deleteEffectStepsByEffect, effectID)
	return err
}

const deleteVolatileActiveEffects = `-- name: DeleteVolatileActiveEffects :execrows
DELETE FROM active_effects WHERE volatile = 1
`

func (q *Queries) DeleteVolatileActiveEffects(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVolatileActiveEffects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveEffectByTarget = `-- name: GetActiveEffectByTarget :one
SELECT id, effect_id, target_type, target_id, started_at, volatile
FROM active_effects
WHERE target_type = ? AND target_id = ?
`

type GetActiveEffectByTargetParams struct {
	TargetType string
	TargetID   string
}

func (q *Queries) GetActiveEffectByTarget(ctx context.Context, arg GetActiveEffectByTargetParams) (ActiveEffect, error) {
	row := q.db.QueryRowContext(ctx, getActiveEffectByTarget, arg.TargetType, arg.TargetID)
	var i ActiveEffect
	err := row.Scan(
		&i.ID,
		&i.EffectID,
		&i.TargetType,
		&i.TargetID,
		&i.StartedAt,
		&i.Volatile,
	)
	return i, err
}

const getEffect = `-- name: GetEffect :one
SELECT e.id, e.name, e.icon, e.kind, e.native_name, e.loop,
       e.created_at, e.updated_at,
       u.id       AS creator_id,
       u.username AS creator_username,
       u.name     AS creator_name
FROM effects e
LEFT JOIN users u ON u.id = e.created_by
WHERE e.id = ?
`

type GetEffectRow struct {
	ID              string
	Name            string
	Icon            *string
	Kind            string
	NativeName      *string
	Loop            int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetEffect(ctx context.Context, id string) (GetEffectRow, error) {
	row := q.db.QueryRowContext(ctx, getEffect, id)
	var i GetEffectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Kind,
		&i.NativeName,
		&i.Loop,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listActiveEffects = `-- name: ListActiveEffects :many
SELECT id, effect_id, target_type, target_id, started_at, volatile
FROM active_effects
`

func (q *Queries) ListActiveEffects(ctx context.Context) ([]ActiveEffect, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveEffect
	for rows.Next() {
		var i ActiveEffect
		if err := rows.Scan(
			&i.ID,
			&i.EffectID,
			&i.TargetType,
			&i.TargetID,
			&i.StartedAt,
			&i.Volatile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectSteps = `-- name: ListEffectSteps :many
SELECT id, effect_id, step_index, kind, config
FROM effect_steps
WHERE effect_id = ?
ORDER BY step_index
`

func (q *Queries) ListEffectSteps(ctx context.Context, effectID string) ([]EffectStep, error) {
	rows, err := q.db.QueryContext(ctx, listEffectSteps, effectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EffectStep
	for rows.Next() {
		var i EffectStep
		if err := rows.Scan(
			&i.ID,
			&i.EffectID,
			&i.StepIndex,
			&i.Kind,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffects = `-- name: ListEffects :many
SELECT e.id, e.name, e.icon, e.kind, e.native_name, e.loop,
       e.created_at, e.updated_at,
       u.id       AS creator_id,
       u.username AS creator_username,
       u.name     AS creator_name
FROM effects e
LEFT JOIN users u ON u.id = e.created_by
`

type ListEffectsRow struct {
	ID              string
	Name            string
	Icon            *string
	Kind            string
	NativeName      *string
	Loop            int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListEffects(ctx context.Context) ([]ListEffectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectsRow
	for rows.Next() {
		var i ListEffectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Kind,
			&i.NativeName,
			&i.Loop,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEffect = `-- name: UpdateEffect :exec
UPDATE effects SET
    name        = COALESCE(?1,        name),
    icon        = COALESCE(?2,        icon),
    kind        = COALESCE(?3,        kind),
    native_name = COALESCE(?4, native_name),
    loop        = COALESCE(?5,        loop),
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?6
`

type UpdateEffectParams struct {
	Name       *string
	Icon       *string
	Kind       *string
	NativeName *string
	Loop       *int64
	ID         string
}

func (q *Queries) UpdateEffect(ctx context.Context, arg UpdateEffectParams) error {
	_, err := q.db.ExecContext(ctx, updateEffect,
		arg.Name,
		arg.Icon,
		arg.Kind,
		arg.NativeName,
		arg.Loop,
		arg.ID,
	)
	return err
}

const upsertActiveEffect = `-- name: UpsertActiveEffect :exec
INSERT INTO active_effects (id, effect_id, target_type, target_id, started_at, volatile)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(target_type, target_id) DO UPDATE SET
    effect_id  = excluded.effect_id,
    started_at = excluded.started_at,
    volatile   = excluded.volatile
`

type UpsertActiveEffectParams struct {
	ID         string
	EffectID   string
	TargetType string
	TargetID   string
	StartedAt  time.Time
	Volatile   int64
}

func (q *Queries) UpsertActiveEffect(ctx context.Context, arg UpsertActiveEffectParams) error {
	_, err := q.db.ExecContext(ctx, upsertActiveEffect,
		arg.ID,
		arg.EffectID,
		arg.TargetType,
		arg.TargetID,
		arg.StartedAt,
		arg.Volatile,
	)
	return err
}
