// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: floorplans.sql

package sqlite

import (
	"context"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const createFloorplanFurniture = `-- name: CreateFloorplanFurniture :exec
INSERT INTO floorplan_furniture (id, floorplan_id, kind, x, y, width, height, rotation, occluder)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type CreateFloorplanFurnitureParams struct {
	ID          string
	FloorplanID string
	Kind        string
	X           float64
	Y           float64
	Width       float64
	Height      float64
	Rotation    float64
	Occluder    bool
}

func (q *Queries) CreateFloorplanFurniture(ctx context.Context, arg CreateFloorplanFurnitureParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanFurniture,
		arg.ID,
		arg.FloorplanID,
		arg.Kind,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Rotation,
		arg.Occluder,
	)
	return err
}

const createFloorplanOpening = `-- name: CreateFloorplanOpening :exec
INSERT INTO floorplan_openings (id, floorplan_id, wall_id, t, width, kind)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateFloorplanOpeningParams struct {
	ID          string
	FloorplanID string
	WallID      string
	T           float64
	Width       float64
	Kind        string
}

func (q *Queries) CreateFloorplanOpening(ctx context.Context, arg CreateFloorplanOpeningParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanOpening,
		arg.ID,
		arg.FloorplanID,
		arg.WallID,
		arg.T,
		arg.Width,
		arg.Kind,
	)
	return err
}

const createFloorplanPlacement = `-- name: CreateFloorplanPlacement :exec
INSERT INTO floorplan_placements (floorplan_id, member_type, member_id, x, y)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateFloorplanPlacementParams struct {
	FloorplanID string
	MemberType  device.TargetType
	MemberID    string
	X           float64
	Y           float64
}

func (q *Queries) CreateFloorplanPlacement(ctx context.Context, arg CreateFloorplanPlacementParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanPlacement,
		arg.FloorplanID,
		arg.MemberType,
		arg.MemberID,
		arg.X,
		arg.Y,
	)
	return err
}

const createFloorplanRoom = `-- name: CreateFloorplanRoom :exec
INSERT INTO floorplan_rooms (id, floorplan_id, name, room_id, vertex_ids)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateFloorplanRoomParams struct {
	ID          string
	FloorplanID string
	Name        *string
	RoomID      *string
	VertexIds   string
}

func (q *Queries) CreateFloorplanRoom(ctx context.Context, arg CreateFloorplanRoomParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanRoom,
		arg.ID,
		arg.FloorplanID,
		arg.Name,
		arg.RoomID,
		arg.VertexIds,
	)
	return err
}

const createFloorplanVertex = `-- name: CreateFloorplanVertex :exec
INSERT INTO floorplan_vertices (id, floorplan_id, x, y)
VALUES (?1, ?2, ?3, ?4)
`

type CreateFloorplanVertexParams struct {
	ID          string
	FloorplanID string
	X           float64
	Y           float64
}

func (q *Queries) CreateFloorplanVertex(ctx context.Context, arg CreateFloorplanVertexParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanVertex,
		arg.ID,
		arg.FloorplanID,
		arg.X,
		arg.Y,
	)
	return err
}

const createFloorplanWall = `-- name: CreateFloorplanWall :exec
INSERT INTO floorplan_walls (id, floorplan_id, vertex_a, vertex_b, thickness, curve_x, curve_y)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type CreateFloorplanWallParams struct {
	ID          string
	FloorplanID string
	VertexA     string
	VertexB     string
	Thickness   float64
	CurveX      *float64
	CurveY      *float64
}

func (q *Queries) CreateFloorplanWall(ctx context.Context, arg CreateFloorplanWallParams) error {
	_, err := q.db.ExecContext(ctx, createFloorplanWall,
		arg.ID,
		arg.FloorplanID,
		arg.VertexA,
		arg.VertexB,
		arg.Thickness,
		arg.CurveX,
		arg.CurveY,
	)
	return err
}

const deleteFloorplanFurnitureByFloorplan = `-- name: DeleteFloorplanFurnitureByFloorplan :exec
DELETE FROM floorplan_furniture WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanFurnitureByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanFurnitureByFloorplan, floorplanID)
	return err
}

const deleteFloorplanOpeningsByFloorplan = `-- name: DeleteFloorplanOpeningsByFloorplan :exec
DELETE FROM floorplan_openings WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanOpeningsByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanOpeningsByFloorplan, floorplanID)
	return err
}

const deleteFloorplanPlacementsByFloorplan = `-- name: DeleteFloorplanPlacementsByFloorplan :exec
DELETE FROM floorplan_placements WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanPlacementsByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanPlacementsByFloorplan, floorplanID)
	return err
}

const deleteFloorplanPlacementsByMember = `-- name: DeleteFloorplanPlacementsByMember :exec
DELETE FROM floorplan_placements
WHERE member_type = ?1 AND member_id = ?2
`

type DeleteFloorplanPlacementsByMemberParams struct {
	MemberType device.TargetType
	MemberID   string
}

// DeleteFloorplanPlacementsByMember drops the map placement of a device or
// group being deleted. The runtime connection does not enforce foreign keys,
// so this sweep runs inside the DeleteDevice / DeleteGroup / BatchDeleteGroups
// transactions rather than relying on a cascade.
func (q *Queries) DeleteFloorplanPlacementsByMember(ctx context.Context, arg DeleteFloorplanPlacementsByMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanPlacementsByMember, arg.MemberType, arg.MemberID)
	return err
}

const deleteFloorplanRoomsByFloorplan = `-- name: DeleteFloorplanRoomsByFloorplan :exec
DELETE FROM floorplan_rooms WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanRoomsByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanRoomsByFloorplan, floorplanID)
	return err
}

const deleteFloorplanVerticesByFloorplan = `-- name: DeleteFloorplanVerticesByFloorplan :exec
DELETE FROM floorplan_vertices WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanVerticesByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanVerticesByFloorplan, floorplanID)
	return err
}

const deleteFloorplanWallsByFloorplan = `-- name: DeleteFloorplanWallsByFloorplan :exec
DELETE FROM floorplan_walls WHERE floorplan_id = ?1
`

func (q *Queries) DeleteFloorplanWallsByFloorplan(ctx context.Context, floorplanID string) error {
	_, err := q.db.ExecContext(ctx, deleteFloorplanWallsByFloorplan, floorplanID)
	return err
}

const getFloorplan = `-- name: GetFloorplan :one

SELECT id, name, created_at, updated_at
FROM floorplans
ORDER BY created_at
LIMIT 1
`

// A floorplan owns five child tables: floorplan_vertices, floorplan_walls,
// floorplan_openings, floorplan_rooms, floorplan_placements. GetFloorplanGraph
// is composed in Go from these queries; ReplaceFloorplan swaps the whole plan
// inside one tx. vertex_ids is a JSON TEXT array; the Go wrapper marshals it
// before hitting these queries and unmarshals on read.
func (q *Queries) GetFloorplan(ctx context.Context) (Floorplan, error) {
	row := q.db.QueryRowContext(ctx, getFloorplan)
	var i Floorplan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFloorplanFurniture = `-- name: ListFloorplanFurniture :many
SELECT id, floorplan_id, kind, x, y, width, height, rotation, occluder
FROM floorplan_furniture
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanFurniture(ctx context.Context, floorplanID string) ([]FloorplanFurniture, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanFurniture, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanFurniture
	for rows.Next() {
		var i FloorplanFurniture
		if err := rows.Scan(
			&i.ID,
			&i.FloorplanID,
			&i.Kind,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Rotation,
			&i.Occluder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorplanOpenings = `-- name: ListFloorplanOpenings :many
SELECT id, floorplan_id, wall_id, t, width, kind
FROM floorplan_openings
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanOpenings(ctx context.Context, floorplanID string) ([]FloorplanOpening, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanOpenings, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanOpening
	for rows.Next() {
		var i FloorplanOpening
		if err := rows.Scan(
			&i.ID,
			&i.FloorplanID,
			&i.WallID,
			&i.T,
			&i.Width,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorplanPlacements = `-- name: ListFloorplanPlacements :many
SELECT floorplan_id, member_type, member_id, x, y
FROM floorplan_placements
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanPlacements(ctx context.Context, floorplanID string) ([]FloorplanPlacement, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanPlacements, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanPlacement
	for rows.Next() {
		var i FloorplanPlacement
		if err := rows.Scan(
			&i.FloorplanID,
			&i.MemberType,
			&i.MemberID,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorplanRooms = `-- name: ListFloorplanRooms :many
SELECT id, floorplan_id, name, room_id, vertex_ids
FROM floorplan_rooms
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanRooms(ctx context.Context, floorplanID string) ([]FloorplanRoom, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanRooms, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanRoom
	for rows.Next() {
		var i FloorplanRoom
		if err := rows.Scan(
			&i.ID,
			&i.FloorplanID,
			&i.Name,
			&i.RoomID,
			&i.VertexIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorplanVertices = `-- name: ListFloorplanVertices :many
SELECT id, floorplan_id, x, y
FROM floorplan_vertices
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanVertices(ctx context.Context, floorplanID string) ([]FloorplanVertex, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanVertices, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanVertex
	for rows.Next() {
		var i FloorplanVertex
		if err := rows.Scan(
			&i.ID,
			&i.FloorplanID,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorplanWalls = `-- name: ListFloorplanWalls :many
SELECT id, floorplan_id, vertex_a, vertex_b, thickness, curve_x, curve_y
FROM floorplan_walls
WHERE floorplan_id = ?1
`

func (q *Queries) ListFloorplanWalls(ctx context.Context, floorplanID string) ([]FloorplanWall, error) {
	rows, err := q.db.QueryContext(ctx, listFloorplanWalls, floorplanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorplanWall
	for rows.Next() {
		var i FloorplanWall
		if err := rows.Scan(
			&i.ID,
			&i.FloorplanID,
			&i.VertexA,
			&i.VertexB,
			&i.Thickness,
			&i.CurveX,
			&i.CurveY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkFloorplanRoomsByRoom = `-- name: UnlinkFloorplanRoomsByRoom :exec
UPDATE floorplan_rooms
SET name    = COALESCE(name, (SELECT rooms.name FROM rooms WHERE rooms.id = ?1)),
    room_id = NULL
WHERE room_id = ?1
`

// UnlinkFloorplanRoomsByRoom clears the Hive-room link on the faces that point
// at a room being deleted. COALESCE copies the room's name into faces that have
// no loose label yet, so the label survives the deletion; runs inside the
// DeleteRoom / BatchDeleteRooms transactions before the rooms row goes away.
func (q *Queries) UnlinkFloorplanRoomsByRoom(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, unlinkFloorplanRoomsByRoom, roomID)
	return err
}

const upsertFloorplan = `-- name: UpsertFloorplan :exec
INSERT INTO floorplans (id, name)
VALUES (?1, ?2)
ON CONFLICT(id) DO UPDATE SET
    name       = excluded.name,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertFloorplanParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertFloorplan(ctx context.Context, arg UpsertFloorplanParams) error {
	_, err := q.db.ExecContext(ctx, upsertFloorplan, arg.ID, arg.Name)
	return err
}
