// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: group_tags.sql

package sqlite

import (
	"context"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const deleteGroupTags = `-- name: DeleteGroupTags :exec
DELETE FROM group_tags WHERE group_id = ?
`

func (q *Queries) DeleteGroupTags(ctx context.Context, groupID string) error {
	_, err := q.db.ExecContext(ctx, deleteGroupTags, groupID)
	return err
}

const insertGroupTag = `-- name: InsertGroupTag :exec
INSERT OR IGNORE INTO group_tags (group_id, tag) VALUES (?, ?)
`

type InsertGroupTagParams struct {
	GroupID string
	Tag     device.GroupTag
}

func (q *Queries) InsertGroupTag(ctx context.Context, arg InsertGroupTagParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupTag, arg.GroupID, arg.Tag)
	return err
}

const listAllGroupTags = `-- name: ListAllGroupTags :many
SELECT group_id, tag FROM group_tags
`

func (q *Queries) ListAllGroupTags(ctx context.Context) ([]GroupTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllGroupTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTag
	for rows.Next() {
		var i GroupTag
		if err := rows.Scan(&i.GroupID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupTags = `-- name: ListGroupTags :many
SELECT tag FROM group_tags WHERE group_id = ?
`

func (q *Queries) ListGroupTags(ctx context.Context, groupID string) ([]device.GroupTag, error) {
	rows, err := q.db.QueryContext(ctx, listGroupTags, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []device.GroupTag
	for rows.Next() {
		var tag device.GroupTag
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
