// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: groups.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (id, group_id, member_type, member_id)
VALUES (?, ?, ?, ?)
`

type AddGroupMemberParams struct {
	ID         string
	GroupID    string
	MemberType device.GroupMemberType
	MemberID   string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember,
		arg.ID,
		arg.GroupID,
		arg.MemberType,
		arg.MemberID,
	)
	return err
}

const addGroupMemberIfMissing = `-- name: AddGroupMemberIfMissing :execrows
INSERT OR IGNORE INTO group_members (id, group_id, member_type, member_id)
VALUES (?, ?, ?, ?)
`

type AddGroupMemberIfMissingParams struct {
	ID         string
	GroupID    string
	MemberType device.GroupMemberType
	MemberID   string
}

func (q *Queries) AddGroupMemberIfMissing(ctx context.Context, arg AddGroupMemberIfMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addGroupMemberIfMissing,
		arg.ID,
		arg.GroupID,
		arg.MemberType,
		arg.MemberID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const batchDeleteGroups = `-- name: BatchDeleteGroups :execrows
DELETE FROM groups
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) BatchDeleteGroups(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteGroups, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearGroupIcon = `-- name: ClearGroupIcon :exec
UPDATE groups SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearGroupIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearGroupIcon, id)
	return err
}

const createGroup = `-- name: CreateGroup :exec

INSERT INTO groups (id, name, created_by) VALUES (?, ?, ?)
`

type CreateGroupParams struct {
	ID        string
	Name      string
	CreatedBy *string
}

// Same join shape as rooms; member table is group_members with typed member_type.
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ID, arg.Name, arg.CreatedBy)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.name, g.icon, g.created_at, g.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM groups g
LEFT JOIN users u ON u.id = g.created_by
WHERE g.id = ?
`

type GetGroupRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetGroup(ctx context.Context, id string) (GetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listAllGroupMemberships = `-- name: ListAllGroupMemberships :many
SELECT id, group_id, member_type, member_id FROM group_members
`

func (q *Queries) ListAllGroupMemberships(ctx context.Context) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listAllGroupMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.MemberType,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT id, group_id, member_type, member_id
FROM group_members
WHERE group_id = ?
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.MemberType,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.icon, g.created_at, g.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM groups g
LEFT JOIN users u ON u.id = g.created_by
`

type ListGroupsRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsContainingMember = `-- name: ListGroupsContainingMember :many
SELECT g.id, g.name, g.icon, g.created_at, g.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM groups g
INNER JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN users u ON u.id = g.created_by
WHERE gm.member_type = ? AND gm.member_id = ?
`

type ListGroupsContainingMemberParams struct {
	MemberType device.GroupMemberType
	MemberID   string
}

type ListGroupsContainingMemberRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListGroupsContainingMember(ctx context.Context, arg ListGroupsContainingMemberParams) ([]ListGroupsContainingMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsContainingMember, arg.MemberType, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsContainingMemberRow
	for rows.Next() {
		var i ListGroupsContainingMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE id = ?
`

func (q *Queries) RemoveGroupMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, id)
	return err
}

const removeGroupMembersByRoom = `-- name: RemoveGroupMembersByRoom :exec
DELETE FROM group_members WHERE member_type = 'room' AND member_id = ?
`

// Cleanup of dangling polymorphic room references when a room is deleted.
// group_members.member_id is polymorphic so no FK; mirror the same intent.
func (q *Queries) RemoveGroupMembersByRoom(ctx context.Context, memberID string) error {
	_, err := q.db.ExecContext(ctx, removeGroupMembersByRoom, memberID)
	return err
}

const updateGroupIcon = `-- name: UpdateGroupIcon :exec
UPDATE groups SET icon = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateGroupIconParams struct {
	Icon *string
	ID   string
}

func (q *Queries) UpdateGroupIcon(ctx context.Context, arg UpdateGroupIconParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupIcon, arg.Icon, arg.ID)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE groups SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateGroupNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupName, arg.Name, arg.ID)
	return err
}
