// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: guests.sql

package sqlite

import (
	"context"
	"time"
)

const batchDeleteGuests = `-- name: BatchDeleteGuests :many
DELETE FROM guests
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
RETURNING id
`

func (q *Queries) BatchDeleteGuests(ctx context.Context, idsJson string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, batchDeleteGuests, idsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGuest = `-- name: CreateGuest :exec
INSERT INTO guests (id, name, normalized_name, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateGuestParams struct {
	ID             string
	Name           string
	NormalizedName string
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) error {
	_, err := q.db.ExecContext(ctx, createGuest,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredGuestByNormalizedName = `-- name: DeleteExpiredGuestByNormalizedName :exec
DELETE FROM guests
WHERE normalized_name = ?1
  AND expires_at <= ?2
`

type DeleteExpiredGuestByNormalizedNameParams struct {
	NormalizedName string
	Now            time.Time
}

func (q *Queries) DeleteExpiredGuestByNormalizedName(ctx context.Context, arg DeleteExpiredGuestByNormalizedNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredGuestByNormalizedName, arg.NormalizedName, arg.Now)
	return err
}

const deleteExpiredGuests = `-- name: DeleteExpiredGuests :many
DELETE FROM guests
WHERE expires_at <= ?
RETURNING id
`

func (q *Queries) DeleteExpiredGuests(ctx context.Context, expiresAt time.Time) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredGuests, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGuest = `-- name: DeleteGuest :execrows
DELETE FROM guests WHERE id = ?
`

func (q *Queries) DeleteGuest(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGuest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveGuestByID = `-- name: GetActiveGuestByID :one
SELECT id, name, normalized_name, expires_at, created_at
FROM guests
WHERE id = ?1
  AND expires_at > ?2
`

type GetActiveGuestByIDParams struct {
	ID  string
	Now time.Time
}

func (q *Queries) GetActiveGuestByID(ctx context.Context, arg GetActiveGuestByIDParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getActiveGuestByID, arg.ID, arg.Now)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveGuestByNormalizedName = `-- name: GetActiveGuestByNormalizedName :one
SELECT id, name, normalized_name, expires_at, created_at
FROM guests
WHERE normalized_name = ?1
  AND expires_at > ?2
`

type GetActiveGuestByNormalizedNameParams struct {
	NormalizedName string
	Now            time.Time
}

func (q *Queries) GetActiveGuestByNormalizedName(ctx context.Context, arg GetActiveGuestByNormalizedNameParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getActiveGuestByNormalizedName, arg.NormalizedName, arg.Now)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT id, name, normalized_name, expires_at, created_at
FROM guests
WHERE id = ?
`

func (q *Queries) GetGuestByID(ctx context.Context, id string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByID, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGuests = `-- name: ListActiveGuests :many
SELECT id, name, normalized_name, expires_at, created_at
FROM guests
WHERE expires_at > ?
ORDER BY created_at ASC
`

func (q *Queries) ListActiveGuests(ctx context.Context, expiresAt time.Time) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGuests, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuestExpiresAt = `-- name: UpdateGuestExpiresAt :execrows
UPDATE guests
SET expires_at = ?1
WHERE id = ?2
`

type UpdateGuestExpiresAtParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) UpdateGuestExpiresAt(ctx context.Context, arg UpdateGuestExpiresAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuestExpiresAt, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
