// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: localized_names.sql

package sqlite

import (
	"context"
)

const deleteLocalizedNamesForSubject = `-- name: DeleteLocalizedNamesForSubject :exec
DELETE FROM localized_names WHERE entity_type = ? AND entity_id = ?
`

type DeleteLocalizedNamesForSubjectParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) DeleteLocalizedNamesForSubject(ctx context.Context, arg DeleteLocalizedNamesForSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteLocalizedNamesForSubject, arg.EntityType, arg.EntityID)
	return err
}

const getLocalizedNameSubject = `-- name: GetLocalizedNameSubject :one
SELECT entity_type, entity_id, source_language
FROM localized_name_subjects
WHERE entity_type = ? AND entity_id = ?
`

type GetLocalizedNameSubjectParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) GetLocalizedNameSubject(ctx context.Context, arg GetLocalizedNameSubjectParams) (LocalizedNameSubject, error) {
	row := q.db.QueryRowContext(ctx, getLocalizedNameSubject, arg.EntityType, arg.EntityID)
	var i LocalizedNameSubject
	err := row.Scan(&i.EntityType, &i.EntityID, &i.SourceLanguage)
	return i, err
}

const listLocalizedNameSubjects = `-- name: ListLocalizedNameSubjects :many
SELECT entity_type, entity_id, source_language
FROM localized_name_subjects
ORDER BY entity_type, entity_id
`

func (q *Queries) ListLocalizedNameSubjects(ctx context.Context) ([]LocalizedNameSubject, error) {
	rows, err := q.db.QueryContext(ctx, listLocalizedNameSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizedNameSubject
	for rows.Next() {
		var i LocalizedNameSubject
		if err := rows.Scan(&i.EntityType, &i.EntityID, &i.SourceLanguage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizedNames = `-- name: ListLocalizedNames :many
SELECT entity_type, entity_id, language, value
FROM localized_names
ORDER BY entity_type, entity_id, language
`

func (q *Queries) ListLocalizedNames(ctx context.Context) ([]LocalizedName, error) {
	rows, err := q.db.QueryContext(ctx, listLocalizedNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizedName
	for rows.Next() {
		var i LocalizedName
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.Language,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizedNamesForSubject = `-- name: ListLocalizedNamesForSubject :many
SELECT entity_type, entity_id, language, value
FROM localized_names
WHERE entity_type = ? AND entity_id = ?
ORDER BY language
`

type ListLocalizedNamesForSubjectParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) ListLocalizedNamesForSubject(ctx context.Context, arg ListLocalizedNamesForSubjectParams) ([]LocalizedName, error) {
	rows, err := q.db.QueryContext(ctx, listLocalizedNamesForSubject, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizedName
	for rows.Next() {
		var i LocalizedName
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.Language,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocalizedName = `-- name: UpsertLocalizedName :exec
INSERT INTO localized_names (entity_type, entity_id, language, value)
VALUES (?, ?, ?, ?)
ON CONFLICT(entity_type, entity_id, language) DO UPDATE SET value = excluded.value
`

type UpsertLocalizedNameParams struct {
	EntityType string
	EntityID   string
	Language   string
	Value      string
}

func (q *Queries) UpsertLocalizedName(ctx context.Context, arg UpsertLocalizedNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocalizedName,
		arg.EntityType,
		arg.EntityID,
		arg.Language,
		arg.Value,
	)
	return err
}
