// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: maintenance.sql

package sqlite

import (
	"context"
	"time"
)

const deleteMaintenanceAcknowledgementsByFingerprints = `-- name: DeleteMaintenanceAcknowledgementsByFingerprints :execrows
DELETE FROM maintenance_acknowledgements
WHERE task_key = ?1
  AND condition_fingerprint IN (
      SELECT value FROM json_each(CAST(?2 AS TEXT))
  )
`

type DeleteMaintenanceAcknowledgementsByFingerprintsParams struct {
	TaskKey          string
	FingerprintsJson string
}

func (q *Queries) DeleteMaintenanceAcknowledgementsByFingerprints(ctx context.Context, arg DeleteMaintenanceAcknowledgementsByFingerprintsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMaintenanceAcknowledgementsByFingerprints, arg.TaskKey, arg.FingerprintsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMaintenanceAcknowledgementsByTaskKey = `-- name: DeleteMaintenanceAcknowledgementsByTaskKey :execrows
DELETE FROM maintenance_acknowledgements WHERE task_key = ?
`

func (q *Queries) DeleteMaintenanceAcknowledgementsByTaskKey(ctx context.Context, taskKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMaintenanceAcknowledgementsByTaskKey, taskKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertMaintenanceAcknowledgement = `-- name: InsertMaintenanceAcknowledgement :exec
INSERT INTO maintenance_acknowledgements (
    task_key, condition_fingerprint, completed_at, completed_by
) VALUES (?, ?, ?, ?)
ON CONFLICT(task_key, condition_fingerprint) DO NOTHING
`

type InsertMaintenanceAcknowledgementParams struct {
	TaskKey              string
	ConditionFingerprint string
	CompletedAt          time.Time
	CompletedBy          *string
}

func (q *Queries) InsertMaintenanceAcknowledgement(ctx context.Context, arg InsertMaintenanceAcknowledgementParams) error {
	_, err := q.db.ExecContext(ctx, insertMaintenanceAcknowledgement,
		arg.TaskKey,
		arg.ConditionFingerprint,
		arg.CompletedAt,
		arg.CompletedBy,
	)
	return err
}

const listMaintenanceAcknowledgements = `-- name: ListMaintenanceAcknowledgements :many
SELECT task_key, condition_fingerprint, completed_at, completed_by
FROM maintenance_acknowledgements
ORDER BY task_key, condition_fingerprint
`

func (q *Queries) ListMaintenanceAcknowledgements(ctx context.Context) ([]MaintenanceAcknowledgement, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceAcknowledgements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceAcknowledgement
	for rows.Next() {
		var i MaintenanceAcknowledgement
		if err := rows.Scan(
			&i.TaskKey,
			&i.ConditionFingerprint,
			&i.CompletedAt,
			&i.CompletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
