// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

type ActiveEffect struct {
	ID         string
	EffectID   string
	TargetType string
	TargetID   string
	StartedAt  time.Time
	Volatile   int64
}

type ActivityEvent struct {
	ID             int64
	Type           string
	Timestamp      time.Time
	Message        string
	PayloadJson    string
	DeviceID       *string
	DeviceName     *string
	DeviceType     *string
	RoomID         *string
	RoomName       *string
	SceneID        *string
	SceneName      *string
	AutomationID   *string
	AutomationName *string
}

type Alarm struct {
	ID       int64
	AlarmID  string
	Severity string
	Kind     string
	Message  string
	Source   string
	RaisedAt time.Time
}

type Automation struct {
	ID          string
	Name        string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Icon        *string
	CreatedBy   *string
	LastFiredAt *time.Time
}

type AutomationEdge struct {
	AutomationID string
	FromNodeID   string
	ToNodeID     string
}

type AutomationNode struct {
	ID           string
	AutomationID string
	Type         string
	Config       string
	PositionX    float64
	PositionY    float64
}

type AutomationNodeState struct {
	AutomationID string
	NodeID       string
	Key          string
	Value        string
	UpdatedAt    time.Time
}

type Device struct {
	ID           device.DeviceID
	Name         *string
	FriendlyName string
	Source       device.Source
	Type         device.DeviceType
	Capabilities string
	Icon         *string
	Available    bool
	Removed      bool
	Disabled     bool
	LastSeen     *time.Time
	Seen         bool
}

type DeviceStateSample struct {
	ID         int64
	DeviceID   device.DeviceID
	Field      string
	Value      float64
	RecordedAt time.Time
}

type DeviceTag struct {
	DeviceID string
	Tag      string
}

type Effect struct {
	ID         string
	Name       string
	Icon       *string
	Kind       string
	NativeName *string
	Loop       int64
	CreatedBy  *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DurationMs int64
}

type EffectClip struct {
	ID              string
	TrackID         string
	StartMs         int64
	TransitionMinMs int64
	TransitionMaxMs int64
	Kind            string
	Config          string
}

type EffectTrack struct {
	ID         string
	EffectID   string
	TrackIndex int64
	Name       string
}

type Floorplan struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FloorplanOpening struct {
	ID          string
	FloorplanID string
	WallID      string
	T           float64
	Width       float64
	Kind        string
}

type FloorplanPlacement struct {
	FloorplanID string
	MemberType  device.TargetType
	MemberID    string
	X           float64
	Y           float64
}

type FloorplanRoom struct {
	ID          string
	FloorplanID string
	Name        *string
	RoomID      *string
	VertexIds   string
}

type FloorplanVertex struct {
	ID          string
	FloorplanID string
	X           float64
	Y           float64
}

type FloorplanWall struct {
	ID          string
	FloorplanID string
	VertexA     string
	VertexB     string
	Thickness   float64
	CurveX      *float64
	CurveY      *float64
}

type Group struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Icon      *string
	CreatedBy *string
}

type GroupMember struct {
	ID         string
	GroupID    string
	MemberType device.GroupMemberType
	MemberID   string
}

type GroupTag struct {
	GroupID string
	Tag     device.GroupTag
}

type Room struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Icon      *string
	CreatedBy *string
}

type RoomMember struct {
	ID         string
	RoomID     string
	MemberType device.RoomMemberType
	MemberID   string
}

type Scene struct {
	ID          string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Icon        *string
	CreatedBy   *string
	ActivatedAt *time.Time
}

type SceneAction struct {
	SceneID    string
	TargetType device.TargetType
	TargetID   string
	Expression *string
	Name       *string
}

type SceneDevicePayload struct {
	SceneID  string
	DeviceID device.DeviceID
	Payload  string
}

type SceneExpectedState struct {
	SceneID    string
	DeviceID   device.DeviceID
	OnState    *int64
	Brightness *int64
	ColorTemp  *int64
	ColorR     *int64
	ColorG     *int64
	ColorB     *int64
}

type Setting struct {
	Key   string
	Value string
}

type TuyaConfig struct {
	ID           int64
	AccessID     string
	AccessSecret string
	Region       string
	Enabled      bool
}

type TuyaDevice struct {
	DeviceID        string
	LocalKey        string
	ProtocolVersion string
	LanIp           string
	ProductID       string
}

type User struct {
	ID                 string
	Username           string
	Name               string
	PasswordHash       string
	CreatedAt          time.Time
	AvatarPath         *string
	Theme              string
	MustChangePassword bool
	TimeFormat         string
	TemperatureUnit    string
	TokenVersion       int64
}

type Zigbee2mqttConfig struct {
	ID       int64
	Broker   string
	Username string
	Password string
	UseWss   bool
	Enabled  bool
}
