// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

type ActivityEvent struct {
	ID             int64
	Type           string
	Timestamp      time.Time
	Message        string
	PayloadJson    string
	DeviceID       *string
	DeviceName     *string
	DeviceType     *string
	RoomID         *string
	RoomName       *string
	SceneID        *string
	SceneName      *string
	AutomationID   *string
	AutomationName *string
}

type Alarm struct {
	ID       int64
	AlarmID  string
	Severity string
	Kind     string
	Message  string
	Source   string
	RaisedAt time.Time
}

type Automation struct {
	ID          string
	Name        string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Icon        *string
	CreatedBy   *string
	LastFiredAt *time.Time
}

type AutomationEdge struct {
	ID           string
	AutomationID string
	FromNodeID   string
	ToNodeID     string
}

type AutomationNode struct {
	ID           string
	AutomationID string
	Type         string
	Config       string
	PositionX    float64
	PositionY    float64
}

type Device struct {
	ID           device.DeviceID
	Name         string
	Source       device.Source
	Type         device.DeviceType
	Available    bool
	Removed      bool
	LastSeen     *time.Time
	Capabilities string
}

type DeviceStateSample struct {
	ID         int64
	DeviceID   device.DeviceID
	Field      string
	Value      float64
	RecordedAt time.Time
}

type Group struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Icon      *string
	CreatedBy *string
}

type GroupMember struct {
	ID         string
	GroupID    string
	MemberType device.GroupMemberType
	MemberID   string
}

type MqttConfig struct {
	ID       int64
	Broker   string
	Username string
	Password string
	UseWss   bool
}

type Room struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Icon      *string
	CreatedBy *string
}

type RoomDevice struct {
	ID       string
	RoomID   string
	DeviceID string
}

type Scene struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Icon      *string
	CreatedBy *string
}

type SceneAction struct {
	ID         string
	SceneID    string
	TargetID   string
	TargetType device.TargetType
}

type SceneDevicePayload struct {
	SceneID  string
	DeviceID device.DeviceID
	Payload  string
}

type Setting struct {
	Key   string
	Value string
}

type User struct {
	ID           string
	Username     string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	AvatarPath   *string
	Theme        string
}

type ZigbeeDevice struct {
	DeviceID     device.DeviceID
	IeeeAddress  string
	FriendlyName string
}
