// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: mqtt_config.sql

package sqlite

import (
	"context"
)

const getMQTTConfig = `-- name: GetMQTTConfig :one
SELECT broker, username, password, use_wss
FROM mqtt_config
WHERE id = 1
`

type GetMQTTConfigRow struct {
	Broker   string
	Username string
	Password string
	UseWss   bool
}

func (q *Queries) GetMQTTConfig(ctx context.Context) (GetMQTTConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getMQTTConfig)
	var i GetMQTTConfigRow
	err := row.Scan(
		&i.Broker,
		&i.Username,
		&i.Password,
		&i.UseWss,
	)
	return i, err
}

const upsertMQTTConfig = `-- name: UpsertMQTTConfig :exec
INSERT INTO mqtt_config (id, broker, username, password, use_wss)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    broker   = excluded.broker,
    username = excluded.username,
    password = excluded.password,
    use_wss  = excluded.use_wss
`

type UpsertMQTTConfigParams struct {
	Broker   string
	Username string
	Password string
	UseWss   bool
}

func (q *Queries) UpsertMQTTConfig(ctx context.Context, arg UpsertMQTTConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertMQTTConfig,
		arg.Broker,
		arg.Username,
		arg.Password,
		arg.UseWss,
	)
	return err
}
