// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: native_effect_observations.sql

package sqlite

import (
	"context"
)

const deleteNativeEffectObservation = `-- name: DeleteNativeEffectObservation :exec
DELETE FROM native_effect_observations
WHERE device_id = ? AND effect_name = ?
`

type DeleteNativeEffectObservationParams struct {
	DeviceID   string
	EffectName string
}

func (q *Queries) DeleteNativeEffectObservation(ctx context.Context, arg DeleteNativeEffectObservationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNativeEffectObservation, arg.DeviceID, arg.EffectName)
	return err
}

const getNativeEffectObservation = `-- name: GetNativeEffectObservation :one
SELECT device_id, effect_name, result, evidence_fingerprint, observed_at
FROM native_effect_observations
WHERE device_id = ? AND effect_name = ?
`

type GetNativeEffectObservationParams struct {
	DeviceID   string
	EffectName string
}

func (q *Queries) GetNativeEffectObservation(ctx context.Context, arg GetNativeEffectObservationParams) (NativeEffectObservation, error) {
	row := q.db.QueryRowContext(ctx, getNativeEffectObservation, arg.DeviceID, arg.EffectName)
	var i NativeEffectObservation
	err := row.Scan(
		&i.DeviceID,
		&i.EffectName,
		&i.Result,
		&i.EvidenceFingerprint,
		&i.ObservedAt,
	)
	return i, err
}

const listNativeEffectObservations = `-- name: ListNativeEffectObservations :many
SELECT device_id, effect_name, result, evidence_fingerprint, observed_at
FROM native_effect_observations
ORDER BY device_id, effect_name
`

func (q *Queries) ListNativeEffectObservations(ctx context.Context) ([]NativeEffectObservation, error) {
	rows, err := q.db.QueryContext(ctx, listNativeEffectObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NativeEffectObservation
	for rows.Next() {
		var i NativeEffectObservation
		if err := rows.Scan(
			&i.DeviceID,
			&i.EffectName,
			&i.Result,
			&i.EvidenceFingerprint,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNativeEffectObservation = `-- name: UpsertNativeEffectObservation :one
INSERT INTO native_effect_observations (
    device_id, effect_name, result, evidence_fingerprint
) VALUES (?, ?, ?, ?)
ON CONFLICT(device_id, effect_name) DO UPDATE SET
    result = excluded.result,
    evidence_fingerprint = excluded.evidence_fingerprint,
    observed_at = CURRENT_TIMESTAMP
WHERE native_effect_observations.result != excluded.result
   OR native_effect_observations.evidence_fingerprint != excluded.evidence_fingerprint
RETURNING device_id, effect_name, result, evidence_fingerprint, observed_at
`

type UpsertNativeEffectObservationParams struct {
	DeviceID            string
	EffectName          string
	Result              string
	EvidenceFingerprint string
}

func (q *Queries) UpsertNativeEffectObservation(ctx context.Context, arg UpsertNativeEffectObservationParams) (NativeEffectObservation, error) {
	row := q.db.QueryRowContext(ctx, upsertNativeEffectObservation,
		arg.DeviceID,
		arg.EffectName,
		arg.Result,
		arg.EvidenceFingerprint,
	)
	var i NativeEffectObservation
	err := row.Scan(
		&i.DeviceID,
		&i.EffectName,
		&i.Result,
		&i.EvidenceFingerprint,
		&i.ObservedAt,
	)
	return i, err
}
