// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: network_topology.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const deleteNetworkTopology = `-- name: DeleteNetworkTopology :exec
DELETE FROM network_topology_snapshots WHERE provider = ?
`

func (q *Queries) DeleteNetworkTopology(ctx context.Context, provider device.Source) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkTopology, provider)
	return err
}

const getNetworkTopology = `-- name: GetNetworkTopology :one
SELECT provider, nodes, links, scanned_at
FROM network_topology_snapshots
WHERE provider = ?
`

func (q *Queries) GetNetworkTopology(ctx context.Context, provider device.Source) (NetworkTopologySnapshot, error) {
	row := q.db.QueryRowContext(ctx, getNetworkTopology, provider)
	var i NetworkTopologySnapshot
	err := row.Scan(
		&i.Provider,
		&i.Nodes,
		&i.Links,
		&i.ScannedAt,
	)
	return i, err
}

const listNetworkTopologies = `-- name: ListNetworkTopologies :many
SELECT provider, nodes, links, scanned_at
FROM network_topology_snapshots
ORDER BY provider
`

func (q *Queries) ListNetworkTopologies(ctx context.Context) ([]NetworkTopologySnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listNetworkTopologies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NetworkTopologySnapshot
	for rows.Next() {
		var i NetworkTopologySnapshot
		if err := rows.Scan(
			&i.Provider,
			&i.Nodes,
			&i.Links,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNetworkTopology = `-- name: UpsertNetworkTopology :exec
INSERT INTO network_topology_snapshots (provider, nodes, links, scanned_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(provider) DO UPDATE SET
    nodes      = excluded.nodes,
    links      = excluded.links,
    scanned_at = excluded.scanned_at
`

type UpsertNetworkTopologyParams struct {
	Provider  device.Source
	Nodes     string
	Links     string
	ScannedAt time.Time
}

func (q *Queries) UpsertNetworkTopology(ctx context.Context, arg UpsertNetworkTopologyParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkTopology,
		arg.Provider,
		arg.Nodes,
		arg.Links,
		arg.ScannedAt,
	)
	return err
}
