// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AddGroupMemberIfMissing(ctx context.Context, arg AddGroupMemberIfMissingParams) (int64, error)
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	AddRoomMemberIfMissing(ctx context.Context, arg AddRoomMemberIfMissingParams) (int64, error)
	BatchDeleteAlarmsByAlarmIDs(ctx context.Context, alarmIdsJson string) (int64, error)
	BatchDeleteAutomations(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteEffects(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteGroups(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteRooms(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteScenes(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteUsers(ctx context.Context, idsJson string) (int64, error)
	// Invalidates every JWT previously issued for this user by incrementing the
	// token_version column. The auth middleware refuses tokens whose embedded
	// version no longer matches the row, so existing sessions are revoked the
	// next time they hit the API. Bumped automatically on password change /
	// reset, and exposed via forceLogoutAllSessions for explicit revocation.
	BumpUserTokenVersion(ctx context.Context, id string) error
	ClearAutomationIcon(ctx context.Context, id string) error
	ClearDeviceDisplayBrightness(ctx context.Context, id device.DeviceID) error
	ClearDeviceDisplayColor(ctx context.Context, id device.DeviceID) error
	ClearDeviceIcon(ctx context.Context, id device.DeviceID) error
	ClearEffectIcon(ctx context.Context, id string) error
	ClearEffectNativeName(ctx context.Context, id string) error
	ClearGroupIcon(ctx context.Context, id string) error
	ClearRoomIcon(ctx context.Context, id string) error
	ClearSceneActivatedAt(ctx context.Context, id string) error
	ClearSceneIcon(ctx context.Context, id string) error
	ClearUserAvatar(ctx context.Context, id string) error
	// Sets a fresh password hash and clears the must_change_password flag in one
	// statement. The WHERE clause guards against use outside the forced-change
	// flow: only rows where the flag is currently set will be updated.
	CompleteFirstPasswordChange(ctx context.Context, arg CompleteFirstPasswordChangeParams) (int64, error)
	CountAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Automations own three related tables: automations, automation_nodes,
	// automation_edges. GetAutomationGraph is composed in Go from three sqlc
	// queries since sqlc's SQLite parser doesn't support data-modifying CTEs.
	CreateAutomation(ctx context.Context, arg CreateAutomationParams) error
	CreateAutomationEdge(ctx context.Context, arg CreateAutomationEdgeParams) error
	CreateAutomationNode(ctx context.Context, arg CreateAutomationNodeParams) error
	// Capabilities is stored as a JSON TEXT blob; the Go wrapper marshals it
	// before hitting these queries and unmarshals on read.
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateEffect(ctx context.Context, arg CreateEffectParams) error
	CreateEffectClip(ctx context.Context, arg CreateEffectClipParams) error
	CreateEffectTrack(ctx context.Context, arg CreateEffectTrackParams) error
	CreateFloorplanDoorBinding(ctx context.Context, arg CreateFloorplanDoorBindingParams) error
	CreateFloorplanFurniture(ctx context.Context, arg CreateFloorplanFurnitureParams) error
	CreateFloorplanOpening(ctx context.Context, arg CreateFloorplanOpeningParams) error
	CreateFloorplanPlacement(ctx context.Context, arg CreateFloorplanPlacementParams) error
	CreateFloorplanRoom(ctx context.Context, arg CreateFloorplanRoomParams) error
	CreateFloorplanVertex(ctx context.Context, arg CreateFloorplanVertexParams) error
	CreateFloorplanWall(ctx context.Context, arg CreateFloorplanWallParams) error
	// Same join shape as rooms; member table is group_members with typed member_type.
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	// Rooms share the same read-shape with scenes/groups/automations: the row is
	// joined against users to attach optional creator attribution, so each :one /
	// :many SELECT returns the room columns plus three nullable creator columns.
	//
	// Partial updates use the COALESCE(sqlc.narg, col) gate pattern: nil means
	// "leave alone". The nullable `icon` column needs a dedicated ClearRoomIcon
	// because COALESCE can't distinguish "leave alone" from "set to NULL".
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	CreateScene(ctx context.Context, arg CreateSceneParams) error
	CreateSceneAction(ctx context.Context, arg CreateSceneActionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteActiveEffectByTarget(ctx context.Context, arg DeleteActiveEffectByTargetParams) error
	DeleteAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error)
	DeleteAutomation(ctx context.Context, id string) error
	DeleteAutomationEdgesByAutomation(ctx context.Context, automationID string) error
	DeleteAutomationNodeStateByAutomation(ctx context.Context, automationID string) error
	DeleteAutomationNodesByAutomation(ctx context.Context, automationID string) error
	DeleteDevice(ctx context.Context, id device.DeviceID) error
	DeleteEffect(ctx context.Context, id string) error
	DeleteEffectTracksByEffect(ctx context.Context, effectID string) error
	DeleteFloorplanDoorBindingsByDevice(ctx context.Context, deviceID string) error
	DeleteFloorplanDoorBindingsByFloorplan(ctx context.Context, floorplanID string) error
	DeleteFloorplanFurnitureByFloorplan(ctx context.Context, floorplanID string) error
	DeleteFloorplanOpeningsByFloorplan(ctx context.Context, floorplanID string) error
	DeleteFloorplanPlacementsByFloorplan(ctx context.Context, floorplanID string) error
	// DeleteFloorplanPlacementsByMember drops the map placement of a device or
	// group being deleted. The runtime connection does not enforce foreign keys,
	// so this sweep runs inside the DeleteDevice / DeleteGroup / BatchDeleteGroups
	// transactions rather than relying on a cascade.
	DeleteFloorplanPlacementsByMember(ctx context.Context, arg DeleteFloorplanPlacementsByMemberParams) error
	DeleteFloorplanRoomsByFloorplan(ctx context.Context, floorplanID string) error
	DeleteFloorplanVerticesByFloorplan(ctx context.Context, floorplanID string) error
	DeleteFloorplanWallsByFloorplan(ctx context.Context, floorplanID string) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteGroupTags(ctx context.Context, groupID string) error
	DeleteMaintenanceAcknowledgementsByFingerprints(ctx context.Context, arg DeleteMaintenanceAcknowledgementsByFingerprintsParams) (int64, error)
	DeleteMaintenanceAcknowledgementsByTaskKey(ctx context.Context, taskKey string) (int64, error)
	DeleteNetworkTopology(ctx context.Context, provider device.Source) error
	DeleteProviderGroupMembers(ctx context.Context, groupID string) error
	DeleteRoom(ctx context.Context, id string) error
	DeleteScene(ctx context.Context, id string) error
	DeleteSceneActionsByScene(ctx context.Context, sceneID string) error
	DeleteSceneDevicePayloadsByScene(ctx context.Context, sceneID string) error
	DeleteSceneDevicePayloadsNotIn(ctx context.Context, arg DeleteSceneDevicePayloadsNotInParams) (int64, error)
	DeleteSceneExpectedStatesByScene(ctx context.Context, sceneID string) error
	DeleteTuyaConfig(ctx context.Context) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVolatileActiveEffects(ctx context.Context) (int64, error)
	DeleteZigbee2MQTTConfig(ctx context.Context) error
	DeleteZigbeeDeviceMetadata(ctx context.Context, deviceID device.DeviceID) error
	GetAutomation(ctx context.Context, id string) (GetAutomationRow, error)
	// Per-node runtime state for stateful automation nodes (e.g. cycle_scenes
	// index). Generic key/value JSON store keyed by (automation_id, node_id, key).
	// Cascades on automation and node deletion, so graph replacement wipes state
	// automatically.
	GetAutomationNodeState(ctx context.Context, arg GetAutomationNodeStateParams) (string, error)
	GetDevice(ctx context.Context, id device.DeviceID) (GetDeviceRow, error)
	GetEffect(ctx context.Context, id string) (GetEffectRow, error)
	// A floorplan owns its graph, rooms, placements, furniture, and door bindings. GetFloorplanGraph
	// is composed in Go from these queries; ReplaceFloorplan swaps the whole plan
	// inside one tx. vertex_ids is a JSON TEXT array; the Go wrapper marshals it
	// before hitting these queries and unmarshals on read.
	GetFloorplan(ctx context.Context) (Floorplan, error)
	GetFloorplanDoorBindingByDevice(ctx context.Context, deviceID string) (FloorplanDoorBinding, error)
	GetGroup(ctx context.Context, id string) (GetGroupRow, error)
	GetGroupMemberGroupID(ctx context.Context, id string) (string, error)
	GetNetworkTopology(ctx context.Context, provider device.Source) (NetworkTopologySnapshot, error)
	GetRoom(ctx context.Context, id string) (GetRoomRow, error)
	GetRoomMemberRoomID(ctx context.Context, id string) (string, error)
	GetScene(ctx context.Context, id string) (GetSceneRow, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetTuyaConfig(ctx context.Context) (GetTuyaConfigRow, error)
	GetUserAvatarPath(ctx context.Context, id string) (*string, error)
	GetUserAvatarPathsByIDs(ctx context.Context, idsJson string) ([]GetUserAvatarPathsByIDsRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetZigbee2MQTTConfig(ctx context.Context) (GetZigbee2MQTTConfigRow, error)
	GetZigbeeDeviceMetadata(ctx context.Context, deviceID device.DeviceID) (ZigbeeDeviceMetadatum, error)
	// Activity event persistence. QueryActivityEvents is the only query in the
	// codebase with fully-dynamic filters, so it uses every gate trick we have:
	//
	//   - json_array_length + json_each: a single JSON-array param covers both
	//     "match all" (empty array) and "match listed values" without a combinatorial
	//     explosion of generated queries.
	//   - CAST(narg AS TEXT) IS NULL OR col = CAST(narg AS TEXT): optional filter
	//     on a nullable column. The CAST is there to pin the Go type to *string;
	//     without it sqlc emits interface{}.
	//   - COALESCE(narg, col): optional filter on a NOT NULL column (timestamp,
	//     id). Self-neutral when narg is NULL, since col >= col is always true.
	//   - IIF(lim > 0, lim, -1): single-query optional LIMIT; SQLite treats -1 as
	//     unbounded.
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (int64, error)
	// Alarms persistence. One row per raise; grouping by alarm_id happens in Go.
	// Deletion is by alarm_id, removing every row belonging to a logical alarm
	// in one shot. The user-facing identity is alarm_id, not the row id.
	InsertAlarm(ctx context.Context, arg InsertAlarmParams) (Alarm, error)
	InsertGroupTag(ctx context.Context, arg InsertGroupTagParams) error
	InsertMaintenanceAcknowledgement(ctx context.Context, arg InsertMaintenanceAcknowledgementParams) error
	InsertProviderGroupMember(ctx context.Context, arg InsertProviderGroupMemberParams) error
	InsertStateSample(ctx context.Context, arg InsertStateSampleParams) (int64, error)
	LatestStateSample(ctx context.Context, arg LatestStateSampleParams) (LatestStateSampleRow, error)
	ListActiveEffects(ctx context.Context) ([]ActiveEffect, error)
	ListActiveScenes(ctx context.Context) ([]ListActiveScenesRow, error)
	ListAlarms(ctx context.Context) ([]Alarm, error)
	ListAllGroupMemberships(ctx context.Context) ([]GroupMember, error)
	ListAllGroupTags(ctx context.Context) ([]GroupTag, error)
	ListAllSceneExpectedStates(ctx context.Context) ([]SceneExpectedState, error)
	ListAutomationEdges(ctx context.Context, automationID string) ([]AutomationEdge, error)
	ListAutomationNodeStateByAutomation(ctx context.Context, automationID string) ([]ListAutomationNodeStateByAutomationRow, error)
	ListAutomationNodes(ctx context.Context, automationID string) ([]AutomationNode, error)
	ListAutomations(ctx context.Context) ([]ListAutomationsRow, error)
	ListDevices(ctx context.Context) ([]ListDevicesRow, error)
	ListDevicesBySource(ctx context.Context, source device.Source) ([]ListDevicesBySourceRow, error)
	ListDisabledDeviceIDs(ctx context.Context) ([]device.DeviceID, error)
	ListEffectClips(ctx context.Context, trackID string) ([]EffectClip, error)
	ListEffectTracks(ctx context.Context, effectID string) ([]EffectTrack, error)
	ListEffects(ctx context.Context) ([]ListEffectsRow, error)
	ListEnabledAutomations(ctx context.Context) ([]ListEnabledAutomationsRow, error)
	ListFloorplanDoorBindings(ctx context.Context, floorplanID string) ([]FloorplanDoorBinding, error)
	ListFloorplanFurniture(ctx context.Context, floorplanID string) ([]FloorplanFurniture, error)
	ListFloorplanOpenings(ctx context.Context, floorplanID string) ([]FloorplanOpening, error)
	ListFloorplanPlacements(ctx context.Context, floorplanID string) ([]FloorplanPlacement, error)
	ListFloorplanRooms(ctx context.Context, floorplanID string) ([]FloorplanRoom, error)
	ListFloorplanVertices(ctx context.Context, floorplanID string) ([]FloorplanVertex, error)
	ListFloorplanWalls(ctx context.Context, floorplanID string) ([]FloorplanWall, error)
	ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error)
	ListGroupTags(ctx context.Context, groupID string) ([]device.GroupTag, error)
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	ListGroupsContainingMember(ctx context.Context, arg ListGroupsContainingMemberParams) ([]ListGroupsContainingMemberRow, error)
	ListMaintenanceAcknowledgements(ctx context.Context) ([]MaintenanceAcknowledgement, error)
	ListNetworkTopologies(ctx context.Context) ([]NetworkTopologySnapshot, error)
	ListProviderGroupMembers(ctx context.Context, provider string) ([]GroupMember, error)
	ListProviderGroups(ctx context.Context, provider string) ([]ListProviderGroupsRow, error)
	ListRoomMembers(ctx context.Context, roomID string) ([]RoomMember, error)
	ListRoomMemberships(ctx context.Context) ([]ListRoomMembershipsRow, error)
	ListRooms(ctx context.Context) ([]ListRoomsRow, error)
	ListRoomsContainingMember(ctx context.Context, arg ListRoomsContainingMemberParams) ([]ListRoomsContainingMemberRow, error)
	ListSceneActions(ctx context.Context, sceneID string) ([]SceneAction, error)
	ListSceneDevicePayloads(ctx context.Context, sceneID string) ([]SceneDevicePayload, error)
	ListSceneExpectedStates(ctx context.Context, sceneID string) ([]SceneExpectedState, error)
	ListScenes(ctx context.Context) ([]ListScenesRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListTuyaDevices(ctx context.Context) ([]TuyaDevice, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListZigbeeFirmwareCandidates(ctx context.Context) ([]ZigbeeDeviceMetadatum, error)
	ListZigbeeProviderGroupsForDevice(ctx context.Context, memberID string) ([]ListZigbeeProviderGroupsForDeviceRow, error)
	MarkDevicesSeen(ctx context.Context, idsJson string) (int64, error)
	MarkProviderGroupsRemovedExcept(ctx context.Context, arg MarkProviderGroupsRemovedExceptParams) error
	MergeZigbeeOTAStatus(ctx context.Context, arg MergeZigbeeOTAStatusParams) (device.DeviceID, error)
	PruneActivityEventsOlderThan(ctx context.Context, timestamp time.Time) (int64, error)
	PruneDeviceStateSamplesOlderThan(ctx context.Context, cutoff string) (int64, error)
	QueryActivityEvents(ctx context.Context, arg QueryActivityEventsParams) ([]ActivityEvent, error)
	QueryStateHistoryAnchors(ctx context.Context, arg QueryStateHistoryAnchorsParams) ([]QueryStateHistoryAnchorsRow, error)
	QueryStateHistoryNumericBucketed(ctx context.Context, arg QueryStateHistoryNumericBucketedParams) ([]QueryStateHistoryNumericBucketedRow, error)
	QueryStateHistoryRaw(ctx context.Context, arg QueryStateHistoryRawParams) ([]QueryStateHistoryRawRow, error)
	QueryStateHistoryStatefulBucketed(ctx context.Context, arg QueryStateHistoryStatefulBucketedParams) ([]QueryStateHistoryStatefulBucketedRow, error)
	RemoveGroupMember(ctx context.Context, id string) error
	// Cleanup of dangling polymorphic room references when a room is deleted.
	// group_members.member_id is polymorphic so no FK; mirror the same intent.
	RemoveGroupMembersByRoom(ctx context.Context, memberID string) error
	RemoveRoomMember(ctx context.Context, id string) error
	// Cleanup of dangling polymorphic group references when a group is deleted.
	// Mirrors group_members FK cascade for room-as-group-member; no FK because
	// member_id is polymorphic.
	RemoveRoomMembersByGroup(ctx context.Context, memberID string) error
	ResolveGroupIDByName(ctx context.Context, name *string) (string, error)
	ResolveRoomIDByName(ctx context.Context, name string) (string, error)
	SetAutomationNodeState(ctx context.Context, arg SetAutomationNodeStateParams) error
	SetDeviceDisabled(ctx context.Context, arg SetDeviceDisabledParams) error
	// The nullable icon and display_color columns need dedicated clear queries
	// because COALESCE can't distinguish "leave alone" from "set to NULL".
	// UpdateDevice deliberately skips both so MQTT-driven sync (UpsertDevice) and
	// re-sync don't overwrite what the user set.
	// The disabled flag, the name override and the seen flag are user-owned, so each
	// gets its own setter for the same reason the icon column does: UpdateDevice
	// overwrites every column it names, and the device-removal path calls it with an
	// otherwise zero-value struct. UpsertDevice preserves user-owned values and
	// reconciles role categories against the adapter-owned type and capabilities.
	SetDeviceName(ctx context.Context, arg SetDeviceNameParams) error
	SetDeviceRoles(ctx context.Context, arg SetDeviceRolesParams) error
	SetSceneActivatedAt(ctx context.Context, arg SetSceneActivatedAtParams) error
	SetUserMustChangePassword(ctx context.Context, arg SetUserMustChangePasswordParams) error
	// UnlinkFloorplanRoomsByRoom clears the Hive-room link on the faces that point
	// at a room being deleted. COALESCE copies the room's name into faces that have
	// no loose label yet, so the label survives the deletion; runs inside the
	// DeleteRoom / BatchDeleteRooms transactions before the rooms row goes away.
	UnlinkFloorplanRoomsByRoom(ctx context.Context, roomID string) error
	UpdateAutomationEnabled(ctx context.Context, arg UpdateAutomationEnabledParams) error
	// Partial update via COALESCE(narg, col) gate. Nil narg values leave their
	// column untouched. The nullable icon column can't be cleared through this
	// query; use ClearAutomationIcon for that. All args are named so sqlc's
	// SQLite emitter keeps a consistent indexing scheme (mixing named and bare
	// positional `?` produced off-by-one parameter indices in 1.31.0).
	UpdateAutomationFields(ctx context.Context, arg UpdateAutomationFieldsParams) error
	// Stamps when the automation most recently fired. updated_at is intentionally
	// NOT touched so the "last edited" semantics stay distinct from "last fired".
	UpdateAutomationLastFired(ctx context.Context, arg UpdateAutomationLastFiredParams) error
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateDeviceDisplayBrightness(ctx context.Context, arg UpdateDeviceDisplayBrightnessParams) error
	UpdateDeviceDisplayColor(ctx context.Context, arg UpdateDeviceDisplayColorParams) error
	UpdateDeviceIcon(ctx context.Context, arg UpdateDeviceIconParams) error
	UpdateEffect(ctx context.Context, arg UpdateEffectParams) error
	UpdateEffectDuration(ctx context.Context, arg UpdateEffectDurationParams) error
	UpdateGroupIcon(ctx context.Context, arg UpdateGroupIconParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error
	UpdateRoomIcon(ctx context.Context, arg UpdateRoomIconParams) error
	UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) error
	UpdateSceneIcon(ctx context.Context, arg UpdateSceneIconParams) error
	UpdateSceneName(ctx context.Context, arg UpdateSceneNameParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	// Partial update of mutable profile fields. Nil narg values leave their column
	// untouched. avatar_path can be set to a value here but cannot be cleared to
	// NULL; use ClearUserAvatar for that (COALESCE cannot distinguish "leave alone"
	// from "set to NULL"). theme is constrained by a CHECK in the migration.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertActiveEffect(ctx context.Context, arg UpsertActiveEffectParams) error
	// Refreshes every adapter-owned column, including the friendly name, and clears
	// the removed flag when a device reappears. The name column is the user's
	// override and is never touched here.
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertFloorplan(ctx context.Context, arg UpsertFloorplanParams) error
	UpsertNetworkTopology(ctx context.Context, arg UpsertNetworkTopologyParams) error
	UpsertProviderGroup(ctx context.Context, arg UpsertProviderGroupParams) error
	UpsertSceneDevicePayload(ctx context.Context, arg UpsertSceneDevicePayloadParams) error
	UpsertSceneExpectedState(ctx context.Context, arg UpsertSceneExpectedStateParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertTuyaConfig(ctx context.Context, arg UpsertTuyaConfigParams) error
	UpsertTuyaDevice(ctx context.Context, arg UpsertTuyaDeviceParams) error
	UpsertZigbee2MQTTConfig(ctx context.Context, arg UpsertZigbee2MQTTConfigParams) error
	UpsertZigbeeBridgeMetadata(ctx context.Context, arg UpsertZigbeeBridgeMetadataParams) (device.DeviceID, error)
}

var _ Querier = (*Queries)(nil)
