// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AddRoomDevice(ctx context.Context, arg AddRoomDeviceParams) error
	ClearAutomationIcon(ctx context.Context, id string) error
	ClearGroupIcon(ctx context.Context, id string) error
	ClearRoomIcon(ctx context.Context, id string) error
	ClearSceneIcon(ctx context.Context, id string) error
	CountUsers(ctx context.Context) (int64, error)
	// Automations own three related tables: automations, automation_nodes,
	// automation_edges. GetAutomationGraph is composed in Go from three sqlc
	// queries since sqlc's SQLite parser doesn't support data-modifying CTEs.
	CreateAutomation(ctx context.Context, arg CreateAutomationParams) error
	CreateAutomationEdge(ctx context.Context, arg CreateAutomationEdgeParams) error
	CreateAutomationNode(ctx context.Context, arg CreateAutomationNodeParams) error
	// Capabilities is stored as a JSON TEXT blob; the Go wrapper marshals it
	// before hitting these queries and unmarshals on read (with a legacy format
	// fallback preserved in mapper.go).
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	// Same join shape as rooms; member table is group_members with typed member_type.
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	// Rooms share the same read-shape with scenes/groups/automations: the row is
	// joined against users to attach optional creator attribution, so each :one /
	// :many SELECT returns the room columns plus three nullable creator columns.
	//
	// Partial updates use the COALESCE(sqlc.narg, col) gate pattern: nil means
	// "leave alone". The nullable `icon` column needs a dedicated ClearRoomIcon
	// because COALESCE can't distinguish "leave alone" from "set to NULL".
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	CreateScene(ctx context.Context, arg CreateSceneParams) error
	CreateSceneAction(ctx context.Context, arg CreateSceneActionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAutomation(ctx context.Context, id string) error
	DeleteAutomationEdge(ctx context.Context, id string) error
	DeleteAutomationNode(ctx context.Context, id string) error
	DeleteDevice(ctx context.Context, id device.DeviceID) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteRoom(ctx context.Context, id string) error
	DeleteScene(ctx context.Context, id string) error
	DeleteSceneAction(ctx context.Context, id string) error
	GetAutomation(ctx context.Context, id string) (GetAutomationRow, error)
	GetDevice(ctx context.Context, id device.DeviceID) (GetDeviceRow, error)
	GetGroup(ctx context.Context, id string) (GetGroupRow, error)
	GetMQTTConfig(ctx context.Context) (GetMQTTConfigRow, error)
	GetRoom(ctx context.Context, id string) (GetRoomRow, error)
	GetScene(ctx context.Context, id string) (GetSceneRow, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetZigbeeDeviceByFriendlyName(ctx context.Context, friendlyName string) (ZigbeeDevice, error)
	GetZigbeeDeviceByIEEEAddress(ctx context.Context, ieeeAddress string) (ZigbeeDevice, error)
	// Activity event persistence. QueryActivityEvents is the only query in the
	// codebase with fully-dynamic filters, so it uses every gate trick we have:
	//
	//   - json_array_length + json_each: a single JSON-array param covers both
	//     "match all" (empty array) and "match listed values" without a combinatorial
	//     explosion of generated queries.
	//   - CAST(narg AS TEXT) IS NULL OR col = CAST(narg AS TEXT): optional filter
	//     on a nullable column. The CAST is there to pin the Go type to *string;
	//     without it sqlc emits interface{}.
	//   - COALESCE(narg, col): optional filter on a NOT NULL column (timestamp,
	//     id). Self-neutral when narg is NULL, since col >= col is always true.
	//   - IIF(lim > 0, lim, -1): single-query optional LIMIT; SQLite treats -1 as
	//     unbounded.
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (int64, error)
	// Returns the auto-generated id; other fields echo the input.
	InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) (int64, error)
	ListAutomationEdges(ctx context.Context, automationID string) ([]AutomationEdge, error)
	ListAutomationNodes(ctx context.Context, automationID string) ([]AutomationNode, error)
	ListAutomations(ctx context.Context) ([]ListAutomationsRow, error)
	ListDevices(ctx context.Context) ([]ListDevicesRow, error)
	ListDevicesBySource(ctx context.Context, source device.Source) ([]ListDevicesBySourceRow, error)
	ListEnabledAutomations(ctx context.Context) ([]ListEnabledAutomationsRow, error)
	ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error)
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	ListGroupsContainingMember(ctx context.Context, arg ListGroupsContainingMemberParams) ([]ListGroupsContainingMemberRow, error)
	ListRoomDevices(ctx context.Context, roomID string) ([]RoomDevice, error)
	ListRooms(ctx context.Context) ([]ListRoomsRow, error)
	ListRoomsContainingDevice(ctx context.Context, deviceID string) ([]ListRoomsContainingDeviceRow, error)
	ListSceneActions(ctx context.Context, sceneID string) ([]ListSceneActionsRow, error)
	ListScenes(ctx context.Context) ([]ListScenesRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUsers(ctx context.Context) ([]User, error)
	PruneActivityEventsOlderThan(ctx context.Context, timestamp time.Time) (int64, error)
	QueryActivityEvents(ctx context.Context, arg QueryActivityEventsParams) ([]ActivityEvent, error)
	// Optional LIMIT collapsed into one query: SQLite treats LIMIT -1 as unbounded,
	// and IIF(lim > 0, lim, -1) turns a 0 sentinel into "no limit".
	QuerySensorHistory(ctx context.Context, arg QuerySensorHistoryParams) ([]SensorHistory, error)
	RegisterZigbeeDevice(ctx context.Context, arg RegisterZigbeeDeviceParams) error
	RemoveGroupMember(ctx context.Context, id string) error
	RemoveRoomDevice(ctx context.Context, id string) error
	RemoveRoomDeviceByRoomAndDevice(ctx context.Context, arg RemoveRoomDeviceByRoomAndDeviceParams) error
	UpdateAutomationEnabled(ctx context.Context, arg UpdateAutomationEnabledParams) error
	// Partial update via COALESCE(narg, col) gate. Nil narg values leave their
	// column untouched. The nullable icon column can't be cleared through this
	// query; use ClearAutomationIcon for that. All args are named so sqlc's
	// SQLite emitter keeps a consistent indexing scheme (mixing named and bare
	// positional `?` produced off-by-one parameter indices in 1.31.0).
	UpdateAutomationFields(ctx context.Context, arg UpdateAutomationFieldsParams) error
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateGroupIcon(ctx context.Context, arg UpdateGroupIconParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error
	UpdateRoomIcon(ctx context.Context, arg UpdateRoomIconParams) error
	UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) error
	UpdateSceneIcon(ctx context.Context, arg UpdateSceneIconParams) error
	UpdateSceneName(ctx context.Context, arg UpdateSceneNameParams) error
	// Clears the removed flag on conflict so re-discovered devices become active.
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertMQTTConfig(ctx context.Context, arg UpsertMQTTConfigParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertZigbeeDevice(ctx context.Context, arg UpsertZigbeeDeviceParams) error
}

var _ Querier = (*Queries)(nil)
