// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AddGroupMemberIfMissing(ctx context.Context, arg AddGroupMemberIfMissingParams) (int64, error)
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	AddRoomMemberIfMissing(ctx context.Context, arg AddRoomMemberIfMissingParams) (int64, error)
	BatchDeleteAlarmsByAlarmIDs(ctx context.Context, alarmIdsJson string) (int64, error)
	BatchDeleteAutomations(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteGroups(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteRooms(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteScenes(ctx context.Context, idsJson string) (int64, error)
	BatchDeleteUsers(ctx context.Context, idsJson string) (int64, error)
	ClearAutomationIcon(ctx context.Context, id string) error
	ClearEffectIcon(ctx context.Context, id string) error
	ClearEffectNativeName(ctx context.Context, id string) error
	ClearGroupIcon(ctx context.Context, id string) error
	ClearRoomIcon(ctx context.Context, id string) error
	ClearSceneActivatedAt(ctx context.Context, id string) error
	ClearSceneIcon(ctx context.Context, id string) error
	ClearUserAvatar(ctx context.Context, id string) error
	CountAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Automations own three related tables: automations, automation_nodes,
	// automation_edges. GetAutomationGraph is composed in Go from three sqlc
	// queries since sqlc's SQLite parser doesn't support data-modifying CTEs.
	CreateAutomation(ctx context.Context, arg CreateAutomationParams) error
	CreateAutomationEdge(ctx context.Context, arg CreateAutomationEdgeParams) error
	CreateAutomationNode(ctx context.Context, arg CreateAutomationNodeParams) error
	// Capabilities is stored as a JSON TEXT blob; the Go wrapper marshals it
	// before hitting these queries and unmarshals on read (with a legacy format
	// fallback preserved in mapper.go).
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateEffect(ctx context.Context, arg CreateEffectParams) error
	CreateEffectClip(ctx context.Context, arg CreateEffectClipParams) error
	CreateEffectTrack(ctx context.Context, arg CreateEffectTrackParams) error
	// Same join shape as rooms; member table is group_members with typed member_type.
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	// Rooms share the same read-shape with scenes/groups/automations: the row is
	// joined against users to attach optional creator attribution, so each :one /
	// :many SELECT returns the room columns plus three nullable creator columns.
	//
	// Partial updates use the COALESCE(sqlc.narg, col) gate pattern: nil means
	// "leave alone". The nullable `icon` column needs a dedicated ClearRoomIcon
	// because COALESCE can't distinguish "leave alone" from "set to NULL".
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	CreateScene(ctx context.Context, arg CreateSceneParams) error
	CreateSceneAction(ctx context.Context, arg CreateSceneActionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteActiveEffectByTarget(ctx context.Context, arg DeleteActiveEffectByTargetParams) error
	DeleteAlarmsByAlarmID(ctx context.Context, alarmID string) (int64, error)
	DeleteAutomation(ctx context.Context, id string) error
	DeleteAutomationEdgesByAutomation(ctx context.Context, automationID string) error
	DeleteAutomationNodesByAutomation(ctx context.Context, automationID string) error
	DeleteDevice(ctx context.Context, id device.DeviceID) error
	DeleteEffect(ctx context.Context, id string) error
	DeleteEffectTracksByEffect(ctx context.Context, effectID string) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteGroupTags(ctx context.Context, groupID string) error
	DeleteRoom(ctx context.Context, id string) error
	DeleteScene(ctx context.Context, id string) error
	DeleteSceneActionsByScene(ctx context.Context, sceneID string) error
	DeleteSceneDevicePayloadsByScene(ctx context.Context, sceneID string) error
	DeleteSceneDevicePayloadsNotIn(ctx context.Context, arg DeleteSceneDevicePayloadsNotInParams) (int64, error)
	DeleteSceneExpectedStatesByScene(ctx context.Context, sceneID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVolatileActiveEffects(ctx context.Context) (int64, error)
	GetAutomation(ctx context.Context, id string) (GetAutomationRow, error)
	GetDevice(ctx context.Context, id device.DeviceID) (GetDeviceRow, error)
	GetEffect(ctx context.Context, id string) (GetEffectRow, error)
	GetGroup(ctx context.Context, id string) (GetGroupRow, error)
	GetMQTTConfig(ctx context.Context) (GetMQTTConfigRow, error)
	GetRoom(ctx context.Context, id string) (GetRoomRow, error)
	GetScene(ctx context.Context, id string) (GetSceneRow, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetUserAvatarPath(ctx context.Context, id string) (*string, error)
	GetUserAvatarPathsByIDs(ctx context.Context, idsJson string) ([]GetUserAvatarPathsByIDsRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetZigbeeDeviceByFriendlyName(ctx context.Context, friendlyName string) (ZigbeeDevice, error)
	GetZigbeeDeviceByIEEEAddress(ctx context.Context, ieeeAddress string) (ZigbeeDevice, error)
	// Activity event persistence. QueryActivityEvents is the only query in the
	// codebase with fully-dynamic filters, so it uses every gate trick we have:
	//
	//   - json_array_length + json_each: a single JSON-array param covers both
	//     "match all" (empty array) and "match listed values" without a combinatorial
	//     explosion of generated queries.
	//   - CAST(narg AS TEXT) IS NULL OR col = CAST(narg AS TEXT): optional filter
	//     on a nullable column. The CAST is there to pin the Go type to *string;
	//     without it sqlc emits interface{}.
	//   - COALESCE(narg, col): optional filter on a NOT NULL column (timestamp,
	//     id). Self-neutral when narg is NULL, since col >= col is always true.
	//   - IIF(lim > 0, lim, -1): single-query optional LIMIT; SQLite treats -1 as
	//     unbounded.
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (int64, error)
	// Alarms persistence. One row per raise; grouping by alarm_id happens in Go.
	// Deletion is by alarm_id, removing every row belonging to a logical alarm
	// in one shot. The user-facing identity is alarm_id, not the row id.
	InsertAlarm(ctx context.Context, arg InsertAlarmParams) (Alarm, error)
	InsertGroupTag(ctx context.Context, arg InsertGroupTagParams) error
	InsertStateSample(ctx context.Context, arg InsertStateSampleParams) (int64, error)
	ListActiveEffects(ctx context.Context) ([]ActiveEffect, error)
	ListActiveScenes(ctx context.Context) ([]ListActiveScenesRow, error)
	ListAlarms(ctx context.Context) ([]Alarm, error)
	ListAllGroupMemberships(ctx context.Context) ([]GroupMember, error)
	ListAllGroupTags(ctx context.Context) ([]GroupTag, error)
	ListAllSceneExpectedStates(ctx context.Context) ([]SceneExpectedState, error)
	ListAutomationEdges(ctx context.Context, automationID string) ([]AutomationEdge, error)
	ListAutomationNodes(ctx context.Context, automationID string) ([]AutomationNode, error)
	ListAutomations(ctx context.Context) ([]ListAutomationsRow, error)
	ListDevices(ctx context.Context) ([]ListDevicesRow, error)
	ListDevicesBySource(ctx context.Context, source device.Source) ([]ListDevicesBySourceRow, error)
	ListEffectClips(ctx context.Context, trackID string) ([]EffectClip, error)
	ListEffectTracks(ctx context.Context, effectID string) ([]EffectTrack, error)
	ListEffects(ctx context.Context) ([]ListEffectsRow, error)
	ListEnabledAutomations(ctx context.Context) ([]ListEnabledAutomationsRow, error)
	ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error)
	ListGroupTags(ctx context.Context, groupID string) ([]device.GroupTag, error)
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	ListGroupsContainingMember(ctx context.Context, arg ListGroupsContainingMemberParams) ([]ListGroupsContainingMemberRow, error)
	ListRoomMembers(ctx context.Context, roomID string) ([]RoomMember, error)
	ListRoomMemberships(ctx context.Context) ([]ListRoomMembershipsRow, error)
	ListRooms(ctx context.Context) ([]ListRoomsRow, error)
	ListRoomsContainingMember(ctx context.Context, arg ListRoomsContainingMemberParams) ([]ListRoomsContainingMemberRow, error)
	ListSceneActions(ctx context.Context, sceneID string) ([]SceneAction, error)
	ListSceneDevicePayloads(ctx context.Context, sceneID string) ([]SceneDevicePayload, error)
	ListSceneExpectedStates(ctx context.Context, sceneID string) ([]SceneExpectedState, error)
	ListScenes(ctx context.Context) ([]ListScenesRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	PruneActivityEventsOlderThan(ctx context.Context, timestamp time.Time) (int64, error)
	PruneDeviceStateSamplesOlderThan(ctx context.Context, cutoff string) (int64, error)
	QueryActivityEvents(ctx context.Context, arg QueryActivityEventsParams) ([]ActivityEvent, error)
	// Groups samples into fixed-size time buckets. bucket_seconds must be > 0.
	// Per bucket returns AVG(value) and the Unix epoch of the earliest recorded_at
	// (bucket_start_unix). Returning an INTEGER epoch sidesteps the sqlite driver's
	// re-serialisation of TIMESTAMP aggregates. The substr(..., 1, 19) keeps
	// strftime happy across the stored RFC3339Nano form.
	QueryStateHistoryBucketed(ctx context.Context, arg QueryStateHistoryBucketedParams) ([]QueryStateHistoryBucketedRow, error)
	// device_ids_json and fields_json are JSON-array strings. An empty array in
	// fields_json matches every field. device_ids_json must be non-empty (callers
	// always pick sources explicitly). Time bounds are RFC3339Nano UTC strings so
	// lexicographic comparison matches chronological order.
	QueryStateHistoryRaw(ctx context.Context, arg QueryStateHistoryRawParams) ([]QueryStateHistoryRawRow, error)
	RegisterZigbeeDevice(ctx context.Context, arg RegisterZigbeeDeviceParams) error
	RemoveGroupMember(ctx context.Context, id string) error
	// Cleanup of dangling polymorphic room references when a room is deleted.
	// group_members.member_id is polymorphic so no FK; mirror the same intent.
	RemoveGroupMembersByRoom(ctx context.Context, memberID string) error
	RemoveRoomMember(ctx context.Context, id string) error
	// Cleanup of dangling polymorphic group references when a group is deleted.
	// Mirrors group_members FK cascade for room-as-group-member; no FK because
	// member_id is polymorphic.
	RemoveRoomMembersByGroup(ctx context.Context, memberID string) error
	SetSceneActivatedAt(ctx context.Context, arg SetSceneActivatedAtParams) error
	UpdateAutomationEnabled(ctx context.Context, arg UpdateAutomationEnabledParams) error
	// Partial update via COALESCE(narg, col) gate. Nil narg values leave their
	// column untouched. The nullable icon column can't be cleared through this
	// query; use ClearAutomationIcon for that. All args are named so sqlc's
	// SQLite emitter keeps a consistent indexing scheme (mixing named and bare
	// positional `?` produced off-by-one parameter indices in 1.31.0).
	UpdateAutomationFields(ctx context.Context, arg UpdateAutomationFieldsParams) error
	// Stamps when the automation most recently fired. updated_at is intentionally
	// NOT touched so the "last edited" semantics stay distinct from "last fired".
	UpdateAutomationLastFired(ctx context.Context, arg UpdateAutomationLastFiredParams) error
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateEffect(ctx context.Context, arg UpdateEffectParams) error
	UpdateEffectDuration(ctx context.Context, arg UpdateEffectDurationParams) error
	UpdateGroupIcon(ctx context.Context, arg UpdateGroupIconParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error
	UpdateRoomIcon(ctx context.Context, arg UpdateRoomIconParams) error
	UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) error
	UpdateSceneIcon(ctx context.Context, arg UpdateSceneIconParams) error
	UpdateSceneName(ctx context.Context, arg UpdateSceneNameParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	// Partial update of mutable profile fields. Nil narg values leave their column
	// untouched. avatar_path can be set to a value here but cannot be cleared to
	// NULL; use ClearUserAvatar for that (COALESCE cannot distinguish "leave alone"
	// from "set to NULL"). theme is constrained by a CHECK in the migration.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertActiveEffect(ctx context.Context, arg UpsertActiveEffectParams) error
	// Clears the removed flag on conflict so re-discovered devices become active.
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertMQTTConfig(ctx context.Context, arg UpsertMQTTConfigParams) error
	UpsertSceneDevicePayload(ctx context.Context, arg UpsertSceneDevicePayloadParams) error
	UpsertSceneExpectedState(ctx context.Context, arg UpsertSceneExpectedStateParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertZigbeeDevice(ctx context.Context, arg UpsertZigbeeDeviceParams) error
}

var _ Querier = (*Queries)(nil)
