// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rooms.sql

package sqlite

import (
	"context"
	"time"
)

const addRoomDevice = `-- name: AddRoomDevice :exec
INSERT INTO room_devices (id, room_id, device_id) VALUES (?, ?, ?)
`

type AddRoomDeviceParams struct {
	ID       string
	RoomID   string
	DeviceID string
}

func (q *Queries) AddRoomDevice(ctx context.Context, arg AddRoomDeviceParams) error {
	_, err := q.db.ExecContext(ctx, addRoomDevice, arg.ID, arg.RoomID, arg.DeviceID)
	return err
}

const clearRoomIcon = `-- name: ClearRoomIcon :exec
UPDATE rooms SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearRoomIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearRoomIcon, id)
	return err
}

const createRoom = `-- name: CreateRoom :exec

INSERT INTO rooms (id, name, created_by) VALUES (?, ?, ?)
`

type CreateRoomParams struct {
	ID        string
	Name      string
	CreatedBy *string
}

// Rooms share the same read-shape with scenes/groups/automations: the row is
// joined against users to attach optional creator attribution, so each :one /
// :many SELECT returns the room columns plus three nullable creator columns.
//
// Partial updates use the COALESCE(sqlc.narg, col) gate pattern: nil means
// "leave alone". The nullable `icon` column needs a dedicated ClearRoomIcon
// because COALESCE can't distinguish "leave alone" from "set to NULL".
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.ID, arg.Name, arg.CreatedBy)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.id = ?
`

type GetRoomRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetRoom(ctx context.Context, id string) (GetRoomRow, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i GetRoomRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listRoomDevices = `-- name: ListRoomDevices :many
SELECT id, room_id, device_id FROM room_devices WHERE room_id = ?
`

func (q *Queries) ListRoomDevices(ctx context.Context, roomID string) ([]RoomDevice, error) {
	rows, err := q.db.QueryContext(ctx, listRoomDevices, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomDevice
	for rows.Next() {
		var i RoomDevice
		if err := rows.Scan(&i.ID, &i.RoomID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
LEFT JOIN users u ON u.id = r.created_by
`

type ListRoomsRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListRooms(ctx context.Context) ([]ListRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsContainingDevice = `-- name: ListRoomsContainingDevice :many
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
INNER JOIN room_devices rd ON r.id = rd.room_id
LEFT JOIN users u ON u.id = r.created_by
WHERE rd.device_id = ?
`

type ListRoomsContainingDeviceRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListRoomsContainingDevice(ctx context.Context, deviceID string) ([]ListRoomsContainingDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsContainingDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsContainingDeviceRow
	for rows.Next() {
		var i ListRoomsContainingDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomDevice = `-- name: RemoveRoomDevice :exec
DELETE FROM room_devices WHERE id = ?
`

func (q *Queries) RemoveRoomDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeRoomDevice, id)
	return err
}

const removeRoomDeviceByRoomAndDevice = `-- name: RemoveRoomDeviceByRoomAndDevice :exec
DELETE FROM room_devices WHERE room_id = ? AND device_id = ?
`

type RemoveRoomDeviceByRoomAndDeviceParams struct {
	RoomID   string
	DeviceID string
}

func (q *Queries) RemoveRoomDeviceByRoomAndDevice(ctx context.Context, arg RemoveRoomDeviceByRoomAndDeviceParams) error {
	_, err := q.db.ExecContext(ctx, removeRoomDeviceByRoomAndDevice, arg.RoomID, arg.DeviceID)
	return err
}

const updateRoomIcon = `-- name: UpdateRoomIcon :exec
UPDATE rooms SET icon = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRoomIconParams struct {
	Icon *string
	ID   string
}

func (q *Queries) UpdateRoomIcon(ctx context.Context, arg UpdateRoomIconParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomIcon, arg.Icon, arg.ID)
	return err
}

const updateRoomName = `-- name: UpdateRoomName :exec
UPDATE rooms SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRoomNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomName, arg.Name, arg.ID)
	return err
}
