// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rooms.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (id, room_id, member_type, member_id)
VALUES (?, ?, ?, ?)
`

type AddRoomMemberParams struct {
	ID         string
	RoomID     string
	MemberType device.RoomMemberType
	MemberID   string
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.ExecContext(ctx, addRoomMember,
		arg.ID,
		arg.RoomID,
		arg.MemberType,
		arg.MemberID,
	)
	return err
}

const addRoomMemberIfMissing = `-- name: AddRoomMemberIfMissing :execrows
INSERT OR IGNORE INTO room_members (id, room_id, member_type, member_id)
VALUES (?, ?, ?, ?)
`

type AddRoomMemberIfMissingParams struct {
	ID         string
	RoomID     string
	MemberType device.RoomMemberType
	MemberID   string
}

func (q *Queries) AddRoomMemberIfMissing(ctx context.Context, arg AddRoomMemberIfMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addRoomMemberIfMissing,
		arg.ID,
		arg.RoomID,
		arg.MemberType,
		arg.MemberID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const batchDeleteRooms = `-- name: BatchDeleteRooms :execrows
DELETE FROM rooms
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) BatchDeleteRooms(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteRooms, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearRoomIcon = `-- name: ClearRoomIcon :exec
UPDATE rooms SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearRoomIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearRoomIcon, id)
	return err
}

const createRoom = `-- name: CreateRoom :exec

INSERT INTO rooms (id, name, created_by) VALUES (?, ?, ?)
`

type CreateRoomParams struct {
	ID        string
	Name      string
	CreatedBy *string
}

// Rooms share the same read-shape with scenes/groups/automations: the row is
// joined against users to attach optional creator attribution, so each :one /
// :many SELECT returns the room columns plus three nullable creator columns.
//
// Partial updates use the COALESCE(sqlc.narg, col) gate pattern: nil means
// "leave alone". The nullable `icon` column needs a dedicated ClearRoomIcon
// because COALESCE can't distinguish "leave alone" from "set to NULL".
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.ID, arg.Name, arg.CreatedBy)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.id = ?
`

type GetRoomRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetRoom(ctx context.Context, id string) (GetRoomRow, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i GetRoomRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT id, room_id, member_type, member_id
FROM room_members
WHERE room_id = ?
`

func (q *Queries) ListRoomMembers(ctx context.Context, roomID string) ([]RoomMember, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MemberType,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMemberships = `-- name: ListRoomMemberships :many
SELECT rm.id, rm.room_id, rm.member_type, rm.member_id, r.name AS room_name
FROM room_members rm
INNER JOIN rooms r ON r.id = rm.room_id
`

type ListRoomMembershipsRow struct {
	ID         string
	RoomID     string
	MemberType device.RoomMemberType
	MemberID   string
	RoomName   string
}

func (q *Queries) ListRoomMemberships(ctx context.Context) ([]ListRoomMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembershipsRow
	for rows.Next() {
		var i ListRoomMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MemberType,
			&i.MemberID,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
LEFT JOIN users u ON u.id = r.created_by
`

type ListRoomsRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListRooms(ctx context.Context) ([]ListRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsContainingMember = `-- name: ListRoomsContainingMember :many
SELECT r.id, r.name, r.icon, r.created_at, r.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM rooms r
INNER JOIN room_members rm ON r.id = rm.room_id
LEFT JOIN users u ON u.id = r.created_by
WHERE rm.member_type = ? AND rm.member_id = ?
`

type ListRoomsContainingMemberParams struct {
	MemberType device.RoomMemberType
	MemberID   string
}

type ListRoomsContainingMemberRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListRoomsContainingMember(ctx context.Context, arg ListRoomsContainingMemberParams) ([]ListRoomsContainingMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsContainingMember, arg.MemberType, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsContainingMemberRow
	for rows.Next() {
		var i ListRoomsContainingMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members WHERE id = ?
`

func (q *Queries) RemoveRoomMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeRoomMember, id)
	return err
}

const removeRoomMembersByGroup = `-- name: RemoveRoomMembersByGroup :exec
DELETE FROM room_members WHERE member_type = 'group' AND member_id = ?
`

// Cleanup of dangling polymorphic group references when a group is deleted.
// Mirrors group_members FK cascade for room-as-group-member; no FK because
// member_id is polymorphic.
func (q *Queries) RemoveRoomMembersByGroup(ctx context.Context, memberID string) error {
	_, err := q.db.ExecContext(ctx, removeRoomMembersByGroup, memberID)
	return err
}

const resolveRoomIDByName = `-- name: ResolveRoomIDByName :one
SELECT id FROM rooms WHERE name = ? LIMIT 1
`

func (q *Queries) ResolveRoomIDByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveRoomIDByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateRoomIcon = `-- name: UpdateRoomIcon :exec
UPDATE rooms SET icon = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRoomIconParams struct {
	Icon *string
	ID   string
}

func (q *Queries) UpdateRoomIcon(ctx context.Context, arg UpdateRoomIconParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomIcon, arg.Icon, arg.ID)
	return err
}

const updateRoomName = `-- name: UpdateRoomName :exec
UPDATE rooms SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRoomNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomName, arg.Name, arg.ID)
	return err
}
