// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: scenes.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const batchDeleteScenes = `-- name: BatchDeleteScenes :execrows
DELETE FROM scenes
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) BatchDeleteScenes(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteScenes, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearSceneIcon = `-- name: ClearSceneIcon :exec
UPDATE scenes SET icon = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearSceneIcon(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearSceneIcon, id)
	return err
}

const createScene = `-- name: CreateScene :exec
INSERT INTO scenes (id, name, created_by) VALUES (?, ?, ?)
`

type CreateSceneParams struct {
	ID        string
	Name      string
	CreatedBy *string
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) error {
	_, err := q.db.ExecContext(ctx, createScene, arg.ID, arg.Name, arg.CreatedBy)
	return err
}

const createSceneAction = `-- name: CreateSceneAction :exec
INSERT INTO scene_actions (id, scene_id, target_type, target_id, payload)
VALUES (?, ?, ?, ?, ?)
`

type CreateSceneActionParams struct {
	ID         string
	SceneID    string
	TargetType device.TargetType
	TargetID   string
	Payload    string
}

func (q *Queries) CreateSceneAction(ctx context.Context, arg CreateSceneActionParams) error {
	_, err := q.db.ExecContext(ctx, createSceneAction,
		arg.ID,
		arg.SceneID,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = ?
`

func (q *Queries) DeleteScene(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteScene, id)
	return err
}

const deleteSceneAction = `-- name: DeleteSceneAction :exec
DELETE FROM scene_actions WHERE id = ?
`

func (q *Queries) DeleteSceneAction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSceneAction, id)
	return err
}

const getScene = `-- name: GetScene :one
SELECT s.id, s.name, s.icon, s.created_at, s.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM scenes s
LEFT JOIN users u ON u.id = s.created_by
WHERE s.id = ?
`

type GetSceneRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) GetScene(ctx context.Context, id string) (GetSceneRow, error) {
	row := q.db.QueryRowContext(ctx, getScene, id)
	var i GetSceneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
	)
	return i, err
}

const listSceneActions = `-- name: ListSceneActions :many
SELECT id, scene_id, target_type, target_id, payload
FROM scene_actions
WHERE scene_id = ?
`

type ListSceneActionsRow struct {
	ID         string
	SceneID    string
	TargetType device.TargetType
	TargetID   string
	Payload    string
}

func (q *Queries) ListSceneActions(ctx context.Context, sceneID string) ([]ListSceneActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSceneActions, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSceneActionsRow
	for rows.Next() {
		var i ListSceneActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenes = `-- name: ListScenes :many
SELECT s.id, s.name, s.icon, s.created_at, s.updated_at,
       u.id   AS creator_id,
       u.username AS creator_username,
       u.name AS creator_name
FROM scenes s
LEFT JOIN users u ON u.id = s.created_by
`

type ListScenesRow struct {
	ID              string
	Name            string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorID       *string
	CreatorUsername *string
	CreatorName     *string
}

func (q *Queries) ListScenes(ctx context.Context) ([]ListScenesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScenes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenesRow
	for rows.Next() {
		var i ListScenesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSceneIcon = `-- name: UpdateSceneIcon :exec
UPDATE scenes SET icon = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateSceneIconParams struct {
	Icon *string
	ID   string
}

func (q *Queries) UpdateSceneIcon(ctx context.Context, arg UpdateSceneIconParams) error {
	_, err := q.db.ExecContext(ctx, updateSceneIcon, arg.Icon, arg.ID)
	return err
}

const updateSceneName = `-- name: UpdateSceneName :exec
UPDATE scenes SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateSceneNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateSceneName(ctx context.Context, arg UpdateSceneNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSceneName, arg.Name, arg.ID)
	return err
}
