// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: scene_rooms.sql

package sqlite

import (
	"context"
)

const deleteSceneRooms = `-- name: DeleteSceneRooms :exec
DELETE FROM scene_rooms WHERE scene_id = ?
`

func (q *Queries) DeleteSceneRooms(ctx context.Context, sceneID string) error {
	_, err := q.db.ExecContext(ctx, deleteSceneRooms, sceneID)
	return err
}

const insertSceneRoom = `-- name: InsertSceneRoom :exec
INSERT OR IGNORE INTO scene_rooms (scene_id, room_id) VALUES (?, ?)
`

type InsertSceneRoomParams struct {
	SceneID string
	RoomID  string
}

func (q *Queries) InsertSceneRoom(ctx context.Context, arg InsertSceneRoomParams) error {
	_, err := q.db.ExecContext(ctx, insertSceneRoom, arg.SceneID, arg.RoomID)
	return err
}

const listAllSceneRooms = `-- name: ListAllSceneRooms :many
SELECT scene_id, room_id FROM scene_rooms
`

func (q *Queries) ListAllSceneRooms(ctx context.Context) ([]SceneRoom, error) {
	rows, err := q.db.QueryContext(ctx, listAllSceneRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneRoom
	for rows.Next() {
		var i SceneRoom
		if err := rows.Scan(&i.SceneID, &i.RoomID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneRooms = `-- name: ListSceneRooms :many
SELECT room_id FROM scene_rooms WHERE scene_id = ?
`

func (q *Queries) ListSceneRooms(ctx context.Context, sceneID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSceneRooms, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var room_id string
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
