// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: scene_expected_states.sql

package sqlite

import (
	"context"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const deleteSceneExpectedStatesByScene = `-- name: DeleteSceneExpectedStatesByScene :exec
DELETE FROM scene_expected_states WHERE scene_id = ?
`

func (q *Queries) DeleteSceneExpectedStatesByScene(ctx context.Context, sceneID string) error {
	_, err := q.db.ExecContext(ctx, deleteSceneExpectedStatesByScene, sceneID)
	return err
}

const listAllSceneExpectedStates = `-- name: ListAllSceneExpectedStates :many
SELECT scene_id, device_id, on_state, brightness, color_temp, color_r, color_g, color_b
FROM scene_expected_states
`

func (q *Queries) ListAllSceneExpectedStates(ctx context.Context) ([]SceneExpectedState, error) {
	rows, err := q.db.QueryContext(ctx, listAllSceneExpectedStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneExpectedState
	for rows.Next() {
		var i SceneExpectedState
		if err := rows.Scan(
			&i.SceneID,
			&i.DeviceID,
			&i.OnState,
			&i.Brightness,
			&i.ColorTemp,
			&i.ColorR,
			&i.ColorG,
			&i.ColorB,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneExpectedStates = `-- name: ListSceneExpectedStates :many
SELECT scene_id, device_id, on_state, brightness, color_temp, color_r, color_g, color_b
FROM scene_expected_states
WHERE scene_id = ?
`

func (q *Queries) ListSceneExpectedStates(ctx context.Context, sceneID string) ([]SceneExpectedState, error) {
	rows, err := q.db.QueryContext(ctx, listSceneExpectedStates, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneExpectedState
	for rows.Next() {
		var i SceneExpectedState
		if err := rows.Scan(
			&i.SceneID,
			&i.DeviceID,
			&i.OnState,
			&i.Brightness,
			&i.ColorTemp,
			&i.ColorR,
			&i.ColorG,
			&i.ColorB,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSceneExpectedState = `-- name: UpsertSceneExpectedState :exec
INSERT INTO scene_expected_states (scene_id, device_id, on_state, brightness, color_temp, color_r, color_g, color_b)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(scene_id, device_id) DO UPDATE SET
    on_state   = excluded.on_state,
    brightness = excluded.brightness,
    color_temp = excluded.color_temp,
    color_r    = excluded.color_r,
    color_g    = excluded.color_g,
    color_b    = excluded.color_b
`

type UpsertSceneExpectedStateParams struct {
	SceneID    string
	DeviceID   device.DeviceID
	OnState    *int64
	Brightness *int64
	ColorTemp  *int64
	ColorR     *int64
	ColorG     *int64
	ColorB     *int64
}

func (q *Queries) UpsertSceneExpectedState(ctx context.Context, arg UpsertSceneExpectedStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSceneExpectedState,
		arg.SceneID,
		arg.DeviceID,
		arg.OnState,
		arg.Brightness,
		arg.ColorTemp,
		arg.ColorR,
		arg.ColorG,
		arg.ColorB,
	)
	return err
}
