// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: sensor_history.sql

package sqlite

import (
	"context"
	"time"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const insertSensorReading = `-- name: InsertSensorReading :one
INSERT INTO sensor_history (device_id, temperature, humidity, battery, pressure, illuminance, recorded_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSensorReadingParams struct {
	DeviceID    device.DeviceID
	Temperature *float64
	Humidity    *float64
	Battery     *int64
	Pressure    *float64
	Illuminance *float64
	RecordedAt  time.Time
}

// Returns the auto-generated id; other fields echo the input.
func (q *Queries) InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSensorReading,
		arg.DeviceID,
		arg.Temperature,
		arg.Humidity,
		arg.Battery,
		arg.Pressure,
		arg.Illuminance,
		arg.RecordedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const querySensorHistory = `-- name: QuerySensorHistory :many
SELECT id, device_id, temperature, humidity, battery, pressure, illuminance, recorded_at
FROM sensor_history
WHERE device_id   = ?1
  AND recorded_at >= ?2
  AND recorded_at <= ?3
ORDER BY recorded_at DESC
LIMIT IIF(CAST(?4 AS INTEGER) > 0, CAST(?4 AS INTEGER), -1)
`

type QuerySensorHistoryParams struct {
	DeviceID device.DeviceID
	FromTime time.Time
	ToTime   time.Time
	Lim      int64
}

// Optional LIMIT collapsed into one query: SQLite treats LIMIT -1 as unbounded,
// and IIF(lim > 0, lim, -1) turns a 0 sentinel into "no limit".
func (q *Queries) QuerySensorHistory(ctx context.Context, arg QuerySensorHistoryParams) ([]SensorHistory, error) {
	rows, err := q.db.QueryContext(ctx, querySensorHistory,
		arg.DeviceID,
		arg.FromTime,
		arg.ToTime,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorHistory
	for rows.Next() {
		var i SensorHistory
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.Battery,
			&i.Pressure,
			&i.Illuminance,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
