// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tuya_config.sql

package sqlite

import (
	"context"
)

const deleteTuyaConfig = `-- name: DeleteTuyaConfig :exec
DELETE FROM tuya_config WHERE id = 1
`

func (q *Queries) DeleteTuyaConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTuyaConfig)
	return err
}

const getTuyaConfig = `-- name: GetTuyaConfig :one
SELECT access_id, access_secret, region, enabled
FROM tuya_config
WHERE id = 1
`

type GetTuyaConfigRow struct {
	AccessID     string
	AccessSecret string
	Region       string
	Enabled      bool
}

func (q *Queries) GetTuyaConfig(ctx context.Context) (GetTuyaConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getTuyaConfig)
	var i GetTuyaConfigRow
	err := row.Scan(
		&i.AccessID,
		&i.AccessSecret,
		&i.Region,
		&i.Enabled,
	)
	return i, err
}

const upsertTuyaConfig = `-- name: UpsertTuyaConfig :exec
INSERT INTO tuya_config (id, access_id, access_secret, region, enabled)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    access_id     = excluded.access_id,
    access_secret = excluded.access_secret,
    region        = excluded.region,
    enabled       = excluded.enabled
`

type UpsertTuyaConfigParams struct {
	AccessID     string
	AccessSecret string
	Region       string
	Enabled      bool
}

func (q *Queries) UpsertTuyaConfig(ctx context.Context, arg UpsertTuyaConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertTuyaConfig,
		arg.AccessID,
		arg.AccessSecret,
		arg.Region,
		arg.Enabled,
	)
	return err
}
