// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package sqlite

import (
	"context"
	"time"
)

const batchDeleteUsers = `-- name: BatchDeleteUsers :execrows
DELETE FROM users
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

func (q *Queries) BatchDeleteUsers(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteUsers, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearUserAvatar = `-- name: ClearUserAvatar :exec
UPDATE users SET avatar_path = NULL WHERE id = ?
`

func (q *Queries) ClearUserAvatar(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearUserAvatar, id)
	return err
}

const completeFirstPasswordChange = `-- name: CompleteFirstPasswordChange :execrows
UPDATE users
SET password_hash = ?1,
    must_change_password = false
WHERE id = ?2 AND must_change_password = true
`

type CompleteFirstPasswordChangeParams struct {
	PasswordHash string
	ID           string
}

// Sets a fresh password hash and clears the must_change_password flag in one
// statement. The WHERE clause guards against use outside the forced-change
// flow: only rows where the flag is currently set will be updated.
func (q *Queries) CompleteFirstPasswordChange(ctx context.Context, arg CompleteFirstPasswordChangeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeFirstPasswordChange, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, name, password_hash, must_change_password)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID                 string
	Username           string
	Name               string
	PasswordHash       string
	MustChangePassword bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.PasswordHash,
		arg.MustChangePassword,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserAvatarPath = `-- name: GetUserAvatarPath :one
SELECT avatar_path FROM users WHERE id = ?
`

func (q *Queries) GetUserAvatarPath(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatarPath, id)
	var avatar_path *string
	err := row.Scan(&avatar_path)
	return avatar_path, err
}

const getUserAvatarPathsByIDs = `-- name: GetUserAvatarPathsByIDs :many
SELECT id, avatar_path FROM users
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
`

type GetUserAvatarPathsByIDsRow struct {
	ID         string
	AvatarPath *string
}

func (q *Queries) GetUserAvatarPathsByIDs(ctx context.Context, idsJson string) ([]GetUserAvatarPathsByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAvatarPathsByIDs, idsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAvatarPathsByIDsRow
	for rows.Next() {
		var i GetUserAvatarPathsByIDsRow
		if err := rows.Scan(&i.ID, &i.AvatarPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, name, password_hash, avatar_path, theme, must_change_password, created_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID                 string
	Username           string
	Name               string
	PasswordHash       string
	AvatarPath         *string
	Theme              string
	MustChangePassword bool
	CreatedAt          time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Theme,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, name, password_hash, avatar_path, theme, must_change_password, created_at
FROM users
WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID                 string
	Username           string
	Name               string
	PasswordHash       string
	AvatarPath         *string
	Theme              string
	MustChangePassword bool
	CreatedAt          time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Theme,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, name, password_hash, avatar_path, theme, must_change_password, created_at
FROM users
ORDER BY created_at ASC
`

type ListUsersRow struct {
	ID                 string
	Username           string
	Name               string
	PasswordHash       string
	AvatarPath         *string
	Theme              string
	MustChangePassword bool
	CreatedAt          time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.PasswordHash,
			&i.AvatarPath,
			&i.Theme,
			&i.MustChangePassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserMustChangePassword = `-- name: SetUserMustChangePassword :exec
UPDATE users SET must_change_password = ?1 WHERE id = ?2
`

type SetUserMustChangePasswordParams struct {
	MustChangePassword bool
	ID                 string
}

func (q *Queries) SetUserMustChangePassword(ctx context.Context, arg SetUserMustChangePasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserMustChangePassword, arg.MustChangePassword, arg.ID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET
    name        = COALESCE(?1,        name),
    theme       = COALESCE(?2,       theme),
    avatar_path = COALESCE(?3, avatar_path)
WHERE id = ?4
`

type UpdateUserProfileParams struct {
	Name       *string
	Theme      *string
	AvatarPath *string
	ID         string
}

// Partial update of mutable profile fields. Nil narg values leave their column
// untouched. avatar_path can be set to a value here but cannot be cleared to
// NULL; use ClearUserAvatar for that (COALESCE cannot distinguish "leave alone"
// from "set to NULL"). theme is constrained by a CHECK in the migration.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Name,
		arg.Theme,
		arg.AvatarPath,
		arg.ID,
	)
	return err
}
