// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: webhooks.sql

package sqlite

import (
	"context"
	"time"
)

const batchDeleteWebhookEndpoints = `-- name: BatchDeleteWebhookEndpoints :execrows
DELETE FROM webhook_endpoints
WHERE id IN (SELECT value FROM json_each(CAST(?1 AS TEXT)))
  AND NOT EXISTS (
      SELECT 1 FROM automation_nodes n
      WHERE n.type = 'trigger'
        AND json_valid(n.config)
        AND json_extract(n.config, '$.event_type') = 'webhook.received'
        AND json_extract(n.config, '$.endpoint_id') = webhook_endpoints.id
  )
`

func (q *Queries) BatchDeleteWebhookEndpoints(ctx context.Context, idsJson string) (int64, error) {
	result, err := q.db.ExecContext(ctx, batchDeleteWebhookEndpoints, idsJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countWebhookDeliveriesSince = `-- name: CountWebhookDeliveriesSince :one
SELECT COUNT(*) FROM webhook_deliveries
WHERE endpoint_id = ? AND received_at >= ? AND outcome != 'rate_limited'
`

type CountWebhookDeliveriesSinceParams struct {
	EndpointID string
	ReceivedAt time.Time
}

func (q *Queries) CountWebhookDeliveriesSince(ctx context.Context, arg CountWebhookDeliveriesSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookDeliveriesSince, arg.EndpointID, arg.ReceivedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :exec
INSERT INTO webhook_endpoints (
    id, name, enabled, secret_hash,
    rate_limit_count, rate_limit_window_ms, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWebhookEndpointParams struct {
	ID                string
	Name              string
	Enabled           bool
	SecretHash        string
	RateLimitCount    int64
	RateLimitWindowMs int64
	CreatedBy         *string
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookEndpoint,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.SecretHash,
		arg.RateLimitCount,
		arg.RateLimitWindowMs,
		arg.CreatedBy,
	)
	return err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = ?
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookEndpoint, id)
	return err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, endpoint_id, received_at, outcome, http_status, client_ip, user_agent, content_type, body_size, duration_ms, request_id, query_keys_json, header_names_json, body FROM webhook_deliveries WHERE id = ?
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ReceivedAt,
		&i.Outcome,
		&i.HttpStatus,
		&i.ClientIp,
		&i.UserAgent,
		&i.ContentType,
		&i.BodySize,
		&i.DurationMs,
		&i.RequestID,
		&i.QueryKeysJson,
		&i.HeaderNamesJson,
		&i.Body,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT w.id, w.name, w.enabled,
       w.rate_limit_count, w.rate_limit_window_ms,
       w.created_at, w.updated_at,
       u.id AS creator_id, u.username AS creator_username, u.name AS creator_name,
       d.received_at AS last_delivery_at
FROM webhook_endpoints w
LEFT JOIN users u ON u.id = w.created_by
LEFT JOIN webhook_deliveries d ON d.id = (
    SELECT latest.id FROM webhook_deliveries latest
    WHERE latest.endpoint_id = w.id
    ORDER BY latest.received_at DESC, latest.id DESC LIMIT 1
)
WHERE w.id = ?
`

type GetWebhookEndpointRow struct {
	ID                string
	Name              string
	Enabled           bool
	RateLimitCount    int64
	RateLimitWindowMs int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatorID         *string
	CreatorUsername   *string
	CreatorName       *string
	LastDeliveryAt    *time.Time
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id string) (GetWebhookEndpointRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, id)
	var i GetWebhookEndpointRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.RateLimitCount,
		&i.RateLimitWindowMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorName,
		&i.LastDeliveryAt,
	)
	return i, err
}

const getWebhookEndpointBySecretHash = `-- name: GetWebhookEndpointBySecretHash :one
SELECT id, name, enabled, secret_hash,
       rate_limit_count, rate_limit_window_ms, created_by, created_at, updated_at
FROM webhook_endpoints
WHERE secret_hash = ?
`

func (q *Queries) GetWebhookEndpointBySecretHash(ctx context.Context, secretHash string) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpointBySecretHash, secretHash)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.SecretHash,
		&i.RateLimitCount,
		&i.RateLimitWindowMs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasWebhookRateLimitDeliverySince = `-- name: HasWebhookRateLimitDeliverySince :one
SELECT EXISTS(
    SELECT 1 FROM webhook_deliveries
    WHERE endpoint_id = ? AND received_at >= ? AND outcome = 'rate_limited'
)
`

type HasWebhookRateLimitDeliverySinceParams struct {
	EndpointID string
	ReceivedAt time.Time
}

func (q *Queries) HasWebhookRateLimitDeliverySince(ctx context.Context, arg HasWebhookRateLimitDeliverySinceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasWebhookRateLimitDeliverySince, arg.EndpointID, arg.ReceivedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec
INSERT INTO webhook_deliveries (
    id, endpoint_id, received_at, outcome, http_status,
    client_ip, user_agent, content_type, body_size, body, duration_ms,
    request_id, query_keys_json, header_names_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWebhookDeliveryParams struct {
	ID              string
	EndpointID      string
	ReceivedAt      time.Time
	Outcome         string
	HttpStatus      int64
	ClientIp        string
	UserAgent       string
	ContentType     string
	BodySize        int64
	Body            *string
	DurationMs      int64
	RequestID       *string
	QueryKeysJson   string
	HeaderNamesJson string
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.ReceivedAt,
		arg.Outcome,
		arg.HttpStatus,
		arg.ClientIp,
		arg.UserAgent,
		arg.ContentType,
		arg.BodySize,
		arg.Body,
		arg.DurationMs,
		arg.RequestID,
		arg.QueryKeysJson,
		arg.HeaderNamesJson,
	)
	return err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, endpoint_id, received_at, outcome, http_status, client_ip, user_agent, content_type, body_size, duration_ms, request_id, query_keys_json, header_names_json, body FROM webhook_deliveries
WHERE webhook_deliveries.endpoint_id = ?1
  AND (CAST(?2 AS TIMESTAMP) IS NULL
       OR received_at < CAST(?2 AS TIMESTAMP))
ORDER BY received_at DESC, id DESC
LIMIT IIF(CAST(?3 AS INTEGER) > 0, CAST(?3 AS INTEGER), 100)
`

type ListWebhookDeliveriesParams struct {
	EndpointID string
	Before     *time.Time
	Lim        int64
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveries, arg.EndpointID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.ReceivedAt,
			&i.Outcome,
			&i.HttpStatus,
			&i.ClientIp,
			&i.UserAgent,
			&i.ContentType,
			&i.BodySize,
			&i.DurationMs,
			&i.RequestID,
			&i.QueryKeysJson,
			&i.HeaderNamesJson,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointAutomationReferences = `-- name: ListWebhookEndpointAutomationReferences :many
SELECT DISTINCT a.id, a.name
FROM automations a
JOIN automation_nodes n ON n.automation_id = a.id
WHERE n.type = 'trigger'
  AND json_valid(n.config)
  AND json_extract(n.config, '$.event_type') = 'webhook.received'
  AND json_extract(n.config, '$.endpoint_id') = ?
ORDER BY lower(a.name), a.id
`

type ListWebhookEndpointAutomationReferencesRow struct {
	ID   string
	Name string
}

func (q *Queries) ListWebhookEndpointAutomationReferences(ctx context.Context, config string) ([]ListWebhookEndpointAutomationReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpointAutomationReferences, config)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookEndpointAutomationReferencesRow
	for rows.Next() {
		var i ListWebhookEndpointAutomationReferencesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT w.id, w.name, w.enabled,
       w.rate_limit_count, w.rate_limit_window_ms,
       w.created_at, w.updated_at,
       u.id AS creator_id, u.username AS creator_username, u.name AS creator_name,
       d.received_at AS last_delivery_at
FROM webhook_endpoints w
LEFT JOIN users u ON u.id = w.created_by
LEFT JOIN webhook_deliveries d ON d.id = (
    SELECT latest.id FROM webhook_deliveries latest
    WHERE latest.endpoint_id = w.id
    ORDER BY latest.received_at DESC, latest.id DESC LIMIT 1
)
ORDER BY lower(w.name), w.id
`

type ListWebhookEndpointsRow struct {
	ID                string
	Name              string
	Enabled           bool
	RateLimitCount    int64
	RateLimitWindowMs int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatorID         *string
	CreatorUsername   *string
	CreatorName       *string
	LastDeliveryAt    *time.Time
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context) ([]ListWebhookEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookEndpointsRow
	for rows.Next() {
		var i ListWebhookEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.RateLimitCount,
			&i.RateLimitWindowMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorName,
			&i.LastDeliveryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWebhookDeliveriesOlderThan = `-- name: PruneWebhookDeliveriesOlderThan :execrows
DELETE FROM webhook_deliveries WHERE received_at < ?
`

func (q *Queries) PruneWebhookDeliveriesOlderThan(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneWebhookDeliveriesOlderThan, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneWebhookDeliveriesOverLimit = `-- name: PruneWebhookDeliveriesOverLimit :execrows
DELETE FROM webhook_deliveries
WHERE webhook_deliveries.endpoint_id = ?1
  AND webhook_deliveries.id IN (
      SELECT kept.id FROM webhook_deliveries AS kept
      WHERE kept.endpoint_id = ?1
      ORDER BY kept.received_at DESC, kept.id DESC
      LIMIT -1 OFFSET ?2
  )
`

type PruneWebhookDeliveriesOverLimitParams struct {
	EndpointID string
	KeepCount  int64
}

func (q *Queries) PruneWebhookDeliveriesOverLimit(ctx context.Context, arg PruneWebhookDeliveriesOverLimitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneWebhookDeliveriesOverLimit, arg.EndpointID, arg.KeepCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :exec
UPDATE webhook_endpoints SET
    name = ?,
    enabled = ?,
    rate_limit_count = ?,
    rate_limit_window_ms = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWebhookEndpointParams struct {
	Name              string
	Enabled           bool
	RateLimitCount    int64
	RateLimitWindowMs int64
	ID                string
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookEndpoint,
		arg.Name,
		arg.Enabled,
		arg.RateLimitCount,
		arg.RateLimitWindowMs,
		arg.ID,
	)
	return err
}

const updateWebhookEndpointSecretHash = `-- name: UpdateWebhookEndpointSecretHash :exec
UPDATE webhook_endpoints
SET secret_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWebhookEndpointSecretHashParams struct {
	SecretHash string
	ID         string
}

func (q *Queries) UpdateWebhookEndpointSecretHash(ctx context.Context, arg UpdateWebhookEndpointSecretHashParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookEndpointSecretHash, arg.SecretHash, arg.ID)
	return err
}
