// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: zigbee2mqtt_config.sql

package sqlite

import (
	"context"
)

const deleteZigbee2MQTTConfig = `-- name: DeleteZigbee2MQTTConfig :exec
DELETE FROM zigbee2mqtt_config WHERE id = 1
`

func (q *Queries) DeleteZigbee2MQTTConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteZigbee2MQTTConfig)
	return err
}

const getZigbee2MQTTConfig = `-- name: GetZigbee2MQTTConfig :one
SELECT broker, username, password, use_wss, enabled, scan_schedule_enabled, scan_hour, scan_minute, frontend_url,
       interactive_commands_per_second, continuous_commands_per_second
FROM zigbee2mqtt_config
WHERE id = 1
`

type GetZigbee2MQTTConfigRow struct {
	Broker                       string
	Username                     string
	Password                     string
	UseWss                       bool
	Enabled                      bool
	ScanScheduleEnabled          bool
	ScanHour                     *int64
	ScanMinute                   *int64
	FrontendUrl                  *string
	InteractiveCommandsPerSecond int64
	ContinuousCommandsPerSecond  int64
}

func (q *Queries) GetZigbee2MQTTConfig(ctx context.Context) (GetZigbee2MQTTConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getZigbee2MQTTConfig)
	var i GetZigbee2MQTTConfigRow
	err := row.Scan(
		&i.Broker,
		&i.Username,
		&i.Password,
		&i.UseWss,
		&i.Enabled,
		&i.ScanScheduleEnabled,
		&i.ScanHour,
		&i.ScanMinute,
		&i.FrontendUrl,
		&i.InteractiveCommandsPerSecond,
		&i.ContinuousCommandsPerSecond,
	)
	return i, err
}

const upsertZigbee2MQTTConfig = `-- name: UpsertZigbee2MQTTConfig :exec
INSERT INTO zigbee2mqtt_config (id, broker, username, password, use_wss, enabled, scan_schedule_enabled, scan_hour, scan_minute, frontend_url, interactive_commands_per_second, continuous_commands_per_second)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    broker                = excluded.broker,
    username              = excluded.username,
    password              = excluded.password,
    use_wss               = excluded.use_wss,
    enabled               = excluded.enabled,
    scan_schedule_enabled = excluded.scan_schedule_enabled,
    scan_hour             = excluded.scan_hour,
    scan_minute           = excluded.scan_minute,
    frontend_url          = excluded.frontend_url,
    interactive_commands_per_second = excluded.interactive_commands_per_second,
    continuous_commands_per_second  = excluded.continuous_commands_per_second
`

type UpsertZigbee2MQTTConfigParams struct {
	Broker                       string
	Username                     string
	Password                     string
	UseWss                       bool
	Enabled                      bool
	ScanScheduleEnabled          bool
	ScanHour                     *int64
	ScanMinute                   *int64
	FrontendUrl                  *string
	InteractiveCommandsPerSecond int64
	ContinuousCommandsPerSecond  int64
}

func (q *Queries) UpsertZigbee2MQTTConfig(ctx context.Context, arg UpsertZigbee2MQTTConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertZigbee2MQTTConfig,
		arg.Broker,
		arg.Username,
		arg.Password,
		arg.UseWss,
		arg.Enabled,
		arg.ScanScheduleEnabled,
		arg.ScanHour,
		arg.ScanMinute,
		arg.FrontendUrl,
		arg.InteractiveCommandsPerSecond,
		arg.ContinuousCommandsPerSecond,
	)
	return err
}
