// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: zigbee_device_metadata.sql

package sqlite

import (
	"context"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const deleteZigbeeDeviceMetadata = `-- name: DeleteZigbeeDeviceMetadata :exec
DELETE FROM zigbee_device_metadata WHERE device_id = ?
`

func (q *Queries) DeleteZigbeeDeviceMetadata(ctx context.Context, deviceID device.DeviceID) error {
	_, err := q.db.ExecContext(ctx, deleteZigbeeDeviceMetadata, deviceID)
	return err
}

const getZigbeeDeviceMetadata = `-- name: GetZigbeeDeviceMetadata :one
SELECT device_id, network_type, ieee_address, network_address, supported,
       interview_state, interview_completed, interviewing, description,
       manufacturer, model_id, power_source, software_build_id, date_code,
       definition_model, definition_vendor, definition_description,
       definition_source, definition_icon, definition_supports_ota,
       endpoints, ota_state, ota_installed_version, ota_latest_version,
       ota_progress, bridge_fingerprint, ota_fingerprint, updated_at
FROM zigbee_device_metadata
WHERE device_id = ?
`

func (q *Queries) GetZigbeeDeviceMetadata(ctx context.Context, deviceID device.DeviceID) (ZigbeeDeviceMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getZigbeeDeviceMetadata, deviceID)
	var i ZigbeeDeviceMetadatum
	err := row.Scan(
		&i.DeviceID,
		&i.NetworkType,
		&i.IeeeAddress,
		&i.NetworkAddress,
		&i.Supported,
		&i.InterviewState,
		&i.InterviewCompleted,
		&i.Interviewing,
		&i.Description,
		&i.Manufacturer,
		&i.ModelID,
		&i.PowerSource,
		&i.SoftwareBuildID,
		&i.DateCode,
		&i.DefinitionModel,
		&i.DefinitionVendor,
		&i.DefinitionDescription,
		&i.DefinitionSource,
		&i.DefinitionIcon,
		&i.DefinitionSupportsOta,
		&i.Endpoints,
		&i.OtaState,
		&i.OtaInstalledVersion,
		&i.OtaLatestVersion,
		&i.OtaProgress,
		&i.BridgeFingerprint,
		&i.OtaFingerprint,
		&i.UpdatedAt,
	)
	return i, err
}

const listZigbeeFirmwareCandidates = `-- name: ListZigbeeFirmwareCandidates :many
SELECT device_id, network_type, ieee_address, network_address, supported,
       interview_state, interview_completed, interviewing, description,
       manufacturer, model_id, power_source, software_build_id, date_code,
       definition_model, definition_vendor, definition_description,
       definition_source, definition_icon, definition_supports_ota,
       endpoints, ota_state, ota_installed_version, ota_latest_version,
       ota_progress, bridge_fingerprint, ota_fingerprint, updated_at
FROM zigbee_device_metadata
WHERE definition_supports_ota = true
  AND LOWER(COALESCE(ota_state, '')) = 'available'
  AND ota_latest_version IS NOT NULL
  AND ota_latest_version != -1
ORDER BY device_id
`

func (q *Queries) ListZigbeeFirmwareCandidates(ctx context.Context) ([]ZigbeeDeviceMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listZigbeeFirmwareCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZigbeeDeviceMetadatum
	for rows.Next() {
		var i ZigbeeDeviceMetadatum
		if err := rows.Scan(
			&i.DeviceID,
			&i.NetworkType,
			&i.IeeeAddress,
			&i.NetworkAddress,
			&i.Supported,
			&i.InterviewState,
			&i.InterviewCompleted,
			&i.Interviewing,
			&i.Description,
			&i.Manufacturer,
			&i.ModelID,
			&i.PowerSource,
			&i.SoftwareBuildID,
			&i.DateCode,
			&i.DefinitionModel,
			&i.DefinitionVendor,
			&i.DefinitionDescription,
			&i.DefinitionSource,
			&i.DefinitionIcon,
			&i.DefinitionSupportsOta,
			&i.Endpoints,
			&i.OtaState,
			&i.OtaInstalledVersion,
			&i.OtaLatestVersion,
			&i.OtaProgress,
			&i.BridgeFingerprint,
			&i.OtaFingerprint,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZigbeeProviderGroupsForDevice = `-- name: ListZigbeeProviderGroupsForDevice :many
SELECT g.id, g.provider_group_id,
       COALESCE(NULLIF(g.name, ''), NULLIF(g.friendly_name, ''), g.id) AS display_name,
       gm.provider_endpoint
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE g.provider = 'zigbee2mqtt'
  AND g.removed = false
  AND gm.member_type = 'device'
  AND gm.member_id = ?
ORDER BY g.id, gm.provider_endpoint
`

type ListZigbeeProviderGroupsForDeviceRow struct {
	ID               string
	ProviderGroupID  *string
	DisplayName      string
	ProviderEndpoint *int64
}

func (q *Queries) ListZigbeeProviderGroupsForDevice(ctx context.Context, memberID string) ([]ListZigbeeProviderGroupsForDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listZigbeeProviderGroupsForDevice, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZigbeeProviderGroupsForDeviceRow
	for rows.Next() {
		var i ListZigbeeProviderGroupsForDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderGroupID,
			&i.DisplayName,
			&i.ProviderEndpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeZigbeeOTAStatus = `-- name: MergeZigbeeOTAStatus :one
INSERT INTO zigbee_device_metadata (
    device_id, ota_state, ota_installed_version, ota_latest_version,
    ota_progress, ota_fingerprint
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
ON CONFLICT(device_id) DO UPDATE SET
    ota_state = excluded.ota_state,
    ota_installed_version = excluded.ota_installed_version,
    ota_latest_version = excluded.ota_latest_version,
    ota_progress = excluded.ota_progress,
    ota_fingerprint = excluded.ota_fingerprint,
    updated_at = CURRENT_TIMESTAMP
WHERE zigbee_device_metadata.ota_fingerprint != excluded.ota_fingerprint
RETURNING device_id
`

type MergeZigbeeOTAStatusParams struct {
	DeviceID            device.DeviceID
	OtaState            *string
	OtaInstalledVersion *int64
	OtaLatestVersion    *int64
	OtaProgress         *float64
	OtaFingerprint      string
}

func (q *Queries) MergeZigbeeOTAStatus(ctx context.Context, arg MergeZigbeeOTAStatusParams) (device.DeviceID, error) {
	row := q.db.QueryRowContext(ctx, mergeZigbeeOTAStatus,
		arg.DeviceID,
		arg.OtaState,
		arg.OtaInstalledVersion,
		arg.OtaLatestVersion,
		arg.OtaProgress,
		arg.OtaFingerprint,
	)
	var device_id device.DeviceID
	err := row.Scan(&device_id)
	return device_id, err
}

const upsertZigbeeBridgeMetadata = `-- name: UpsertZigbeeBridgeMetadata :one
INSERT INTO zigbee_device_metadata (
    device_id, network_type, ieee_address, network_address, supported,
    interview_state, interview_completed, interviewing, description,
    manufacturer, model_id, power_source, software_build_id, date_code,
    definition_model, definition_vendor, definition_description,
    definition_source, definition_icon, definition_supports_ota,
    endpoints, bridge_fingerprint
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8, ?9,
    ?10, ?11, ?12,
    ?13, ?14, ?15,
    ?16, ?17,
    ?18, ?19,
    ?20, ?21,
    ?22
)
ON CONFLICT(device_id) DO UPDATE SET
    network_type = excluded.network_type,
    ieee_address = excluded.ieee_address,
    network_address = excluded.network_address,
    supported = excluded.supported,
    interview_state = excluded.interview_state,
    interview_completed = excluded.interview_completed,
    interviewing = excluded.interviewing,
    description = excluded.description,
    manufacturer = excluded.manufacturer,
    model_id = excluded.model_id,
    power_source = excluded.power_source,
    software_build_id = excluded.software_build_id,
    date_code = excluded.date_code,
    definition_model = excluded.definition_model,
    definition_vendor = excluded.definition_vendor,
    definition_description = excluded.definition_description,
    definition_source = excluded.definition_source,
    definition_icon = excluded.definition_icon,
    definition_supports_ota = excluded.definition_supports_ota,
    endpoints = excluded.endpoints,
    bridge_fingerprint = excluded.bridge_fingerprint,
    updated_at = CURRENT_TIMESTAMP
WHERE zigbee_device_metadata.bridge_fingerprint != excluded.bridge_fingerprint
RETURNING device_id
`

type UpsertZigbeeBridgeMetadataParams struct {
	DeviceID              device.DeviceID
	NetworkType           *string
	IeeeAddress           *string
	NetworkAddress        *int64
	Supported             *bool
	InterviewState        *string
	InterviewCompleted    *bool
	Interviewing          *bool
	Description           *string
	Manufacturer          *string
	ModelID               *string
	PowerSource           *string
	SoftwareBuildID       *string
	DateCode              *string
	DefinitionModel       *string
	DefinitionVendor      *string
	DefinitionDescription *string
	DefinitionSource      *string
	DefinitionIcon        *string
	DefinitionSupportsOta *bool
	Endpoints             string
	BridgeFingerprint     string
}

func (q *Queries) UpsertZigbeeBridgeMetadata(ctx context.Context, arg UpsertZigbeeBridgeMetadataParams) (device.DeviceID, error) {
	row := q.db.QueryRowContext(ctx, upsertZigbeeBridgeMetadata,
		arg.DeviceID,
		arg.NetworkType,
		arg.IeeeAddress,
		arg.NetworkAddress,
		arg.Supported,
		arg.InterviewState,
		arg.InterviewCompleted,
		arg.Interviewing,
		arg.Description,
		arg.Manufacturer,
		arg.ModelID,
		arg.PowerSource,
		arg.SoftwareBuildID,
		arg.DateCode,
		arg.DefinitionModel,
		arg.DefinitionVendor,
		arg.DefinitionDescription,
		arg.DefinitionSource,
		arg.DefinitionIcon,
		arg.DefinitionSupportsOta,
		arg.Endpoints,
		arg.BridgeFingerprint,
	)
	var device_id device.DeviceID
	err := row.Scan(&device_id)
	return device_id, err
}
