// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: zigbee_devices.sql

package sqlite

import (
	"context"

	"github.com/saffronjam/saffron-hive/internal/device"
)

const getZigbeeDeviceByFriendlyName = `-- name: GetZigbeeDeviceByFriendlyName :one
SELECT device_id, ieee_address, friendly_name
FROM zigbee_devices
WHERE friendly_name = ?
`

func (q *Queries) GetZigbeeDeviceByFriendlyName(ctx context.Context, friendlyName string) (ZigbeeDevice, error) {
	row := q.db.QueryRowContext(ctx, getZigbeeDeviceByFriendlyName, friendlyName)
	var i ZigbeeDevice
	err := row.Scan(&i.DeviceID, &i.IeeeAddress, &i.FriendlyName)
	return i, err
}

const getZigbeeDeviceByIEEEAddress = `-- name: GetZigbeeDeviceByIEEEAddress :one
SELECT device_id, ieee_address, friendly_name
FROM zigbee_devices
WHERE ieee_address = ?
`

func (q *Queries) GetZigbeeDeviceByIEEEAddress(ctx context.Context, ieeeAddress string) (ZigbeeDevice, error) {
	row := q.db.QueryRowContext(ctx, getZigbeeDeviceByIEEEAddress, ieeeAddress)
	var i ZigbeeDevice
	err := row.Scan(&i.DeviceID, &i.IeeeAddress, &i.FriendlyName)
	return i, err
}

const registerZigbeeDevice = `-- name: RegisterZigbeeDevice :exec
INSERT INTO zigbee_devices (device_id, ieee_address, friendly_name)
VALUES (?, ?, ?)
`

type RegisterZigbeeDeviceParams struct {
	DeviceID     device.DeviceID
	IeeeAddress  string
	FriendlyName string
}

func (q *Queries) RegisterZigbeeDevice(ctx context.Context, arg RegisterZigbeeDeviceParams) error {
	_, err := q.db.ExecContext(ctx, registerZigbeeDevice, arg.DeviceID, arg.IeeeAddress, arg.FriendlyName)
	return err
}

const upsertZigbeeDevice = `-- name: UpsertZigbeeDevice :exec
INSERT INTO zigbee_devices (device_id, ieee_address, friendly_name)
VALUES (?, ?, ?)
ON CONFLICT(device_id) DO UPDATE SET
    ieee_address  = excluded.ieee_address,
    friendly_name = excluded.friendly_name
`

type UpsertZigbeeDeviceParams struct {
	DeviceID     device.DeviceID
	IeeeAddress  string
	FriendlyName string
}

func (q *Queries) UpsertZigbeeDevice(ctx context.Context, arg UpsertZigbeeDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertZigbeeDevice, arg.DeviceID, arg.IeeeAddress, arg.FriendlyName)
	return err
}
