package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/saffronjam/saffron-hive/internal/adapter/zigbee"
	"github.com/saffronjam/saffron-hive/internal/alarms"
	"github.com/saffronjam/saffron-hive/internal/auth"
	"github.com/saffronjam/saffron-hive/internal/automation"
	"github.com/saffronjam/saffron-hive/internal/device"
	"github.com/saffronjam/saffron-hive/internal/effect"
	"github.com/saffronjam/saffron-hive/internal/eventbus"
	"github.com/saffronjam/saffron-hive/internal/graph/model"
	"github.com/saffronjam/saffron-hive/internal/history"
	"github.com/saffronjam/saffron-hive/internal/logging"
	"github.com/saffronjam/saffron-hive/internal/scene"
	"github.com/saffronjam/saffron-hive/internal/store"
)

// UpdateDevice is the resolver for the updateDevice field.
func (r *mutationResolver) UpdateDevice(ctx context.Context, id string, input model.UpdateDeviceInput) (*model.Device, error) {
	deviceID := device.DeviceID(id)
	d, err := r.Store.GetDevice(ctx, deviceID)
	if err != nil {
		return nil, fmt.Errorf("device %q not found: %w", id, err)
	}
	name := d.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	d, err = r.Store.UpdateDevice(ctx, store.UpdateDeviceParams{
		ID:        deviceID,
		Name:      name,
		Available: d.Available,
		Removed:   d.Removed,
		LastSeen:  d.LastSeen,
	})
	if err != nil {
		return nil, err
	}
	return mapDeviceFromReader(r.StateReader, d), nil
}

// SetDeviceState is the resolver for the setDeviceState field.
func (r *mutationResolver) SetDeviceState(ctx context.Context, deviceID string, state model.DeviceStateInput) (*model.Device, error) {
	id := device.DeviceID(deviceID)
	d, ok := r.StateReader.GetDevice(id)
	if !ok {
		return nil, fmt.Errorf("device %q not found", deviceID)
	}

	cmd := device.Command{
		DeviceID:   id,
		On:         state.On.Value(),
		Brightness: state.Brightness.Value(),
		ColorTemp:  state.ColorTemp.Value(),
		Transition: state.Transition.Value(),
		Origin:     device.OriginUser(),
	}
	if color := state.Color.Value(); color != nil {
		cmd.Color = &device.Color{
			R: color.R,
			G: color.G,
			B: color.B,
			X: color.X,
			Y: color.Y,
		}
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventCommandRequested,
		DeviceID:  deviceID,
		Timestamp: time.Now(),
		Payload:   cmd,
	})

	return mapDeviceFromReader(r.StateReader, d), nil
}

// SimulateDeviceAction is the resolver for the simulateDeviceAction field.
func (r *mutationResolver) SimulateDeviceAction(ctx context.Context, deviceID string, action string) (bool, error) {
	id := device.DeviceID(deviceID)
	if _, ok := r.StateReader.GetDevice(id); !ok {
		return false, fmt.Errorf("device %q not found", deviceID)
	}
	if action == "" {
		return false, fmt.Errorf("action must not be empty")
	}
	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventDeviceActionFired,
		DeviceID:  deviceID,
		Timestamp: time.Now(),
		Payload:   device.Action{Action: action},
	})
	return true, nil
}

// ApplyScene is the resolver for the applyScene field.
func (r *mutationResolver) ApplyScene(ctx context.Context, sceneID string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, sceneID)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", sceneID, err)
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}
	payloads, err := r.Store.ListSceneDevicePayloads(ctx, s.ID)
	if err != nil {
		return nil, err
	}

	plan := scene.BuildApplyCommands(ctx, r.TargetResolver, r.StateReader, sceneID, actions, payloads)
	for _, cmd := range plan.Commands {
		r.EventBus.Publish(eventbus.Event{
			Type:      eventbus.EventCommandRequested,
			DeviceID:  string(cmd.DeviceID),
			Timestamp: time.Now(),
			Payload:   cmd,
		})
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventSceneApplied,
		Timestamp: time.Now(),
		Payload:   sceneID,
	})

	return mapScene(ctx, r.StateReader, r.TargetResolver, r.Store, s, actions, payloads), nil
}

// CreateScene is the resolver for the createScene field.
func (r *mutationResolver) CreateScene(ctx context.Context, input model.CreateSceneInput) (*model.Scene, error) {
	sceneID := uuid.New().String()
	_, err := r.Store.CreateScene(ctx, store.CreateSceneParams{
		ID:        sceneID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}

	targets := toSceneTargetRefs(input.Actions)
	payloads := toSceneDevicePayloads(sceneID, input.DevicePayloads.Value())
	if err := r.Store.SaveSceneContent(ctx, store.SaveSceneContentParams{
		SceneID:  sceneID,
		Targets:  targets,
		Payloads: payloads,
	}); err != nil {
		return nil, err
	}

	return loadAndMapScene(ctx, r, sceneID)
}

// UpdateScene is the resolver for the updateScene field.
func (r *mutationResolver) UpdateScene(ctx context.Context, id string, input model.UpdateSceneInput) (*model.Scene, error) {
	_, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", id, err)
	}

	params := store.UpdateSceneParams{}
	updateScene := false
	if name, ok := input.Name.ValueOK(); ok {
		params.Name = name
		updateScene = true
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		params.SetIcon = true
		params.Icon = icon
		updateScene = true
	}
	if updateScene {
		if _, err := r.Store.UpdateScene(ctx, id, params); err != nil {
			return nil, err
		}
	}

	_, actionsGiven := input.Actions.ValueOK()
	_, payloadsGiven := input.DevicePayloads.ValueOK()
	if actionsGiven || payloadsGiven {
		var targets []store.SceneTargetRef
		var payloads []store.SceneDevicePayload
		if actionsGiven {
			targets = toSceneTargetRefs(input.Actions.Value())
		} else {
			existing, err := r.Store.ListSceneActions(ctx, id)
			if err != nil {
				return nil, err
			}
			targets = make([]store.SceneTargetRef, len(existing))
			for i, a := range existing {
				targets[i] = store.SceneTargetRef{TargetType: a.TargetType, TargetID: a.TargetID}
			}
		}
		if payloadsGiven {
			payloads = toSceneDevicePayloads(id, input.DevicePayloads.Value())
		} else {
			existing, err := r.Store.ListSceneDevicePayloads(ctx, id)
			if err != nil {
				return nil, err
			}
			payloads = existing
		}
		if err := r.Store.SaveSceneContent(ctx, store.SaveSceneContentParams{
			SceneID:  id,
			Targets:  targets,
			Payloads: payloads,
		}); err != nil {
			return nil, err
		}
	}

	return loadAndMapScene(ctx, r, id)
}

// DeleteScene is the resolver for the deleteScene field.
func (r *mutationResolver) DeleteScene(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteScene(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateAutomation is the resolver for the createAutomation field.
func (r *mutationResolver) CreateAutomation(ctx context.Context, input model.CreateAutomationInput) (*model.AutomationGraph, error) {
	if err := validateAutomationInput(ctx, r.Store, input.Nodes, input.Edges); err != nil {
		return nil, err
	}

	autoID := uuid.New().String()
	_, err := r.Store.CreateAutomation(ctx, store.CreateAutomationParams{
		ID:        autoID,
		Name:      input.Name,
		Enabled:   input.Enabled,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}

	for _, n := range input.Nodes {
		_, err := r.Store.CreateAutomationNode(ctx, store.CreateAutomationNodeParams{
			ID:           n.ID,
			AutomationID: autoID,
			Type:         n.Type,
			Config:       n.Config,
			PositionX:    n.PositionX,
			PositionY:    n.PositionY,
		})
		if err != nil {
			return nil, err
		}
	}

	for _, e := range input.Edges {
		_, err := r.Store.CreateAutomationEdge(ctx, store.CreateAutomationEdgeParams{
			AutomationID: autoID,
			FromNodeID:   e.FromNodeID,
			ToNodeID:     e.ToNodeID,
		})
		if err != nil {
			return nil, err
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, autoID)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// UpdateAutomation is the resolver for the updateAutomation field.
func (r *mutationResolver) UpdateAutomation(ctx context.Context, id string, input model.UpdateAutomationInput) (*model.AutomationGraph, error) {
	_, err := r.Store.GetAutomation(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("automation %q not found: %w", id, err)
	}

	nodes, nodesSet := input.Nodes.ValueOK()
	edges, _ := input.Edges.ValueOK()
	if nodesSet {
		if err := validateAutomationInput(ctx, r.Store, nodes, edges); err != nil {
			return nil, err
		}
	}

	aParams := store.UpdateAutomationParams{}
	updateAutomation := false
	if name, ok := input.Name.ValueOK(); ok {
		aParams.Name = name
		updateAutomation = true
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		aParams.SetIcon = true
		aParams.Icon = icon
		updateAutomation = true
	}
	if enabled, ok := input.Enabled.ValueOK(); ok {
		aParams.Enabled = enabled
		updateAutomation = true
	}
	if updateAutomation {
		if _, err := r.Store.UpdateAutomation(ctx, id, aParams); err != nil {
			return nil, err
		}
	}

	if nodesSet {
		nodeParams := make([]store.CreateAutomationNodeParams, len(nodes))
		for i, n := range nodes {
			nodeParams[i] = store.CreateAutomationNodeParams{
				ID:           n.ID,
				AutomationID: id,
				Type:         n.Type,
				Config:       n.Config,
				PositionX:    n.PositionX,
				PositionY:    n.PositionY,
			}
		}
		edgeParams := make([]store.CreateAutomationEdgeParams, len(edges))
		for i, e := range edges {
			edgeParams[i] = store.CreateAutomationEdgeParams{
				AutomationID: id,
				FromNodeID:   e.FromNodeID,
				ToNodeID:     e.ToNodeID,
			}
		}
		if err := r.Store.ReplaceAutomationGraph(ctx, id, nodeParams, edgeParams); err != nil {
			return nil, err
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// DeleteAutomation is the resolver for the deleteAutomation field.
func (r *mutationResolver) DeleteAutomation(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteAutomation(ctx, id)
	if err != nil {
		return false, err
	}
	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return false, fmt.Errorf("failed to reload automations: %w", err)
		}
	}
	return true, nil
}

// ToggleAutomation is the resolver for the toggleAutomation field.
func (r *mutationResolver) ToggleAutomation(ctx context.Context, id string, enabled bool) (*model.AutomationGraph, error) {
	err := r.Store.UpdateAutomationEnabled(ctx, id, enabled)
	if err != nil {
		return nil, err
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// FireAutomationTrigger is the resolver for the fireAutomationTrigger field.
func (r *mutationResolver) FireAutomationTrigger(ctx context.Context, automationID string, nodeID string) (bool, error) {
	if r.AutomationTriggerer == nil {
		return false, fmt.Errorf("manual triggers are not configured")
	}
	if err := r.AutomationTriggerer.FireManualTrigger(ctx, automationID, nodeID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	groupID := uuid.New().String()
	params := store.CreateGroupParams{
		ID:        groupID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	}
	if tags, ok := input.Tags.ValueOK(); ok {
		params.Tags = groupTagsFromModel(tags)
	}
	g, err := r.Store.CreateGroup(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, nil), nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, input model.UpdateGroupInput) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("group %q not found: %w", id, err)
	}
	name := g.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	gParams := store.UpdateGroupParams{
		ID:   id,
		Name: name,
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		gParams.SetIcon = true
		gParams.Icon = icon
	}
	if tags, ok := input.Tags.ValueOK(); ok {
		gParams.SetTags = true
		gParams.Tags = groupTagsFromModel(tags)
	}
	g, err = r.Store.UpdateGroup(ctx, gParams)
	if err != nil {
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, members), nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteGroup(ctx, id)
	if err != nil {
		return false, err
	}
	r.publishGroupMembershipChanged()
	r.publishRoomMembershipChanged()
	return true, nil
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, input model.AddGroupMemberInput) (*model.GroupMember, error) {
	memberType := device.GroupMemberType(input.MemberType)
	if memberType != device.GroupMemberDevice && memberType != device.GroupMemberGroup && memberType != device.GroupMemberRoom {
		return nil, fmt.Errorf("invalid member type %q: must be %q, %q, or %q", input.MemberType, device.GroupMemberDevice, device.GroupMemberGroup, device.GroupMemberRoom)
	}

	parent := entityRef{kind: "group", id: input.GroupID}
	switch memberType {
	case device.GroupMemberGroup:
		if err := r.checkCircularDependency(ctx, parent, entityRef{kind: "group", id: input.MemberID}); err != nil {
			return nil, err
		}
	case device.GroupMemberRoom:
		if err := r.checkCircularDependency(ctx, parent, entityRef{kind: "room", id: input.MemberID}); err != nil {
			return nil, err
		}
	}

	memberID := uuid.New().String()
	m, err := r.Store.AddGroupMember(ctx, store.AddGroupMemberParams{
		ID:         memberID,
		GroupID:    input.GroupID,
		MemberType: memberType,
		MemberID:   input.MemberID,
	})
	if err != nil {
		return nil, err
	}
	r.publishGroupMembershipChanged()
	return mapGroupMember(ctx, r.StateReader, r.Store, m), nil
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, id string) (bool, error) {
	err := r.Store.RemoveGroupMember(ctx, id)
	if err != nil {
		return false, err
	}
	r.publishGroupMembershipChanged()
	return true, nil
}

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*model.Room, error) {
	roomID := uuid.New().String()
	rm, err := r.Store.CreateRoom(ctx, store.CreateRoomParams{
		ID:        roomID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}
	r.publishRoomMembershipChanged()
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, id string, input model.UpdateRoomInput) (*model.Room, error) {
	rm, err := r.Store.GetRoom(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("room %q not found: %w", id, err)
	}
	name := rm.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	rParams := store.UpdateRoomParams{
		ID:   id,
		Name: name,
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		rParams.SetIcon = true
		rParams.Icon = icon
	}
	rm, err = r.Store.UpdateRoom(ctx, rParams)
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// DeleteRoom is the resolver for the deleteRoom field.
func (r *mutationResolver) DeleteRoom(ctx context.Context, id string) (bool, error) {
	if err := r.Store.DeleteRoom(ctx, id); err != nil {
		return false, err
	}
	r.publishRoomMembershipChanged()
	return true, nil
}

// AddRoomMember is the resolver for the addRoomMember field.
func (r *mutationResolver) AddRoomMember(ctx context.Context, input model.AddRoomMemberInput) (*model.RoomMember, error) {
	memberType := device.RoomMemberType(input.MemberType)
	if memberType != device.RoomMemberDevice && memberType != device.RoomMemberGroup {
		return nil, fmt.Errorf("%w %q: must be %q or %q", device.ErrInvalidRoomMemberType, input.MemberType, device.RoomMemberDevice, device.RoomMemberGroup)
	}

	if memberType == device.RoomMemberGroup {
		parent := entityRef{kind: "room", id: input.RoomID}
		child := entityRef{kind: "group", id: input.MemberID}
		if err := r.checkCircularDependency(ctx, parent, child); err != nil {
			return nil, err
		}
	}

	memberID := uuid.New().String()
	m, err := r.Store.AddRoomMember(ctx, store.AddRoomMemberParams{
		ID:         memberID,
		RoomID:     input.RoomID,
		MemberType: memberType,
		MemberID:   input.MemberID,
	})
	if err != nil {
		return nil, err
	}
	r.publishRoomMembershipChanged()
	return mapRoomMember(ctx, r.StateReader, r.Store, m), nil
}

// RemoveRoomMember is the resolver for the removeRoomMember field.
func (r *mutationResolver) RemoveRoomMember(ctx context.Context, id string) (bool, error) {
	if err := r.Store.RemoveRoomMember(ctx, id); err != nil {
		return false, err
	}
	r.publishRoomMembershipChanged()
	return true, nil
}

// UpdateMqttConfig is the resolver for the updateMqttConfig field.
func (r *mutationResolver) UpdateMqttConfig(ctx context.Context, input model.MqttConfigInput) (*model.MqttConfig, error) {
	if err := r.Store.UpsertMQTTConfig(ctx, store.MQTTConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWSS:   input.UseWss,
	}); err != nil {
		return nil, err
	}

	if err := r.Reconnector.Reconnect(ctx); err != nil {
		return nil, fmt.Errorf("saved config but failed to reconnect: %w", err)
	}

	return &model.MqttConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWss:   input.UseWss,
	}, nil
}

// TestMqttConnection is the resolver for the testMqttConnection field.
func (r *mutationResolver) TestMqttConnection(ctx context.Context, input model.MqttConfigInput) (*model.ConnectionTestResult, error) {
	client := zigbee.NewPahoClient(zigbee.PahoConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWSS:   input.UseWss,
		ClientID: "saffron-hive-test",
	})

	if err := client.Connect(); err != nil {
		return &model.ConnectionTestResult{
			Success: false,
			Message: err.Error(),
		}, nil
	}
	client.Disconnect(250)

	return &model.ConnectionTestResult{
		Success: true,
		Message: "connected successfully",
	}, nil
}

// UpdateSetting is the resolver for the updateSetting field. Server-internal
// keys (auth.IsInternalSettingKey) are rejected so a caller cannot overwrite
// secrets that the public settings surface intentionally hides — see the doc
// comment on IsInternalSettingKey.
func (r *mutationResolver) UpdateSetting(ctx context.Context, key string, value string) (*model.Setting, error) {
	if auth.IsInternalSettingKey(key) {
		return nil, fmt.Errorf("setting %q is read-only", key)
	}
	if err := r.Store.UpsertSetting(ctx, key, value); err != nil {
		return nil, err
	}

	if key == "log_level" {
		if lvl, ok := logging.ParseLevel(value); ok {
			r.LevelVar.Set(lvl)
		}
	}

	return &model.Setting{Key: key, Value: value}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	u, err := r.Store.GetUserByUsername(ctx, strings.TrimSpace(input.Username))
	if err != nil {
		return nil, fmt.Errorf("invalid username or password")
	}
	if err := auth.VerifyPassword(u.PasswordHash, input.Password); err != nil {
		return nil, fmt.Errorf("invalid username or password")
	}
	return signAuthPayload(r.Auth, u)
}

// CreateInitialUser is the resolver for the createInitialUser field. It is
// allowed only when the users table is empty — this is the first-boot
// bootstrap path reached via /setup.
func (r *mutationResolver) CreateInitialUser(ctx context.Context, input model.CreateInitialUserInput) (*model.AuthPayload, error) {
	count, err := r.Store.CountUsers(ctx)
	if err != nil {
		return nil, err
	}
	if count > 0 {
		return nil, fmt.Errorf("initial user already exists")
	}
	u, err := createUserRow(ctx, r.Store, input.Username, input.Name, input.Password)
	if err != nil {
		return nil, err
	}
	return signAuthPayload(r.Auth, u)
}

// CreateUser is the resolver for the createUser field. Requires an
// authenticated caller. All authenticated users are currently full admins;
// roles will come later.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	if _, ok := auth.UserFromContext(ctx); !ok {
		return nil, fmt.Errorf("authentication required")
	}
	u, err := createUserRow(ctx, r.Store, input.Username, input.Name, input.Password)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// UpdateCurrentUser applies a partial update to the authenticated user's
// profile. Currently covers display name and theme; avatar changes go through
// the POST /api/avatars upload endpoint.
func (r *mutationResolver) UpdateCurrentUser(ctx context.Context, input model.UpdateCurrentUserInput) (*model.User, error) {
	cu, ok := auth.UserFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("authentication required")
	}
	params := store.UpdateUserProfileParams{ID: cu.ID}
	if namePtr, ok := input.Name.ValueOK(); ok && namePtr != nil {
		trimmed := strings.TrimSpace(*namePtr)
		if trimmed == "" {
			return nil, fmt.Errorf("name must not be empty")
		}
		params.Name = &trimmed
	}
	if themePtr, ok := input.Theme.ValueOK(); ok && themePtr != nil {
		s := themeToStore(*themePtr)
		params.Theme = &s
	}
	u, err := r.Store.UpdateUserProfile(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// ChangePassword replaces the authenticated user's password after verifying
// their existing one. The current JWT continues to work until it expires;
// server-side revocation of live tokens is out of scope.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (bool, error) {
	cu, ok := auth.UserFromContext(ctx)
	if !ok {
		return false, fmt.Errorf("authentication required")
	}
	if err := validatePassword(input.NewPassword); err != nil {
		return false, err
	}
	u, err := r.Store.GetUserByID(ctx, cu.ID)
	if err != nil {
		return false, fmt.Errorf("load current user: %w", err)
	}
	if err := auth.VerifyPassword(u.PasswordHash, input.OldPassword); err != nil {
		return false, fmt.Errorf("old password is incorrect")
	}
	hash, err := auth.HashPassword(input.NewPassword)
	if err != nil {
		return false, fmt.Errorf("hash password: %w", err)
	}
	if err := r.Store.UpdateUserPasswordHash(ctx, cu.ID, hash); err != nil {
		return false, err
	}
	return true, nil
}

// ResetUserPassword sets a new password for an arbitrary user, without
// requiring the old one. Every authenticated user is a full admin today
// (roles/permissions are a future patch), so any caller can reset any target.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, id string, newPassword string) (bool, error) {
	if _, ok := auth.UserFromContext(ctx); !ok {
		return false, fmt.Errorf("authentication required")
	}
	if err := validatePassword(newPassword); err != nil {
		return false, err
	}
	if _, err := r.Store.GetUserByID(ctx, id); err != nil {
		return false, fmt.Errorf("load target user: %w", err)
	}
	hash, err := auth.HashPassword(newPassword)
	if err != nil {
		return false, fmt.Errorf("hash password: %w", err)
	}
	if err := r.Store.UpdateUserPasswordHash(ctx, id, hash); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteUser removes a user. Rejects self-delete so the acting admin can't
// lock themselves out. The row's avatar file (if any) is deleted best-effort.
// Creator attribution on scenes/automations/groups/rooms becomes NULL via the
// FK ON DELETE SET NULL configured on those tables.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	cu, ok := auth.UserFromContext(ctx)
	if !ok {
		return false, fmt.Errorf("authentication required")
	}
	if cu.ID == id {
		return false, fmt.Errorf("you cannot delete yourself")
	}
	avatar, err := r.Store.GetUserAvatarPath(ctx, id)
	if err != nil {
		return false, fmt.Errorf("load target user: %w", err)
	}
	if err := r.Store.DeleteUser(ctx, id); err != nil {
		return false, err
	}
	if avatar != nil && *avatar != "" && r.AvatarDir != "" {
		full := filepath.Join(r.AvatarDir, *avatar)
		if rmErr := os.Remove(full); rmErr != nil && !errors.Is(rmErr, os.ErrNotExist) {
			graphLogger.Warn("failed to remove avatar file on user delete", "path", full, "error", rmErr)
		}
	}
	return true, nil
}

// RaiseAlarm is the resolver for the raiseAlarm field.
func (r *mutationResolver) RaiseAlarm(ctx context.Context, input model.RaiseAlarmInput) (*model.Alarm, error) {
	source := ""
	if s, ok := input.Source.ValueOK(); ok && s != nil {
		source = *s
	}
	a, err := r.Alarms.Raise(ctx, alarms.RaiseParams{
		AlarmID:  input.AlarmID,
		Severity: severityFromModel(input.Severity),
		Kind:     kindFromModel(input.Kind),
		Message:  input.Message,
		Source:   source,
	})
	if err != nil {
		return nil, err
	}
	return mapAlarm(a), nil
}

// DeleteAlarm is the resolver for the deleteAlarm field.
func (r *mutationResolver) DeleteAlarm(ctx context.Context, alarmID string) (bool, error) {
	deleted, err := r.Alarms.DeleteByAlarmID(ctx, alarmID)
	if err != nil {
		return false, err
	}
	return deleted, nil
}

// BatchDeleteScenes is the resolver for the batchDeleteScenes field.
func (r *mutationResolver) BatchDeleteScenes(ctx context.Context, ids []string) (int, error) {
	n, err := r.Store.BatchDeleteScenes(ctx, ids)
	if err != nil {
		return 0, err
	}
	return int(n), nil
}

// BatchDeleteAutomations is the resolver for the batchDeleteAutomations field.
func (r *mutationResolver) BatchDeleteAutomations(ctx context.Context, ids []string) (int, error) {
	n, err := r.Store.BatchDeleteAutomations(ctx, ids)
	if err != nil {
		return 0, err
	}
	if n > 0 && r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return 0, fmt.Errorf("failed to reload automations: %w", err)
		}
	}
	return int(n), nil
}

// BatchDeleteGroups is the resolver for the batchDeleteGroups field.
func (r *mutationResolver) BatchDeleteGroups(ctx context.Context, ids []string) (int, error) {
	n, err := r.Store.BatchDeleteGroups(ctx, ids)
	if err != nil {
		return 0, err
	}
	if n > 0 {
		r.publishGroupMembershipChanged()
		r.publishRoomMembershipChanged()
	}
	return int(n), nil
}

// BatchDeleteRooms is the resolver for the batchDeleteRooms field.
func (r *mutationResolver) BatchDeleteRooms(ctx context.Context, ids []string) (int, error) {
	n, err := r.Store.BatchDeleteRooms(ctx, ids)
	if err != nil {
		return 0, err
	}
	if n > 0 {
		r.publishRoomMembershipChanged()
	}
	return int(n), nil
}

// BatchDeleteAlarms is the resolver for the batchDeleteAlarms field.
func (r *mutationResolver) BatchDeleteAlarms(ctx context.Context, alarmIds []string) (int, error) {
	n, err := r.Alarms.BatchDeleteByAlarmIDs(ctx, alarmIds)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// BatchDeleteUsers is the resolver for the batchDeleteUsers field. The
// currently authenticated user is silently filtered out before the store call,
// mirroring the single deleteUser self-protection rule.
func (r *mutationResolver) BatchDeleteUsers(ctx context.Context, ids []string) (int, error) {
	cu, ok := auth.UserFromContext(ctx)
	if !ok {
		return 0, fmt.Errorf("authentication required")
	}
	targetIDs := make([]string, 0, len(ids))
	for _, id := range ids {
		if id == cu.ID {
			continue
		}
		targetIDs = append(targetIDs, id)
	}
	if len(targetIDs) == 0 {
		return 0, nil
	}
	avatars, err := r.Store.GetUserAvatarPathsByIDs(ctx, targetIDs)
	if err != nil {
		return 0, fmt.Errorf("load target users: %w", err)
	}
	n, err := r.Store.BatchDeleteUsers(ctx, targetIDs)
	if err != nil {
		return 0, err
	}
	if r.AvatarDir != "" {
		for _, avatar := range avatars {
			full := filepath.Join(r.AvatarDir, avatar)
			if rmErr := os.Remove(full); rmErr != nil && !errors.Is(rmErr, os.ErrNotExist) {
				graphLogger.Warn("failed to remove avatar file on batch user delete", "path", full, "error", rmErr)
			}
		}
	}
	return int(n), nil
}

// BatchAddRoomMembers is the resolver for the batchAddRoomMembers field.
func (r *mutationResolver) BatchAddRoomMembers(ctx context.Context, roomID string, members []*model.RoomMemberInput) (*model.Room, error) {
	inputs := make([]store.RoomMemberInput, 0, len(members))
	for _, m := range members {
		memberType := device.RoomMemberType(m.MemberType)
		if memberType != device.RoomMemberDevice && memberType != device.RoomMemberGroup {
			return nil, fmt.Errorf("%w %q: must be %q or %q", device.ErrInvalidRoomMemberType, m.MemberType, device.RoomMemberDevice, device.RoomMemberGroup)
		}
		if memberType == device.RoomMemberGroup {
			parent := entityRef{kind: "room", id: roomID}
			child := entityRef{kind: "group", id: m.MemberID}
			if err := r.checkCircularDependency(ctx, parent, child); err != nil {
				return nil, err
			}
		}
		inputs = append(inputs, store.RoomMemberInput{
			MemberType: memberType,
			MemberID:   m.MemberID,
		})
	}
	if _, err := r.Store.BatchAddRoomMembers(ctx, roomID, inputs); err != nil {
		return nil, err
	}
	r.publishRoomMembershipChanged()
	rm, err := r.Store.GetRoom(ctx, roomID)
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// BatchAddGroupDevices is the resolver for the batchAddGroupDevices field.
// Devices already members of the group are silently skipped. Returns the
// updated group.
func (r *mutationResolver) BatchAddGroupDevices(ctx context.Context, groupID string, deviceIds []string) (*model.Group, error) {
	if _, err := r.Store.BatchAddGroupDevices(ctx, groupID, deviceIds); err != nil {
		return nil, err
	}
	g, err := r.Store.GetGroup(ctx, groupID)
	if err != nil {
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, groupID)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, members), nil
}

// CreateEffect is the resolver for the createEffect field.
func (r *mutationResolver) CreateEffect(ctx context.Context, input model.CreateEffectInput) (*model.Effect, error) {
	nativeName := input.NativeName.Value()
	if err := validateEffectInput(input.Kind, nativeName, input.Loop, input.DurationMs, input.Tracks); err != nil {
		return nil, err
	}

	tracks, err := buildEffectTrackInputs(input.Tracks)
	if err != nil {
		return nil, err
	}

	effectID := uuid.New().String()
	if _, err := r.Store.CreateEffect(ctx, store.CreateEffectParams{
		ID:         effectID,
		Name:       input.Name,
		Icon:       input.Icon.Value(),
		Kind:       effectKindFromModel(input.Kind),
		NativeName: nativeName,
		Loop:       input.Loop,
		DurationMs: input.DurationMs,
		CreatedBy:  currentUserID(ctx),
		Tracks:     tracks,
	}); err != nil {
		return nil, err
	}

	row, err := r.Store.GetEffect(ctx, effectID)
	if err != nil {
		return nil, err
	}
	return mapEffect(row), nil
}

// UpdateEffect is the resolver for the updateEffect field.
func (r *mutationResolver) UpdateEffect(ctx context.Context, input model.UpdateEffectInput) (*model.Effect, error) {
	existing, err := r.Store.GetEffect(ctx, input.ID)
	if err != nil {
		return nil, fmt.Errorf("effect %q not found: %w", input.ID, err)
	}

	tracksValue, tracksGiven := input.Tracks.ValueOK()
	if tracksGiven {
		loop := existing.Loop
		if v, ok := input.Loop.ValueOK(); ok && v != nil {
			loop = *v
		}
		duration := existing.DurationMs
		if v, ok := input.DurationMs.ValueOK(); ok && v != nil {
			duration = *v
		}
		nativeName := input.NativeName.Value()
		if err := validateEffectInput(modelKindFromStore(existing.Kind), nativeName, loop, duration, tracksValue); err != nil {
			return nil, err
		}
	}

	params := store.UpdateEffectParams{}
	if name, ok := input.Name.ValueOK(); ok && name != nil {
		params.Name = name
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		params.SetIcon = true
		params.Icon = icon
	}
	if loop, ok := input.Loop.ValueOK(); ok && loop != nil {
		params.Loop = loop
	}
	if duration, ok := input.DurationMs.ValueOK(); ok && duration != nil {
		params.DurationMs = duration
	}
	if nativeName, ok := input.NativeName.ValueOK(); ok {
		params.SetNativeName = true
		params.NativeName = nativeName
	}
	if _, err := r.Store.UpdateEffect(ctx, input.ID, params); err != nil {
		return nil, err
	}

	if tracksGiven {
		newTracks, err := buildEffectTrackInputs(tracksValue)
		if err != nil {
			return nil, err
		}
		if err := r.Store.SaveEffectTracks(ctx, input.ID, newTracks); err != nil {
			return nil, err
		}
	}

	row, err := r.Store.GetEffect(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	return mapEffect(row), nil
}

// DeleteEffect is the resolver for the deleteEffect field.
func (r *mutationResolver) DeleteEffect(ctx context.Context, id string) (bool, error) {
	if err := r.Store.DeleteEffect(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RunEffect is the resolver for the runEffect field.
func (r *mutationResolver) RunEffect(ctx context.Context, effectID string, targetType string, targetID string) (*model.ActiveEffect, error) {
	if r.EffectRunner == nil {
		return nil, errors.New("effect runner is not configured")
	}
	tt := device.TargetType(targetType)
	if tt != device.TargetDevice && tt != device.TargetGroup && tt != device.TargetRoom {
		return nil, fmt.Errorf("invalid target type %q: must be %q, %q, or %q",
			targetType, device.TargetDevice, device.TargetGroup, device.TargetRoom)
	}

	target := effect.Target{Type: tt, ID: targetID}
	if _, err := r.EffectRunner.Start(ctx, effectID, target); err != nil {
		return nil, err
	}

	rows, err := r.Store.ListActiveEffects(ctx)
	if err != nil {
		return nil, fmt.Errorf("list active effects after start: %w", err)
	}
	for _, row := range rows {
		if row.TargetType == string(tt) && row.TargetID == targetID {
			eff, err := r.Store.GetEffect(ctx, row.EffectID)
			if err != nil {
				return nil, fmt.Errorf("load effect %q: %w", row.EffectID, err)
			}
			return mapActiveEffect(row, eff), nil
		}
	}
	return nil, fmt.Errorf("effect run started but no active row found for target %s/%s", targetType, targetID)
}

// RunNativeEffect is the resolver for the runNativeEffect field.
func (r *mutationResolver) RunNativeEffect(ctx context.Context, nativeName string, targetType string, targetID string) (*model.ActiveEffect, error) {
	if r.EffectRunner == nil {
		return nil, errors.New("effect runner is not configured")
	}
	if strings.TrimSpace(nativeName) == "" {
		return nil, errors.New("nativeName must not be empty")
	}
	tt := device.TargetType(targetType)
	if tt != device.TargetDevice && tt != device.TargetGroup && tt != device.TargetRoom {
		return nil, fmt.Errorf("invalid target type %q: must be %q, %q, or %q",
			targetType, device.TargetDevice, device.TargetGroup, device.TargetRoom)
	}

	target := effect.Target{Type: tt, ID: targetID}
	runID, err := r.EffectRunner.StartNative(ctx, nativeName, target)
	if err != nil {
		return nil, err
	}

	displayName := sentenceCase(nativeName)
	nameCopy := nativeName
	return &model.ActiveEffect{
		ID: runID,
		Effect: &model.Effect{
			ID:                   "",
			Name:                 displayName,
			Kind:                 model.EffectKindNative,
			NativeName:           &nameCopy,
			Loop:                 false,
			DurationMs:           0,
			Tracks:               []*model.EffectTrack{},
			RequiredCapabilities: []string{},
			CreatedAt:            time.Now(),
			UpdatedAt:            time.Now(),
		},
		TargetType: string(tt),
		TargetID:   targetID,
		StartedAt:  time.Now(),
		Volatile:   true,
	}, nil
}

// StopEffect is the resolver for the stopEffect field.
func (r *mutationResolver) StopEffect(ctx context.Context, targetType string, targetID string) (bool, error) {
	_ = ctx
	if r.EffectRunner == nil {
		return false, errors.New("effect runner is not configured")
	}
	tt := device.TargetType(targetType)
	if tt != device.TargetDevice && tt != device.TargetGroup && tt != device.TargetRoom {
		return false, fmt.Errorf("invalid target type %q: must be %q, %q, or %q",
			targetType, device.TargetDevice, device.TargetGroup, device.TargetRoom)
	}
	r.EffectRunner.Stop(effect.Target{Type: tt, ID: targetID})
	return true, nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*model.Device, error) {
	devices := r.StateReader.ListDevices()
	result := make([]*model.Device, len(devices))
	for i, d := range devices {
		result[i] = mapDeviceFromReader(r.StateReader, d)
	}
	return result, nil
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*model.Device, error) {
	d, ok := r.StateReader.GetDevice(device.DeviceID(id))
	if !ok {
		return nil, nil
	}
	return mapDeviceFromReader(r.StateReader, d), nil
}

// Scenes is the resolver for the scenes field.
func (r *queryResolver) Scenes(ctx context.Context) ([]*model.Scene, error) {
	scenes, err := r.Store.ListScenes(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Scene, len(scenes))
	for i, s := range scenes {
		actions, err := r.Store.ListSceneActions(ctx, s.ID)
		if err != nil {
			return nil, err
		}
		payloads, err := r.Store.ListSceneDevicePayloads(ctx, s.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapScene(ctx, r.StateReader, r.TargetResolver, r.Store, s, actions, payloads)
	}
	return result, nil
}

// Scene is the resolver for the scene field.
func (r *queryResolver) Scene(ctx context.Context, id string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, err
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}
	payloads, err := r.Store.ListSceneDevicePayloads(ctx, s.ID)
	if err != nil {
		return nil, err
	}
	return mapScene(ctx, r.StateReader, r.TargetResolver, r.Store, s, actions, payloads), nil
}

// Automations is the resolver for the automations field.
func (r *queryResolver) Automations(ctx context.Context) ([]*model.AutomationGraph, error) {
	autos, err := r.Store.ListAutomations(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.AutomationGraph, len(autos))
	for i, a := range autos {
		graph, err := r.Store.GetAutomationGraph(ctx, a.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapAutomationGraph(graph)
	}
	return result, nil
}

// Automation is the resolver for the automation field.
func (r *queryResolver) Automation(ctx context.Context, id string) (*model.AutomationGraph, error) {
	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.Group, error) {
	groups, err := r.Store.ListGroups(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Group, len(groups))
	for i, g := range groups {
		members, err := r.Store.ListGroupMembers(ctx, g.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapGroup(ctx, r.StateReader, r.Store, g, members)
	}
	return result, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, members), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.Store.ListRooms(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Room, len(rooms))
	for i, rm := range rooms {
		result[i] = mapRoom(ctx, r.StateReader, r.Store, rm)
	}
	return result, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	rm, err := r.Store.GetRoom(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// StateHistory is the resolver for the stateHistory field.
func (r *queryResolver) StateHistory(ctx context.Context, filter model.StateHistoryFilter) ([]*model.StateSeries, error) {
	if len(filter.DeviceIds) == 0 {
		return []*model.StateSeries{}, nil
	}

	to := time.Now()
	if toPtr := filter.To.Value(); toPtr != nil {
		to = *toPtr
	}
	from := to.Add(-7 * 24 * time.Hour)
	if fromPtr := filter.From.Value(); fromPtr != nil {
		from = *fromPtr
	}
	if !from.Before(to) {
		return []*model.StateSeries{}, nil
	}

	bucket := 0
	if bPtr := filter.BucketSeconds.Value(); bPtr != nil {
		bucket = *bPtr
	}
	if bucket <= 0 {
		bucket = autoBucketSeconds(to.Sub(from))
	}

	deviceIDs := make([]device.DeviceID, len(filter.DeviceIds))
	for i, id := range filter.DeviceIds {
		deviceIDs[i] = device.DeviceID(id)
	}

	var fields []string
	if fv := filter.Fields.Value(); len(fv) > 0 {
		fields = make([]string, 0, len(fv))
		for _, f := range fv {
			if history.IsKnownField(f) {
				fields = append(fields, f)
			}
		}
	}

	points, err := r.Store.QueryStateHistory(ctx, store.StateHistoryQuery{
		DeviceIDs:     deviceIDs,
		Fields:        fields,
		From:          from,
		To:            to,
		BucketSeconds: bucket,
	})
	if err != nil {
		return nil, err
	}

	type seriesKey struct {
		deviceID string
		field    string
	}
	seriesMap := make(map[seriesKey]*model.StateSeries, 16)
	order := make([]seriesKey, 0, 16)
	for _, p := range points {
		key := seriesKey{deviceID: string(p.DeviceID), field: p.Field}
		series, ok := seriesMap[key]
		if !ok {
			series = &model.StateSeries{
				DeviceID: key.deviceID,
				Field:    key.field,
			}
			seriesMap[key] = series
			order = append(order, key)
		}
		series.Points = append(series.Points, &model.StateSeriesPoint{
			At:    p.At,
			Value: p.Value,
		})
	}
	result := make([]*model.StateSeries, 0, len(order))
	for _, key := range order {
		result = append(result, seriesMap[key])
	}
	return result, nil
}

// StateHistoryFields is the resolver for the stateHistoryFields field.
func (r *queryResolver) StateHistoryFields(ctx context.Context) ([]string, error) {
	out := make([]string, len(history.AllFields))
	copy(out, history.AllFields)
	return out, nil
}

// MqttConfig is the resolver for the mqttConfig field.
func (r *queryResolver) MqttConfig(ctx context.Context) (*model.MqttConfig, error) {
	cfg, err := r.Store.GetMQTTConfig(ctx)
	if err != nil {
		return nil, err
	}
	if cfg == nil {
		return nil, nil
	}
	return &model.MqttConfig{
		Broker:   cfg.Broker,
		Username: cfg.Username,
		Password: cfg.Password,
		UseWss:   cfg.UseWSS,
	}, nil
}

// Settings is the resolver for the settings field. Server-internal keys
// (auth.IsInternalSettingKey) are filtered out so callers cannot exfiltrate
// secrets like the JWT signing key — see the doc comment on IsInternalSettingKey.
func (r *queryResolver) Settings(ctx context.Context) ([]*model.Setting, error) {
	settings, err := r.Store.ListSettings(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Setting, 0, len(settings))
	for _, s := range settings {
		if auth.IsInternalSettingKey(s.Key) {
			continue
		}
		result = append(result, &model.Setting{Key: s.Key, Value: s.Value})
	}
	return result, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, search *string, limit *int) ([]*model.LogEntry, error) {
	entries := r.LogBuffer.Entries()

	var result []*model.LogEntry
	for i := len(entries) - 1; i >= 0; i-- {
		e := entries[i]
		if search != nil && *search != "" {
			if !containsFold(e.Message, *search) && !attrsContainFold(e.Attrs, *search) {
				continue
			}
		}
		result = append(result, mapLogEntry(e))
		if limit != nil && len(result) >= *limit {
			break
		}
	}

	for i, j := 0, len(result)-1; i < j; i, j = i+1, j-1 {
		result[i], result[j] = result[j], result[i]
	}

	return result, nil
}

// Activity is the resolver for the activity field.
func (r *queryResolver) Activity(ctx context.Context, filter *model.ActivityFilter) ([]*model.ActivityEvent, error) {
	q := store.ActivityQuery{Limit: 500}
	if filter != nil {
		if types, ok := filter.Types.ValueOK(); ok {
			q.Types = types
		}
		if did, ok := filter.DeviceID.ValueOK(); ok && did != nil {
			q.DeviceID = did
		}
		if rid, ok := filter.RoomID.ValueOK(); ok && rid != nil {
			q.RoomID = rid
		}
		if since, ok := filter.Since.ValueOK(); ok && since != nil {
			q.Since = since
		}
		if adv, ok := filter.Advanced.ValueOK(); ok && adv != nil {
			q.Advanced = *adv
		}
		if lim, ok := filter.Limit.ValueOK(); ok && lim != nil && *lim > 0 {
			q.Limit = *lim
		}
		if before, ok := filter.Before.ValueOK(); ok && before != nil && *before != "" {
			n, err := strconv.ParseInt(*before, 10, 64)
			if err != nil {
				return nil, fmt.Errorf("invalid before cursor %q: %w", *before, err)
			}
			q.Before = &n
		}
	}
	rows, err := r.Store.QueryActivityEvents(ctx, q)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ActivityEvent, len(rows))
	for i, row := range rows {
		result[i] = mapActivityEvent(row)
	}
	return result, nil
}

// Alarms is the resolver for the alarms field. Returns grouped alarms ordered
// most-recently-raised first. Filtering is performed in Go over the grouped
// projection so the frontend can freely combine severity/kind/source/since
// without the SQL layer having to understand grouping.
func (r *queryResolver) Alarms(ctx context.Context, filter *model.AlarmFilter) ([]*model.Alarm, error) {
	list, err := r.Resolver.Alarms.ListActive(ctx)
	if err != nil {
		return nil, err
	}

	var (
		wantSeverities map[store.AlarmSeverity]struct{}
		wantKinds      map[store.AlarmKind]struct{}
		wantSources    map[string]struct{}
		since          *time.Time
	)
	if filter != nil {
		if sevs, ok := filter.Severities.ValueOK(); ok && len(sevs) > 0 {
			wantSeverities = make(map[store.AlarmSeverity]struct{}, len(sevs))
			for _, s := range sevs {
				wantSeverities[severityFromModel(s)] = struct{}{}
			}
		}
		if ks, ok := filter.Kinds.ValueOK(); ok && len(ks) > 0 {
			wantKinds = make(map[store.AlarmKind]struct{}, len(ks))
			for _, k := range ks {
				wantKinds[kindFromModel(k)] = struct{}{}
			}
		}
		if srcs, ok := filter.Sources.ValueOK(); ok && len(srcs) > 0 {
			wantSources = make(map[string]struct{}, len(srcs))
			for _, s := range srcs {
				wantSources[s] = struct{}{}
			}
		}
		if t, ok := filter.Since.ValueOK(); ok {
			since = t
		}
	}

	result := make([]*model.Alarm, 0, len(list))
	for _, a := range list {
		if wantSeverities != nil {
			if _, ok := wantSeverities[a.Severity]; !ok {
				continue
			}
		}
		if wantKinds != nil {
			if _, ok := wantKinds[a.Kind]; !ok {
				continue
			}
		}
		if wantSources != nil {
			if _, ok := wantSources[a.Source]; !ok {
				continue
			}
		}
		if since != nil && a.LastRaisedAt.Before(*since) {
			continue
		}
		result = append(result, mapAlarm(a))
	}
	return result, nil
}

// SetupStatus is the resolver for the setupStatus field. Whitelisted — callable
// without authentication so the frontend can decide whether to show /setup.
func (r *queryResolver) SetupStatus(ctx context.Context) (*model.SetupStatus, error) {
	count, err := r.Store.CountUsers(ctx)
	if err != nil {
		return nil, err
	}
	mqtt, err := r.Store.GetMQTTConfig(ctx)
	if err != nil {
		return nil, err
	}
	return &model.SetupStatus{
		HasInitialUser: count > 0,
		MqttConfigured: mqtt != nil && mqtt.Broker != "",
	}, nil
}

// Me is the resolver for the me field. Returns nil when unauthenticated. The
// full row is loaded from the DB so avatar / theme / name updates take effect
// without requiring the client to re-authenticate.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	cu, ok := auth.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}
	u, err := r.Store.GetUserByID(ctx, cu.ID)
	if err != nil {
		return nil, fmt.Errorf("load current user: %w", err)
	}
	return mapUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.Store.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = mapUser(u)
	}
	return result, nil
}

// Effects is the resolver for the effects field. Native rows are filtered
// out: built-in firmware effects surface through Query.nativeEffectOptions
// instead, so the user-facing Effects list only carries timeline effects.
func (r *queryResolver) Effects(ctx context.Context) ([]*model.Effect, error) {
	rows, err := r.Store.ListEffects(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Effect, 0, len(rows))
	for _, row := range rows {
		if row.Kind == effect.KindNative {
			continue
		}
		out = append(out, mapEffect(row))
	}
	return out, nil
}

// Effect is the resolver for the effect field.
func (r *queryResolver) Effect(ctx context.Context, id string) (*model.Effect, error) {
	row, err := r.Store.GetEffect(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapEffect(row), nil
}

// ActiveEffects is the resolver for the activeEffects field.
func (r *queryResolver) ActiveEffects(ctx context.Context) ([]*model.ActiveEffect, error) {
	rows, err := r.Store.ListActiveEffects(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ActiveEffect, 0, len(rows))
	for _, row := range rows {
		eff, err := r.Store.GetEffect(ctx, row.EffectID)
		if err != nil {
			graphLogger.Warn("active effect references missing effect, skipping",
				"run_id", row.ID, "effect_id", row.EffectID, "error", err)
			continue
		}
		out = append(out, mapActiveEffect(row, eff))
	}
	return out, nil
}

// NativeEffectOptions is the resolver for the nativeEffectOptions field.
func (r *queryResolver) NativeEffectOptions(ctx context.Context) ([]*model.NativeEffectOption, error) {
	terminators := make(map[string]struct{}, len(nativeEffectTerminators))
	for _, t := range nativeEffectTerminators {
		terminators[t] = struct{}{}
	}

	counts := make(map[string]int)
	for _, d := range r.StateReader.ListDevices() {
		for _, c := range d.Capabilities {
			if c.Name != device.CapEffect {
				continue
			}
			seenInDevice := make(map[string]struct{}, len(c.Values))
			for _, v := range c.Values {
				if _, ok := terminators[v]; ok {
					continue
				}
				if _, dup := seenInDevice[v]; dup {
					continue
				}
				seenInDevice[v] = struct{}{}
				counts[v]++
			}
		}
	}

	out := make([]*model.NativeEffectOption, 0, len(counts))
	for name, count := range counts {
		out = append(out, &model.NativeEffectOption{
			Name:                 name,
			DisplayName:          sentenceCase(name),
			SupportedDeviceCount: count,
		})
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Name < out[j].Name
	})
	return out, nil
}

// DeviceStateChanged is the resolver for the deviceStateChanged field.
func (r *subscriptionResolver) DeviceStateChanged(ctx context.Context, deviceID *string) (<-chan *model.DeviceStateEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceStateChanged)
	out := make(chan *model.DeviceStateEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				if deviceID != nil && evt.DeviceID != *deviceID {
					continue
				}
				state := resolveDeviceStateFromReader(r.StateReader, device.DeviceID(evt.DeviceID))
				if state == nil {
					continue
				}
				select {
				case out <- &model.DeviceStateEvent{
					DeviceID: evt.DeviceID,
					State:    state,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceActionFired is the resolver for the deviceActionFired field.
func (r *subscriptionResolver) DeviceActionFired(ctx context.Context, deviceID *string) (<-chan *model.DeviceActionEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceActionFired)
	out := make(chan *model.DeviceActionEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				if deviceID != nil && evt.DeviceID != *deviceID {
					continue
				}
				action, ok := evt.Payload.(device.Action)
				if !ok || action.Action == "" {
					continue
				}
				select {
				case out <- &model.DeviceActionEvent{
					DeviceID: evt.DeviceID,
					Action:   action.Action,
					FiredAt:  evt.Timestamp,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAvailabilityChanged is the resolver for the deviceAvailabilityChanged field.
func (r *subscriptionResolver) DeviceAvailabilityChanged(ctx context.Context) (<-chan *model.DeviceAvailabilityEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAvailabilityChanged)
	out := make(chan *model.DeviceAvailabilityEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				select {
				case out <- &model.DeviceAvailabilityEvent{
					DeviceID:  evt.DeviceID,
					Available: d.Available,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAdded is the resolver for the deviceAdded field.
func (r *subscriptionResolver) DeviceAdded(ctx context.Context) (<-chan *model.Device, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAdded)
	out := make(chan *model.Device, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				md := mapDeviceFromReader(r.StateReader, d)
				select {
				case out <- md:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceRemoved is the resolver for the deviceRemoved field.
func (r *subscriptionResolver) DeviceRemoved(ctx context.Context) (<-chan string, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceRemoved)
	out := make(chan string, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- evt.DeviceID:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// AutomationNodeActivated is the resolver for the automationNodeActivated field.
func (r *subscriptionResolver) AutomationNodeActivated(ctx context.Context, automationID *string) (<-chan *model.AutomationNodeActivationEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventAutomationNodeActivated)
	out := make(chan *model.AutomationNodeActivationEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				na, ok := evt.Payload.(automation.NodeActivation)
				if !ok {
					continue
				}
				if automationID != nil && na.AutomationID != *automationID {
					continue
				}
				select {
				case out <- &model.AutomationNodeActivationEvent{
					AutomationID: na.AutomationID,
					NodeID:       string(na.NodeID),
					Active:       na.Active,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// SceneActiveChanged is the resolver for the sceneActiveChanged field.
func (r *subscriptionResolver) SceneActiveChanged(ctx context.Context) (<-chan *model.SceneActiveEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventSceneActivated, eventbus.EventSceneDeactivated)
	out := make(chan *model.SceneActiveEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				a, ok := evt.Payload.(scene.ActivationEvent)
				if !ok {
					continue
				}
				select {
				case out <- &model.SceneActiveEvent{
					SceneID:     a.SceneID,
					ActivatedAt: a.ActivatedAt,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// LogStream is the resolver for the logStream field.
func (r *subscriptionResolver) LogStream(ctx context.Context) (<-chan *model.LogEntry, error) {
	ch, unsub := r.LogBuffer.Subscribe()
	out := make(chan *model.LogEntry, 1)

	go func() {
		defer close(out)
		defer unsub()

		for {
			select {
			case <-ctx.Done():
				return
			case e, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- mapLogEntry(e):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// ActivityStream is the resolver for the activityStream field.
func (r *subscriptionResolver) ActivityStream(ctx context.Context, advanced *bool) (<-chan *model.ActivityEvent, error) {
	showAdvanced := advanced != nil && *advanced

	ch, unsub := r.ActivityBuffer.Subscribe()
	out := make(chan *model.ActivityEvent, 16)

	go func() {
		defer close(out)
		defer unsub()

		for {
			select {
			case <-ctx.Done():
				return
			case row, ok := <-ch:
				if !ok {
					return
				}
				if !showAdvanced && (row.Type == "command.requested" || row.Type == "automation.node_activated") {
					continue
				}
				select {
				case out <- mapActivityEvent(row):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// AlarmEvent is the resolver for the alarmEvent field.
func (r *subscriptionResolver) AlarmEvent(ctx context.Context) (<-chan *model.AlarmEvent, error) {
	ch, unsub := r.AlarmBuffer.Subscribe()
	out := make(chan *model.AlarmEvent, 16)

	go func() {
		defer close(out)
		defer unsub()

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- mapAlarmEvent(evt):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// EffectStepActivated is the resolver for the effectStepActivated field.
func (r *subscriptionResolver) EffectStepActivated(ctx context.Context, runID *string) (<-chan *model.EffectStepEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventEffectStepActivated)
	out := make(chan *model.EffectStepEvent, 16)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				payload, ok := evt.Payload.(eventbus.EffectStepActivatedEvent)
				if !ok {
					continue
				}
				if runID != nil && payload.RunID != *runID {
					continue
				}
				select {
				case out <- &model.EffectStepEvent{
					RunID:     payload.RunID,
					EffectID:  payload.EffectID,
					StepIndex: payload.StepIndex,
					Active:    payload.Active,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
