package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/saffronjam/saffron-hive/internal/adapter/zigbee"
	"github.com/saffronjam/saffron-hive/internal/auth"
	"github.com/saffronjam/saffron-hive/internal/automation"
	"github.com/saffronjam/saffron-hive/internal/device"
	"github.com/saffronjam/saffron-hive/internal/eventbus"
	"github.com/saffronjam/saffron-hive/internal/graph/model"
	"github.com/saffronjam/saffron-hive/internal/logging"
	"github.com/saffronjam/saffron-hive/internal/store"
)

// UpdateDevice is the resolver for the updateDevice field.
func (r *mutationResolver) UpdateDevice(ctx context.Context, id string, input model.UpdateDeviceInput) (*model.Device, error) {
	deviceID := device.DeviceID(id)
	d, err := r.Store.GetDevice(ctx, deviceID)
	if err != nil {
		return nil, fmt.Errorf("device %q not found: %w", id, err)
	}
	name := d.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	d, err = r.Store.UpdateDevice(ctx, store.UpdateDeviceParams{
		ID:        deviceID,
		Name:      name,
		Available: d.Available,
		Removed:   d.Removed,
		LastSeen:  d.LastSeen,
	})
	if err != nil {
		return nil, err
	}
	return mapDeviceFromReader(r.StateReader, d), nil
}

// SetDeviceState is the resolver for the setDeviceState field.
func (r *mutationResolver) SetDeviceState(ctx context.Context, deviceID string, state model.LightStateInput) (*model.Device, error) {
	id := device.DeviceID(deviceID)
	d, ok := r.StateReader.GetDevice(id)
	if !ok {
		return nil, fmt.Errorf("device %q not found", deviceID)
	}

	cmd := device.LightCommand{
		On:         state.On.Value(),
		Brightness: state.Brightness.Value(),
		ColorTemp:  state.ColorTemp.Value(),
		Transition: state.Transition.Value(),
	}
	if color := state.Color.Value(); color != nil {
		cmd.Color = &device.Color{
			R: color.R,
			G: color.G,
			B: color.B,
			X: color.X,
			Y: color.Y,
		}
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventCommandRequested,
		DeviceID:  deviceID,
		Timestamp: time.Now(),
		Payload:   device.DeviceCommand{DeviceID: id, Payload: cmd},
	})

	return mapDeviceFromReader(r.StateReader, d), nil
}

// ApplyScene is the resolver for the applyScene field.
func (r *mutationResolver) ApplyScene(ctx context.Context, sceneID string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, sceneID)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", sceneID, err)
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}

	for _, sa := range actions {
		var desired map[string]interface{}
		if err := json.Unmarshal([]byte(sa.Payload), &desired); err != nil {
			continue
		}
		deviceIDs := resolveSceneActionTargetDevices(ctx, r.TargetResolver, sa.TargetType, sa.TargetID)
		for _, did := range deviceIDs {
			cmd := device.DeviceCommand{
				DeviceID: did,
				Payload:  buildLightCommandFromMap(desired),
			}
			r.EventBus.Publish(eventbus.Event{
				Type:      eventbus.EventCommandRequested,
				DeviceID:  string(did),
				Timestamp: time.Now(),
				Payload:   cmd,
			})
		}
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventSceneApplied,
		Timestamp: time.Now(),
		Payload:   sceneID,
	})

	return mapScene(ctx, r.StateReader, r.Store, s, actions), nil
}

// CreateScene is the resolver for the createScene field.
func (r *mutationResolver) CreateScene(ctx context.Context, input model.CreateSceneInput) (*model.Scene, error) {
	sceneID := uuid.New().String()
	s, err := r.Store.CreateScene(ctx, store.CreateSceneParams{
		ID:        sceneID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}

	var storeActions []store.SceneAction
	for _, a := range input.Actions {
		actionID := uuid.New().String()
		sa, err := r.Store.CreateSceneAction(ctx, store.CreateSceneActionParams{
			ID:         actionID,
			SceneID:    sceneID,
			TargetType: a.TargetType,
			TargetID:   a.TargetID,
			Payload:    a.Payload,
		})
		if err != nil {
			return nil, err
		}
		storeActions = append(storeActions, sa)
	}

	return mapScene(ctx, r.StateReader, r.Store, s, storeActions), nil
}

// UpdateScene is the resolver for the updateScene field.
func (r *mutationResolver) UpdateScene(ctx context.Context, id string, input model.UpdateSceneInput) (*model.Scene, error) {
	_, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", id, err)
	}

	params := store.UpdateSceneParams{}
	updateScene := false
	if name, ok := input.Name.ValueOK(); ok {
		params.Name = name
		updateScene = true
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		params.SetIcon = true
		params.Icon = icon
		updateScene = true
	}
	if updateScene {
		if _, err := r.Store.UpdateScene(ctx, id, params); err != nil {
			return nil, err
		}
	}

	if newActions, ok := input.Actions.ValueOK(); ok {
		existingActions, err := r.Store.ListSceneActions(ctx, id)
		if err != nil {
			return nil, err
		}
		for _, ea := range existingActions {
			if err := r.Store.DeleteSceneAction(ctx, ea.ID); err != nil {
				return nil, err
			}
		}
		for _, a := range newActions {
			actionID := uuid.New().String()
			_, err := r.Store.CreateSceneAction(ctx, store.CreateSceneActionParams{
				ID:         actionID,
				SceneID:    id,
				TargetType: a.TargetType,
				TargetID:   a.TargetID,
				Payload:    a.Payload,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	s, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, err
	}
	actions, err := r.Store.ListSceneActions(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapScene(ctx, r.StateReader, r.Store, s, actions), nil
}

// DeleteScene is the resolver for the deleteScene field.
func (r *mutationResolver) DeleteScene(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteScene(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateAutomation is the resolver for the createAutomation field.
func (r *mutationResolver) CreateAutomation(ctx context.Context, input model.CreateAutomationInput) (*model.AutomationGraph, error) {
	if err := validateAutomationInput(input.Nodes, input.Edges); err != nil {
		return nil, err
	}

	autoID := uuid.New().String()
	_, err := r.Store.CreateAutomation(ctx, store.CreateAutomationParams{
		ID:              autoID,
		Name:            input.Name,
		Enabled:         input.Enabled,
		CooldownSeconds: input.CooldownSeconds,
		CreatedBy:       currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}

	for _, n := range input.Nodes {
		_, err := r.Store.CreateAutomationNode(ctx, store.CreateAutomationNodeParams{
			ID:           n.ID,
			AutomationID: autoID,
			Type:         n.Type,
			Config:       n.Config,
		})
		if err != nil {
			return nil, err
		}
	}

	for _, e := range input.Edges {
		edgeID := uuid.New().String()
		_, err := r.Store.CreateAutomationEdge(ctx, store.CreateAutomationEdgeParams{
			ID:           edgeID,
			AutomationID: autoID,
			FromNodeID:   e.FromNodeID,
			ToNodeID:     e.ToNodeID,
		})
		if err != nil {
			return nil, err
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, autoID)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// UpdateAutomation is the resolver for the updateAutomation field.
func (r *mutationResolver) UpdateAutomation(ctx context.Context, id string, input model.UpdateAutomationInput) (*model.AutomationGraph, error) {
	_, err := r.Store.GetAutomation(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("automation %q not found: %w", id, err)
	}

	nodes, nodesSet := input.Nodes.ValueOK()
	edges, _ := input.Edges.ValueOK()
	if nodesSet {
		if err := validateAutomationInput(nodes, edges); err != nil {
			return nil, err
		}
	}

	aParams := store.UpdateAutomationParams{}
	updateAutomation := false
	if name, ok := input.Name.ValueOK(); ok {
		aParams.Name = name
		updateAutomation = true
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		aParams.SetIcon = true
		aParams.Icon = icon
		updateAutomation = true
	}
	if enabled, ok := input.Enabled.ValueOK(); ok {
		aParams.Enabled = enabled
		updateAutomation = true
	}
	if cooldown, ok := input.CooldownSeconds.ValueOK(); ok {
		aParams.CooldownSeconds = cooldown
		updateAutomation = true
	}
	if updateAutomation {
		if _, err := r.Store.UpdateAutomation(ctx, id, aParams); err != nil {
			return nil, err
		}
	}

	if nodesSet {
		existingNodes, err := r.Store.ListAutomationNodes(ctx, id)
		if err != nil {
			return nil, err
		}
		for _, en := range existingNodes {
			if err := r.Store.DeleteAutomationNode(ctx, en.ID); err != nil {
				return nil, err
			}
		}
		for _, n := range nodes {
			_, err := r.Store.CreateAutomationNode(ctx, store.CreateAutomationNodeParams{
				ID:           n.ID,
				AutomationID: id,
				Type:         n.Type,
				Config:       n.Config,
			})
			if err != nil {
				return nil, err
			}
		}

		for _, e := range edges {
			edgeID := uuid.New().String()
			_, err := r.Store.CreateAutomationEdge(ctx, store.CreateAutomationEdgeParams{
				ID:           edgeID,
				AutomationID: id,
				FromNodeID:   e.FromNodeID,
				ToNodeID:     e.ToNodeID,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// DeleteAutomation is the resolver for the deleteAutomation field.
func (r *mutationResolver) DeleteAutomation(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteAutomation(ctx, id)
	if err != nil {
		return false, err
	}
	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return false, fmt.Errorf("failed to reload automations: %w", err)
		}
	}
	return true, nil
}

// ToggleAutomation is the resolver for the toggleAutomation field.
func (r *mutationResolver) ToggleAutomation(ctx context.Context, id string, enabled bool) (*model.AutomationGraph, error) {
	err := r.Store.UpdateAutomationEnabled(ctx, id, enabled)
	if err != nil {
		return nil, err
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	groupID := uuid.New().String()
	g, err := r.Store.CreateGroup(ctx, store.CreateGroupParams{
		ID:        groupID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, nil), nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, input model.UpdateGroupInput) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("group %q not found: %w", id, err)
	}
	name := g.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	gParams := store.UpdateGroupParams{
		ID:   id,
		Name: name,
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		gParams.SetIcon = true
		gParams.Icon = icon
	}
	g, err = r.Store.UpdateGroup(ctx, gParams)
	if err != nil {
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, members), nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteGroup(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, input model.AddGroupMemberInput) (*model.GroupMember, error) {
	memberType := device.GroupMemberType(input.MemberType)
	if memberType != device.GroupMemberDevice && memberType != device.GroupMemberGroup && memberType != device.GroupMemberRoom {
		return nil, fmt.Errorf("invalid member type %q: must be %q, %q, or %q", input.MemberType, device.GroupMemberDevice, device.GroupMemberGroup, device.GroupMemberRoom)
	}

	if memberType == device.GroupMemberGroup {
		if err := r.checkCircularDependency(ctx, input.GroupID, input.MemberID); err != nil {
			return nil, err
		}
	}

	memberID := uuid.New().String()
	m, err := r.Store.AddGroupMember(ctx, store.AddGroupMemberParams{
		ID:         memberID,
		GroupID:    input.GroupID,
		MemberType: memberType,
		MemberID:   input.MemberID,
	})
	if err != nil {
		return nil, err
	}
	return mapGroupMember(ctx, r.StateReader, r.Store, m), nil
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, id string) (bool, error) {
	err := r.Store.RemoveGroupMember(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*model.Room, error) {
	roomID := uuid.New().String()
	rm, err := r.Store.CreateRoom(ctx, store.CreateRoomParams{
		ID:        roomID,
		Name:      input.Name,
		CreatedBy: currentUserID(ctx),
	})
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, id string, input model.UpdateRoomInput) (*model.Room, error) {
	rm, err := r.Store.GetRoom(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("room %q not found: %w", id, err)
	}
	name := rm.Name
	if n, ok := input.Name.ValueOK(); ok && n != nil {
		name = *n
	}
	rParams := store.UpdateRoomParams{
		ID:   id,
		Name: name,
	}
	if icon, ok := input.Icon.ValueOK(); ok {
		rParams.SetIcon = true
		rParams.Icon = icon
	}
	rm, err = r.Store.UpdateRoom(ctx, rParams)
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// DeleteRoom is the resolver for the deleteRoom field.
func (r *mutationResolver) DeleteRoom(ctx context.Context, id string) (bool, error) {
	if err := r.Store.DeleteRoom(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// AddRoomDevice is the resolver for the addRoomDevice field.
func (r *mutationResolver) AddRoomDevice(ctx context.Context, input model.AddRoomDeviceInput) (*model.Room, error) {
	memberID := uuid.New().String()
	_, err := r.Store.AddRoomDevice(ctx, store.AddRoomDeviceParams{
		ID:       memberID,
		RoomID:   input.RoomID,
		DeviceID: input.DeviceID,
	})
	if err != nil {
		return nil, err
	}
	rm, err := r.Store.GetRoom(ctx, input.RoomID)
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// RemoveRoomDevice is the resolver for the removeRoomDevice field.
func (r *mutationResolver) RemoveRoomDevice(ctx context.Context, roomID string, deviceID string) (*model.Room, error) {
	if err := r.Store.RemoveRoomDeviceByRoomAndDevice(ctx, roomID, deviceID); err != nil {
		return nil, err
	}
	rm, err := r.Store.GetRoom(ctx, roomID)
	if err != nil {
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// UpdateMqttConfig is the resolver for the updateMqttConfig field.
func (r *mutationResolver) UpdateMqttConfig(ctx context.Context, input model.MqttConfigInput) (*model.MqttConfig, error) {
	if err := r.Store.UpsertMQTTConfig(ctx, store.MQTTConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWSS:   input.UseWss,
	}); err != nil {
		return nil, err
	}

	if err := r.Reconnector.Reconnect(ctx); err != nil {
		return nil, fmt.Errorf("saved config but failed to reconnect: %w", err)
	}

	return &model.MqttConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWss:   input.UseWss,
	}, nil
}

// TestMqttConnection is the resolver for the testMqttConnection field.
func (r *mutationResolver) TestMqttConnection(ctx context.Context, input model.MqttConfigInput) (*model.ConnectionTestResult, error) {
	client := zigbee.NewPahoClient(zigbee.PahoConfig{
		Broker:   input.Broker,
		Username: input.Username,
		Password: input.Password,
		UseWSS:   input.UseWss,
		ClientID: "saffron-hive-test",
	})

	if err := client.Connect(); err != nil {
		return &model.ConnectionTestResult{
			Success: false,
			Message: err.Error(),
		}, nil
	}
	client.Disconnect(250)

	return &model.ConnectionTestResult{
		Success: true,
		Message: "connected successfully",
	}, nil
}

// UpdateSetting is the resolver for the updateSetting field.
func (r *mutationResolver) UpdateSetting(ctx context.Context, key string, value string) (*model.Setting, error) {
	if err := r.Store.UpsertSetting(ctx, key, value); err != nil {
		return nil, err
	}

	if key == "log_level" {
		if lvl, ok := logging.ParseLevel(value); ok {
			r.LevelVar.Set(lvl)
		}
	}

	return &model.Setting{Key: key, Value: value}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	u, err := r.Store.GetUserByUsername(ctx, strings.TrimSpace(input.Username))
	if err != nil {
		return nil, fmt.Errorf("invalid username or password")
	}
	if err := auth.VerifyPassword(u.PasswordHash, input.Password); err != nil {
		return nil, fmt.Errorf("invalid username or password")
	}
	return signAuthPayload(r.Auth, u)
}

// CreateInitialUser is the resolver for the createInitialUser field. It is
// allowed only when the users table is empty — this is the first-boot
// bootstrap path reached via /setup.
func (r *mutationResolver) CreateInitialUser(ctx context.Context, input model.CreateInitialUserInput) (*model.AuthPayload, error) {
	count, err := r.Store.CountUsers(ctx)
	if err != nil {
		return nil, err
	}
	if count > 0 {
		return nil, fmt.Errorf("initial user already exists")
	}
	u, err := createUserRow(ctx, r.Store, input.Username, input.Name, input.Password)
	if err != nil {
		return nil, err
	}
	return signAuthPayload(r.Auth, u)
}

// CreateUser is the resolver for the createUser field. Requires an
// authenticated caller. All authenticated users are currently full admins;
// roles will come later.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	if _, ok := auth.UserFromContext(ctx); !ok {
		return nil, fmt.Errorf("authentication required")
	}
	u, err := createUserRow(ctx, r.Store, input.Username, input.Name, input.Password)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*model.Device, error) {
	devices := r.StateReader.ListDevices()
	result := make([]*model.Device, len(devices))
	for i, d := range devices {
		result[i] = mapDeviceFromReader(r.StateReader, d)
	}
	return result, nil
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*model.Device, error) {
	d, ok := r.StateReader.GetDevice(device.DeviceID(id))
	if !ok {
		return nil, nil
	}
	return mapDeviceFromReader(r.StateReader, d), nil
}

// Scenes is the resolver for the scenes field.
func (r *queryResolver) Scenes(ctx context.Context) ([]*model.Scene, error) {
	scenes, err := r.Store.ListScenes(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Scene, len(scenes))
	for i, s := range scenes {
		actions, err := r.Store.ListSceneActions(ctx, s.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapScene(ctx, r.StateReader, r.Store, s, actions)
	}
	return result, nil
}

// Scene is the resolver for the scene field.
func (r *queryResolver) Scene(ctx context.Context, id string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, err
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}
	return mapScene(ctx, r.StateReader, r.Store, s, actions), nil
}

// Automations is the resolver for the automations field.
func (r *queryResolver) Automations(ctx context.Context) ([]*model.AutomationGraph, error) {
	autos, err := r.Store.ListAutomations(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.AutomationGraph, len(autos))
	for i, a := range autos {
		graph, err := r.Store.GetAutomationGraph(ctx, a.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapAutomationGraph(graph)
	}
	return result, nil
}

// Automation is the resolver for the automation field.
func (r *queryResolver) Automation(ctx context.Context, id string) (*model.AutomationGraph, error) {
	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.Group, error) {
	groups, err := r.Store.ListGroups(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Group, len(groups))
	for i, g := range groups {
		members, err := r.Store.ListGroupMembers(ctx, g.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapGroup(ctx, r.StateReader, r.Store, g, members)
	}
	return result, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(ctx, r.StateReader, r.Store, g, members), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.Store.ListRooms(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Room, len(rooms))
	for i, rm := range rooms {
		result[i] = mapRoom(ctx, r.StateReader, r.Store, rm)
	}
	return result, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	rm, err := r.Store.GetRoom(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(ctx, r.StateReader, r.Store, rm), nil
}

// SensorHistory is the resolver for the sensorHistory field.
func (r *queryResolver) SensorHistory(ctx context.Context, deviceID string, from *time.Time, to *time.Time, limit *int) ([]*model.SensorReading, error) {
	q := store.SensorHistoryQuery{
		DeviceID: device.DeviceID(deviceID),
		From:     time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
		To:       time.Now().Add(24 * time.Hour),
	}
	if from != nil {
		q.From = *from
	}
	if to != nil {
		q.To = *to
	}
	if limit != nil {
		q.Limit = *limit
	}
	readings, err := r.Store.QuerySensorHistory(ctx, q)
	if err != nil {
		return nil, err
	}
	result := make([]*model.SensorReading, len(readings))
	for i, rd := range readings {
		result[i] = &model.SensorReading{
			ID:          strconv.FormatInt(rd.ID, 10),
			DeviceID:    string(rd.DeviceID),
			Temperature: rd.Temperature,
			Humidity:    rd.Humidity,
			Battery:     rd.Battery,
			Pressure:    rd.Pressure,
			Illuminance: rd.Illuminance,
			RecordedAt:  rd.RecordedAt,
		}
	}
	return result, nil
}

// MqttConfig is the resolver for the mqttConfig field.
func (r *queryResolver) MqttConfig(ctx context.Context) (*model.MqttConfig, error) {
	cfg, err := r.Store.GetMQTTConfig(ctx)
	if err != nil {
		return nil, err
	}
	if cfg == nil {
		return nil, nil
	}
	return &model.MqttConfig{
		Broker:   cfg.Broker,
		Username: cfg.Username,
		Password: cfg.Password,
		UseWss:   cfg.UseWSS,
	}, nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) ([]*model.Setting, error) {
	settings, err := r.Store.ListSettings(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Setting, len(settings))
	for i, s := range settings {
		result[i] = &model.Setting{Key: s.Key, Value: s.Value}
	}
	return result, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, search *string, limit *int) ([]*model.LogEntry, error) {
	entries := r.LogBuffer.Entries()

	var result []*model.LogEntry
	for i := len(entries) - 1; i >= 0; i-- {
		e := entries[i]
		if search != nil && *search != "" {
			if !containsFold(e.Message, *search) && !attrsContainFold(e.Attrs, *search) {
				continue
			}
		}
		result = append(result, mapLogEntry(e))
		if limit != nil && len(result) >= *limit {
			break
		}
	}

	for i, j := 0, len(result)-1; i < j; i, j = i+1, j-1 {
		result[i], result[j] = result[j], result[i]
	}

	return result, nil
}

// Activity is the resolver for the activity field.
func (r *queryResolver) Activity(ctx context.Context, filter *model.ActivityFilter) ([]*model.ActivityEvent, error) {
	q := store.ActivityQuery{Limit: 500}
	if filter != nil {
		if types, ok := filter.Types.ValueOK(); ok {
			q.Types = types
		}
		if did, ok := filter.DeviceID.ValueOK(); ok && did != nil {
			q.DeviceID = did
		}
		if rid, ok := filter.RoomID.ValueOK(); ok && rid != nil {
			q.RoomID = rid
		}
		if since, ok := filter.Since.ValueOK(); ok && since != nil {
			q.Since = since
		}
		if adv, ok := filter.Advanced.ValueOK(); ok && adv != nil {
			q.Advanced = *adv
		}
		if lim, ok := filter.Limit.ValueOK(); ok && lim != nil && *lim > 0 {
			q.Limit = *lim
		}
		if before, ok := filter.Before.ValueOK(); ok && before != nil && *before != "" {
			n, err := strconv.ParseInt(*before, 10, 64)
			if err != nil {
				return nil, fmt.Errorf("invalid before cursor %q: %w", *before, err)
			}
			q.Before = &n
		}
	}
	rows, err := r.Store.QueryActivityEvents(ctx, q)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ActivityEvent, len(rows))
	for i, row := range rows {
		result[i] = mapActivityEvent(row)
	}
	return result, nil
}

// SetupStatus is the resolver for the setupStatus field. Whitelisted — callable
// without authentication so the frontend can decide whether to show /setup.
func (r *queryResolver) SetupStatus(ctx context.Context) (*model.SetupStatus, error) {
	count, err := r.Store.CountUsers(ctx)
	if err != nil {
		return nil, err
	}
	mqtt, err := r.Store.GetMQTTConfig(ctx)
	if err != nil {
		return nil, err
	}
	return &model.SetupStatus{
		HasInitialUser: count > 0,
		MqttConfigured: mqtt != nil && mqtt.Broker != "",
	}, nil
}

// Me is the resolver for the me field. Returns nil when unauthenticated.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	u, ok := auth.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}
	return &model.User{
		ID:       u.ID,
		Username: u.Username,
		Name:     u.Name,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.Store.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = mapUser(u)
	}
	return result, nil
}

// DeviceStateChanged is the resolver for the deviceStateChanged field.
func (r *subscriptionResolver) DeviceStateChanged(ctx context.Context, deviceID *string) (<-chan *model.DeviceStateEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceStateChanged)
	out := make(chan *model.DeviceStateEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				if deviceID != nil && evt.DeviceID != *deviceID {
					continue
				}
				state := resolveDeviceStateFromReader(r.StateReader, device.DeviceID(evt.DeviceID))
				if state == nil {
					continue
				}
				select {
				case out <- &model.DeviceStateEvent{
					DeviceID: evt.DeviceID,
					State:    state,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAvailabilityChanged is the resolver for the deviceAvailabilityChanged field.
func (r *subscriptionResolver) DeviceAvailabilityChanged(ctx context.Context) (<-chan *model.DeviceAvailabilityEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAvailabilityChanged)
	out := make(chan *model.DeviceAvailabilityEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				select {
				case out <- &model.DeviceAvailabilityEvent{
					DeviceID:  evt.DeviceID,
					Available: d.Available,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAdded is the resolver for the deviceAdded field.
func (r *subscriptionResolver) DeviceAdded(ctx context.Context) (<-chan *model.Device, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAdded)
	out := make(chan *model.Device, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				md := mapDeviceFromReader(r.StateReader, d)
				select {
				case out <- md:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceRemoved is the resolver for the deviceRemoved field.
func (r *subscriptionResolver) DeviceRemoved(ctx context.Context) (<-chan string, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceRemoved)
	out := make(chan string, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- evt.DeviceID:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// AutomationNodeActivated is the resolver for the automationNodeActivated field.
func (r *subscriptionResolver) AutomationNodeActivated(ctx context.Context, automationID *string) (<-chan *model.AutomationNodeActivationEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventAutomationNodeActivated)
	out := make(chan *model.AutomationNodeActivationEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				na, ok := evt.Payload.(automation.NodeActivation)
				if !ok {
					continue
				}
				if automationID != nil && na.AutomationID != *automationID {
					continue
				}
				select {
				case out <- &model.AutomationNodeActivationEvent{
					AutomationID: na.AutomationID,
					NodeID:       string(na.NodeID),
					Active:       na.Active,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// LogStream is the resolver for the logStream field.
func (r *subscriptionResolver) LogStream(ctx context.Context) (<-chan *model.LogEntry, error) {
	ch, unsub := r.LogBuffer.Subscribe()
	out := make(chan *model.LogEntry, 1)

	go func() {
		defer close(out)
		defer unsub()

		for {
			select {
			case <-ctx.Done():
				return
			case e, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- mapLogEntry(e):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// ActivityStream is the resolver for the activityStream field.
func (r *subscriptionResolver) ActivityStream(ctx context.Context, advanced *bool) (<-chan *model.ActivityEvent, error) {
	showAdvanced := advanced != nil && *advanced

	ch, unsub := r.ActivityBuffer.Subscribe()
	out := make(chan *model.ActivityEvent, 16)

	go func() {
		defer close(out)
		defer unsub()

		for {
			select {
			case <-ctx.Done():
				return
			case row, ok := <-ch:
				if !ok {
					return
				}
				if !showAdvanced && (row.Type == "command.requested" || row.Type == "automation.node_activated") {
					continue
				}
				select {
				case out <- mapActivityEvent(row):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
