package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/saffronjam/saffron-hive/internal/automation"
	"github.com/saffronjam/saffron-hive/internal/device"
	"github.com/saffronjam/saffron-hive/internal/eventbus"
	"github.com/saffronjam/saffron-hive/internal/graph/model"
	"github.com/saffronjam/saffron-hive/internal/store"
)

// SetDeviceState is the resolver for the setDeviceState field.
func (r *mutationResolver) SetDeviceState(ctx context.Context, deviceID string, state model.LightStateInput) (*model.Device, error) {
	id := device.DeviceID(deviceID)
	d, ok := r.StateReader.GetDevice(id)
	if !ok {
		return nil, fmt.Errorf("device %q not found", deviceID)
	}

	cmd := device.LightCommand{
		On:         state.On,
		Brightness: state.Brightness,
		ColorTemp:  state.ColorTemp,
		Transition: state.Transition,
	}
	if state.Color != nil {
		cmd.Color = &device.Color{
			R: state.Color.R,
			G: state.Color.G,
			B: state.Color.B,
			X: state.Color.X,
			Y: state.Color.Y,
		}
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventCommandRequested,
		DeviceID:  deviceID,
		Timestamp: time.Now(),
		Payload:   device.DeviceCommand{DeviceID: id, Payload: cmd},
	})

	return mapDeviceFromReader(r.StateReader, d), nil
}

// ApplyScene is the resolver for the applyScene field.
func (r *mutationResolver) ApplyScene(ctx context.Context, sceneID string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, sceneID)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", sceneID, err)
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}

	r.EventBus.Publish(eventbus.Event{
		Type:      eventbus.EventSceneApplied,
		Timestamp: time.Now(),
		Payload:   sceneID,
	})

	return mapScene(r.StateReader, s, actions), nil
}

// CreateScene is the resolver for the createScene field.
func (r *mutationResolver) CreateScene(ctx context.Context, input model.CreateSceneInput) (*model.Scene, error) {
	sceneID := uuid.New().String()
	s, err := r.Store.CreateScene(ctx, store.CreateSceneParams{
		ID:   sceneID,
		Name: input.Name,
	})
	if err != nil {
		return nil, err
	}

	var storeActions []store.SceneAction
	for _, a := range input.Actions {
		actionID := uuid.New().String()
		sa, err := r.Store.CreateSceneAction(ctx, store.CreateSceneActionParams{
			ID:         actionID,
			SceneID:    sceneID,
			TargetType: a.TargetType,
			TargetID:   a.TargetID,
			Payload:    a.Payload,
		})
		if err != nil {
			return nil, err
		}
		storeActions = append(storeActions, sa)
	}

	return mapScene(r.StateReader, s, storeActions), nil
}

// UpdateScene is the resolver for the updateScene field.
func (r *mutationResolver) UpdateScene(ctx context.Context, id string, input model.UpdateSceneInput) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("scene %q not found: %w", id, err)
	}

	if input.Actions != nil {
		existingActions, err := r.Store.ListSceneActions(ctx, id)
		if err != nil {
			return nil, err
		}
		for _, ea := range existingActions {
			if err := r.Store.DeleteSceneAction(ctx, ea.ID); err != nil {
				return nil, err
			}
		}
		for _, a := range input.Actions {
			actionID := uuid.New().String()
			_, err := r.Store.CreateSceneAction(ctx, store.CreateSceneActionParams{
				ID:         actionID,
				SceneID:    id,
				TargetType: a.TargetType,
				TargetID:   a.TargetID,
				Payload:    a.Payload,
			})
			if err != nil {
				return nil, err
			}
		}
	}

	actions, err := r.Store.ListSceneActions(ctx, id)
	if err != nil {
		return nil, err
	}
	_ = s
	s, err = r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapScene(r.StateReader, s, actions), nil
}

// DeleteScene is the resolver for the deleteScene field.
func (r *mutationResolver) DeleteScene(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteScene(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateAutomation is the resolver for the createAutomation field.
func (r *mutationResolver) CreateAutomation(ctx context.Context, input model.CreateAutomationInput) (*model.AutomationGraph, error) {
	autoID := uuid.New().String()
	_, err := r.Store.CreateAutomation(ctx, store.CreateAutomationParams{
		ID:              autoID,
		Name:            input.Name,
		Enabled:         input.Enabled,
		CooldownSeconds: input.CooldownSeconds,
	})
	if err != nil {
		return nil, err
	}

	for _, n := range input.Nodes {
		_, err := r.Store.CreateAutomationNode(ctx, store.CreateAutomationNodeParams{
			ID:           n.ID,
			AutomationID: autoID,
			Type:         n.Type,
			Config:       n.Config,
		})
		if err != nil {
			return nil, err
		}
	}

	for _, e := range input.Edges {
		edgeID := uuid.New().String()
		_, err := r.Store.CreateAutomationEdge(ctx, store.CreateAutomationEdgeParams{
			ID:           edgeID,
			AutomationID: autoID,
			FromNodeID:   e.FromNodeID,
			ToNodeID:     e.ToNodeID,
		})
		if err != nil {
			return nil, err
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, autoID)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// UpdateAutomation is the resolver for the updateAutomation field.
func (r *mutationResolver) UpdateAutomation(ctx context.Context, id string, input model.UpdateAutomationInput) (*model.AutomationGraph, error) {
	_, err := r.Store.GetAutomation(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("automation %q not found: %w", id, err)
	}

	if input.Nodes != nil {
		existingNodes, err := r.Store.ListAutomationNodes(ctx, id)
		if err != nil {
			return nil, err
		}
		for _, en := range existingNodes {
			if err := r.Store.DeleteAutomationNode(ctx, en.ID); err != nil {
				return nil, err
			}
		}
		for _, n := range input.Nodes {
			_, err := r.Store.CreateAutomationNode(ctx, store.CreateAutomationNodeParams{
				ID:           n.ID,
				AutomationID: id,
				Type:         n.Type,
				Config:       n.Config,
			})
			if err != nil {
				return nil, err
			}
		}

		if input.Edges != nil {
			for _, e := range input.Edges {
				edgeID := uuid.New().String()
				_, err := r.Store.CreateAutomationEdge(ctx, store.CreateAutomationEdgeParams{
					ID:           edgeID,
					AutomationID: id,
					FromNodeID:   e.FromNodeID,
					ToNodeID:     e.ToNodeID,
				})
				if err != nil {
					return nil, err
				}
			}
		}
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// DeleteAutomation is the resolver for the deleteAutomation field.
func (r *mutationResolver) DeleteAutomation(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteAutomation(ctx, id)
	if err != nil {
		return false, err
	}
	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return false, fmt.Errorf("failed to reload automations: %w", err)
		}
	}
	return true, nil
}

// ToggleAutomation is the resolver for the toggleAutomation field.
func (r *mutationResolver) ToggleAutomation(ctx context.Context, id string, enabled bool) (*model.AutomationGraph, error) {
	err := r.Store.UpdateAutomationEnabled(ctx, id, enabled)
	if err != nil {
		return nil, err
	}

	if r.AutomationReloader != nil {
		if err := r.AutomationReloader.Reload(); err != nil {
			return nil, fmt.Errorf("failed to reload automations: %w", err)
		}
	}

	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, input model.CreateGroupInput) (*model.Group, error) {
	groupID := uuid.New().String()
	g, err := r.Store.CreateGroup(ctx, store.CreateGroupParams{
		ID:   groupID,
		Name: input.Name,
	})
	if err != nil {
		return nil, err
	}
	return mapGroup(r.StateReader, g, nil), nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, input model.UpdateGroupInput) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("group %q not found: %w", id, err)
	}
	name := g.Name
	if input.Name != nil {
		name = *input.Name
	}
	g, err = r.Store.UpdateGroup(ctx, store.UpdateGroupParams{
		ID:   id,
		Name: name,
	})
	if err != nil {
		return nil, err
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(r.StateReader, g, members), nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	err := r.Store.DeleteGroup(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, input model.AddGroupMemberInput) (*model.GroupMember, error) {
	memberType := device.GroupMemberType(input.MemberType)
	if memberType != device.GroupMemberDevice && memberType != device.GroupMemberGroup {
		return nil, fmt.Errorf("invalid member type %q: must be %q or %q", input.MemberType, device.GroupMemberDevice, device.GroupMemberGroup)
	}

	if memberType == device.GroupMemberGroup {
		if err := r.checkCircularDependency(ctx, input.GroupID, input.MemberID); err != nil {
			return nil, err
		}
	}

	memberID := uuid.New().String()
	m, err := r.Store.AddGroupMember(ctx, store.AddGroupMemberParams{
		ID:         memberID,
		GroupID:    input.GroupID,
		MemberType: memberType,
		MemberID:   input.MemberID,
	})
	if err != nil {
		return nil, err
	}
	return mapGroupMember(r.StateReader, m), nil
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, id string) (bool, error) {
	err := r.Store.RemoveGroupMember(ctx, id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*model.Device, error) {
	devices := r.StateReader.ListDevices()
	result := make([]*model.Device, len(devices))
	for i, d := range devices {
		result[i] = mapDeviceFromReader(r.StateReader, d)
	}
	return result, nil
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*model.Device, error) {
	d, ok := r.StateReader.GetDevice(device.DeviceID(id))
	if !ok {
		return nil, nil
	}
	return mapDeviceFromReader(r.StateReader, d), nil
}

// Scenes is the resolver for the scenes field.
func (r *queryResolver) Scenes(ctx context.Context) ([]*model.Scene, error) {
	scenes, err := r.Store.ListScenes(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Scene, len(scenes))
	for i, s := range scenes {
		actions, err := r.Store.ListSceneActions(ctx, s.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapScene(r.StateReader, s, actions)
	}
	return result, nil
}

// Scene is the resolver for the scene field.
func (r *queryResolver) Scene(ctx context.Context, id string) (*model.Scene, error) {
	s, err := r.Store.GetScene(ctx, id)
	if err != nil {
		return nil, err
	}
	actions, err := r.Store.ListSceneActions(ctx, s.ID)
	if err != nil {
		return nil, err
	}
	return mapScene(r.StateReader, s, actions), nil
}

// Automations is the resolver for the automations field.
func (r *queryResolver) Automations(ctx context.Context) ([]*model.AutomationGraph, error) {
	autos, err := r.Store.ListAutomations(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.AutomationGraph, len(autos))
	for i, a := range autos {
		graph, err := r.Store.GetAutomationGraph(ctx, a.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapAutomationGraph(graph)
	}
	return result, nil
}

// Automation is the resolver for the automation field.
func (r *queryResolver) Automation(ctx context.Context, id string) (*model.AutomationGraph, error) {
	graph, err := r.Store.GetAutomationGraph(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapAutomationGraph(graph), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.Group, error) {
	groups, err := r.Store.ListGroups(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Group, len(groups))
	for i, g := range groups {
		members, err := r.Store.ListGroupMembers(ctx, g.ID)
		if err != nil {
			return nil, err
		}
		result[i] = mapGroup(r.StateReader, g, members)
	}
	return result, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*model.Group, error) {
	g, err := r.Store.GetGroup(ctx, id)
	if err != nil {
		return nil, nil
	}
	members, err := r.Store.ListGroupMembers(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapGroup(r.StateReader, g, members), nil
}

// SensorHistory is the resolver for the sensorHistory field.
func (r *queryResolver) SensorHistory(ctx context.Context, deviceID string, from *time.Time, to *time.Time, limit *int) ([]*model.SensorReading, error) {
	q := store.SensorHistoryQuery{
		DeviceID: device.DeviceID(deviceID),
	}
	if from != nil {
		q.From = *from
	}
	if to != nil {
		q.To = *to
	}
	if limit != nil {
		q.Limit = *limit
	}
	readings, err := r.Store.QuerySensorHistory(ctx, q)
	if err != nil {
		return nil, err
	}
	result := make([]*model.SensorReading, len(readings))
	for i, rd := range readings {
		result[i] = &model.SensorReading{
			ID:          strconv.FormatInt(rd.ID, 10),
			DeviceID:    string(rd.DeviceID),
			Temperature: rd.Temperature,
			Humidity:    rd.Humidity,
			Battery:     rd.Battery,
			Pressure:    rd.Pressure,
			Illuminance: rd.Illuminance,
			RecordedAt:  rd.RecordedAt,
		}
	}
	return result, nil
}

// DeviceStateChanged is the resolver for the deviceStateChanged field.
func (r *subscriptionResolver) DeviceStateChanged(ctx context.Context, deviceID *string) (<-chan *model.DeviceStateEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceStateChanged)
	out := make(chan *model.DeviceStateEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				if deviceID != nil && evt.DeviceID != *deviceID {
					continue
				}
				state := resolveDeviceStateFromReader(r.StateReader, device.DeviceID(evt.DeviceID))
				if state == nil {
					continue
				}
				select {
				case out <- &model.DeviceStateEvent{
					DeviceID: evt.DeviceID,
					State:    state,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAvailabilityChanged is the resolver for the deviceAvailabilityChanged field.
func (r *subscriptionResolver) DeviceAvailabilityChanged(ctx context.Context) (<-chan *model.DeviceAvailabilityEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAvailabilityChanged)
	out := make(chan *model.DeviceAvailabilityEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				select {
				case out <- &model.DeviceAvailabilityEvent{
					DeviceID:  evt.DeviceID,
					Available: d.Available,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceAdded is the resolver for the deviceAdded field.
func (r *subscriptionResolver) DeviceAdded(ctx context.Context) (<-chan *model.Device, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceAdded)
	out := make(chan *model.Device, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				d, ok := r.StateReader.GetDevice(device.DeviceID(evt.DeviceID))
				if !ok {
					continue
				}
				md := mapDeviceFromReader(r.StateReader, d)
				select {
				case out <- md:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// DeviceRemoved is the resolver for the deviceRemoved field.
func (r *subscriptionResolver) DeviceRemoved(ctx context.Context) (<-chan string, error) {
	ch := r.EventBus.Subscribe(eventbus.EventDeviceRemoved)
	out := make(chan string, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- evt.DeviceID:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// AutomationNodeActivated is the resolver for the automationNodeActivated field.
func (r *subscriptionResolver) AutomationNodeActivated(ctx context.Context, automationID *string) (<-chan *model.AutomationNodeActivationEvent, error) {
	ch := r.EventBus.Subscribe(eventbus.EventAutomationNodeActivated)
	out := make(chan *model.AutomationNodeActivationEvent, 1)

	go func() {
		defer close(out)
		defer r.EventBus.Unsubscribe(ch)

		for {
			select {
			case <-ctx.Done():
				return
			case evt, ok := <-ch:
				if !ok {
					return
				}
				na, ok := evt.Payload.(automation.NodeActivation)
				if !ok {
					continue
				}
				if automationID != nil && na.AutomationID != *automationID {
					continue
				}
				select {
				case out <- &model.AutomationNodeActivationEvent{
					AutomationID: na.AutomationID,
					NodeID:       string(na.NodeID),
					Active:       na.Active,
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
